### ISSUE TITLE
Please provide 'Download PDF' experience and 'edit in github'

### ISSUE THREAD

**Issue by sandervandevelde** [MicrosoftDocs/azure-sphere-issues#10]
Other Microsoft documentation like https://docs.microsoft.com/en-us/azure/iot-edge/about-iot-edge has the ability to download the complete documentation as PDF. 
And it is possible to make pull requests on the documentation. 
Please add this ability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95a9f97-1fb1-b876-c4f5-878311a7db28
* Version Independent ID: 4b1a01aa-2f48-08b7-8f00-763bd3fa39cf
* Content: [Introduction to Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/)
* Content Source: [AzureSphere/articles/index.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/index.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback. We are planning to add PDF Download in the near future and are considering PR support for a later release.

**Comment by sandervandevelde** [comment]
Thanks. Closing issue.
