### ISSUE TITLE
writing to flash

### ISSUE THREAD

**Issue by gus-ghielec** [MicrosoftDocs/azure-sphere-issues#100]
Our program needs to retain some info in flash. Can the M4 write to flash?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d869ddd-8dfb-d767-8bc5-ecdd16711d34
* Version Independent ID: a121d5cc-02d3-d8b8-fbe8-72842cd75be9
* Content: [Manage memory and latency considerations - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/memory-latency#feedback)
* Content Source: [AzureSphere/articles/app-development/memory-latency.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/memory-latency.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi Thanks for reaching out. Please read this doc if you haven't yet:


[Using storage on Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/storage)
 
[Memory available for high-level applications](https://docs.microsoft.com/en-us/azure-sphere/app-development/application-memory-usage)

**Comment by gus-ghielec** [comment]
Thanks I have seen those but what I need is to have access to writing to the flash memory form within a program running on the M4.

Assume a program running on the M4 that needs to store some parameters on flash, like calibration data. The A7 has "mutable storage" but there is no such thing (or similar) for the M4.

**Comment by pennyo** [comment]
@gus-ghielec Information about memory use for M4 programs is here: 
https://docs.microsoft.com/en-us/azure-sphere/app-development/memory-latency

**Comment by gus-ghielec** [comment]
Maybe I am not explaining this enough! I am not finding anywhere on any docs, not even the datasheet we received under NDA, that shows how a program running on the M4 can write on the internal flash.

void mainRunningOnM4()
{
    WriteToFlash(adddress, CalibrationData);
}

**Comment by pennyo** [comment]
@gus-ghielec The M4 cores don't have write access to flash. If you need to store peristent data from the M4, the app can send the data to the A7 app, which can use the mutable storage API to write it to flash.

**Comment by gus-ghielec** [comment]
@pennyo then an app on the A7 is needed as a gateway to write mutable storage but then can this storage be accessed directly by the M4 or we would also need to use the A7 as a gateway to read the flash that was written through mutable storage?

**Comment by pennyo** [comment]
@gus-ghielec The M4 app has access only to the part of flash where its own ELF is--and that excludes the area where mutable storage might be. So your M4 app would still need to go through the A7 to read anything written in mutable storage.
