### ISSUE TITLE
Hardware Target not shown in VS 2019

### ISSUE THREAD

**Issue by Thoemmeli** [MicrosoftDocs/azure-sphere-issues#101]
Hardware Target fields are not shown in Visual Studio 2019. On the very same PC they are indeed shown in VS 2017. I do run VS 2019 Enterprise Version 16.0.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fe303-324f-149e-d664-95b3f335bbb0
* Version Independent ID: 98bfc861-2906-8225-455c-573035403312
* Content: [Target hardware dependencies](https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies#feedback)
* Content Source: [AzureSphere/articles/app-development/manage-hardware-dependencies.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/manage-hardware-dependencies.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@Thoemmeli Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
@Thoemmeli would you please try to update Visual Studio to VS 2019 16.04
