### ISSUE TITLE
missing information for those new to visual studio

### ISSUE THREAD

**Issue by sdrasnin-microsoft** [MicrosoftDocs/azure-sphere-issues#102]
The instructions on this page say to open up the Blink template, but doesn't give enough information for new people on how to do this.  I think it should instruct people to start Visual Studio, select "create a new project" (choose a project template) and then search for the Azure Blink template. That way new people don't have to hunt for the UI to do this and/or don't have to google it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d6e378-a8c1-6984-2a5c-30f2d2ae9971
* Version Independent ID: de2f147d-3f19-2f80-0427-b25c8061b51b
* Content: [Azure Sphere Blink sample application Quickstart](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-blink-application#feedback)
* Content Source: [AzureSphere/articles/quickstarts/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@sdrasnin-microsoft Thanks for providing your valuable feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@sdrasnin-microsoft In today's doc update, we've added links to Visual Studio tutorials for those who are new to it. Azure Sphere development is supported on Visual Studio Enterprise, Professional, and Community, along with multiple versions within those editions, so the Visual Studio documentation is the best place to find information for new users.

**Comment by pennyo** [comment]
Closing this issue.

**Comment by c2carey** [comment]
You win.  I have VS 16.2.3 and I can't find the Azure Blink template to save my life.
I can't find it in Github.  It is not at https://github.com/Azure/azure-sphere-samples/tree/master/Samples
There is a Raspberry Pi Blink, but I don't think that is what Sphere MT3620 is expecting.

**Comment by pennyo** [comment]
It was moved at renamed at the last major software release. You can find it in VS 2019 by picking Create a New Project from the initial splash screen and then searching for Azure Sphere on the page that pops up.

**Comment by c2carey** [comment]
Want to bet?

I File/New/Project and then I enter the search string of "Azure Sphere" and
I get back "Not finding what you are looking for"
"install more tools and features"
there is not a template that I can click on. the rest of the screen is
blank.

[image: image.png]

**Comment by richardtaylorrt** [comment]
Hi - unfortunatetly, we can't see the screenshot image attachment.  They often get lost when replying via mail.  Please can you visit this ticket online, reply and paste the image inline there.  It'd be great if you can also show the version of the Azure Sphere SDK/Extension you have installed: Extensions -> Manage Extensions -> Visual Studio Extension for Azure Sphere Preview.  Thanks.

**Comment by c2carey** [comment]
My bad. I loaded the Visual Studio Extension for Azure Sphere Preview. But I had not enabled it.

**Comment by pennyo** [comment]
Are you able to find and build the template now?

**Comment by c2carey** [comment]
Yes. My LED is flashing green.

Sorry for the inconvenience .

Chyck
