### ISSUE TITLE
output of azure device image list-installed is possibly truncated?

### ISSUE THREAD

**Issue by sdrasnin-microsoft** [MicrosoftDocs/azure-sphere-issues#103]
when I run this command, the image name is listed as "AzureSphereBlin" instead of "AzureSphereBlink1".  Why is it truncated? I searched the project files and don't see this truncation in project files. 

BTW, the documentation is great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e04f52b-e1a2-44ae-1102-efb2e2096731
* Version Independent ID: 004091d7-2e9e-9074-98b9-b1c364f8603a
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment)
* Content Source: [AzureSphere/articles/quickstarts/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Closing this post since it is meant to be part of https://github.com/MicrosoftDocs/azure-sphere-issues/issues/104
