### ISSUE TITLE
truncated (?) output 

### ISSUE THREAD

**Issue by sdrasnin-microsoft** [MicrosoftDocs/azure-sphere-issues#104]
when I run this command, the image name is listed as "AzureSphereBlin" instead of "AzureSphereBlink1". Why is it truncated? I searched the project files and don't see this truncation in project files.

BTW, the documentation is great!
I forgot to paste in the command line output in my previous post:
C:\Users\sdrasnin\Documents&gt;azsphere device image list-installed
Installed images:
 --&gt; AzureSphereBlin
   --&gt; Image type:   Application
   --&gt; Component ID: 386110d8-25ba-4127-ba02-328e2e6a65fe
   --&gt; Image ID:     f879fd1b-eb10-419f-9a5e-255886b3ae1c
Command completed successfully in 00:00:01.5441440.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e04f52b-e1a2-44ae-1102-efb2e2096731
* Version Independent ID: 004091d7-2e9e-9074-98b9-b1c364f8603a
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment)
* Content Source: [AzureSphere/articles/quickstarts/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@sdrasnin-microsoft Thanks for reaching out. Would you please provide more detail about this issue?

**Comment by AshokPeddakotla-MSFT** [comment]
@sdrasnin-microsoft Thanks you for reporting this issue. We are able to repro the issue.

![image](https://user-images.githubusercontent.com/44426435/59364511-964e6480-8d54-11e9-98d9-c336a4a26867.png)

We are checking on this issue internally and will update as earliest.

**Comment by Alberto-Vega-MSFT** [comment]
@sdrasnin-microsoft Thanks again for the feedback we will be tracking this internally so we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
