### ISSUE TITLE
Is there a way to handle CS externally?

### ISSUE THREAD

**Issue by rickeycv** [MicrosoftDocs/azure-sphere-issues#105]
I mean, I want to use three SPI devices with the same SPI bus, but in the SPIMaster_Open() function you have to specify the ChipSelect ID and when you write using SPI, it automatically clear and set this pin. Is there a way to disable "automatic mode" of CS and do it manually with another GPIO?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9eb269-0b66-ffee-7ebf-1271d958b460
* Version Independent ID: b8f0641a-6c52-a96f-7e4e-977f3a80f7e0
* Content: [Azure Sphere Applibs spi.h reference](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-spi/spi-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-spi/spi-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-spi/spi-overview.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@rickeycv Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
@rickeycv I raised your issue internally. Also assigned the issue to content author.

**Comment by richardtaylorrt** [comment]
@rickeycv - you can use the regular POSIX read() and write() functions to avoid any 'automatic' CS behaviour.  You can pass these functions the file-descriptor (fd) returned when opening a SPI interface (for either 'A' or 'B' CS, it doesn't matter in this case).  As you suggest, you can then surround these write() and read() calls with additional calls to manually drive a separate 'C' CS using a GPIO.  Please let us know if this doesn't answer your question, thanks.

**Comment by rickeycv** [comment]
Currently i'm using POSIX read() and write() for SPI and they automatically control CS pin. I can't control it externally.

Thanks.

**Comment by richardtaylorrt** [comment]
Thanks.  Yes, you're correct that read() and write() will still automatically change the CS pins.

So an alternative suggestion is to not attach anything to the CS pins at all.  Instead, you could pick 3 separate GPIOs - e.g. GPIO0, GPIO1, GPIO2.  Here's a pseudocode example:

```
spi0fd = SPIMaster_Open(SPI0, CSA, config);  // Don't connect anything to CSA.
gpio0fd = GPIO_Open(GPIO0, PushPull, High);  // Connect CS for first SPI device to GPIO0
gpio1fd = GPIO_Open(GPIO1, PushPull, High);  // Connect CS for second SPI device to GPIO1
gpio2fd = GPIO_Open(GPIO2, PushPull, High);  // Connect CS for third SPI device to GPIO2
GPIO_SetValue(gpio0fd, Low);  // Begin transaction with first SPI device
SPIMaster_WriteThenRead(spi0fd, ...);  // Or use other SPIMaster APIs, or individual write() and read(), as preferred
GPIO_SetValue(gpio0fd, High); // End transaction with first SPI device
GPIO_SetValue(gpio1fd, Low);   // Begin transaction with second SPI device
...
```

**Comment by rickeycv** [comment]
Yes, that could be a temporal solution but you are wasting one pin. Do you plan to modify API in order to disable CS "automatic control"?

Thanks.

**Comment by sergaz-msft** [comment]
Hello @rickeycv let us kindly ask you to open a new feature request on azure sphere feedback forum [here](https://feedback.azure.com/forums/915433-azure-sphere). As this is out of the scope of this doc we will close the issue and follow-up with you on the feedback forum. Please share the link when you do so.

Thank you! :)
