### ISSUE TITLE
Mass production

### ISSUE THREAD

**Issue by jeffgar** [MicrosoftDocs/azure-sphere-issues#106]
My understanding is that the recover command should not be used for mass production.  Can a clarification be added regarding when recover should be used and also a suggested alternative for mass production?

Thanks,
Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 748c2974-e65b-3d06-3198-5a15dce0435b
* Version Independent ID: 6fa329c9-f12d-d765-3202-83fe520ee840
* Content: [Azure Sphere device recovery](https://docs.microsoft.com/en-us/azure-sphere/deployment/recover#feedback)
* Content Source: [AzureSphere/articles/deployment/recover.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/recover.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@jeffgar Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by sergaz-msft** [comment]
@jeffgar please take a look at [Manufacturing connected devices doc](https://docs.microsoft.com/en-us/azure-sphere/hardware/manufacturing-guide) (it covers mass production) and let us know if it answers your questions?

Thanks!

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
