### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#107]
" Visual Studio integrated development environment (IFE) ", should be IDE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0be310e-4cea-4cb7-3fad-578140c35e0a
* Version Independent ID: a61988d8-f1c9-e283-b071-5cc024c42ca1
* Content: [Overview of Azure Sphere applications](https://docs.microsoft.com/en-us/azure-sphere/app-development/applications-overview)
* Content Source: [AzureSphere/articles/app-development/applications-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/applications-overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
Fixed, verified, and closed.
