### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Auticons1** [MicrosoftDocs/azure-sphere-issues#108]
The hyperlink "Connecting Ethernet adapters to the MT3620 development board" right under section "Hardware instructions" no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3781077-8806-0de8-85c1-a0e08b3abe8c
* Version Independent ID: f53b30fb-3874-c03e-bb5e-ab194b15fc53
* Content: [Connect Azure Sphere to Ethernet](https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet#feedback)
* Content Source: [AzureSphere/articles/network/connect-ethernet.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/connect-ethernet.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Thanks for reporting this @Auticons1 . The new link should be: https://github.com/Azure/azure-sphere-samples/blob/master/Hardware/mt3620_rdb/EthernetWiring.md

@pennyo can we fix the doc? Thank you!

**Comment by ozhernan** [comment]
documentation has not been updated

**Comment by pennyo** [comment]
Fixed, verified, and closed.
