### ISSUE TITLE
Reference to wrong app

### ISSUE THREAD

**Issue by Auticons1** [MicrosoftDocs/azure-sphere-issues#109]
The third bullet point under section "Link the device to a feed" should mention Blink app instead of HelloWorld.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e04f52b-e1a2-44ae-1102-efb2e2096731
* Version Independent ID: 004091d7-2e9e-9074-98b9-b1c364f8603a
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment)
* Content Source: [AzureSphere/articles/quickstarts/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Thanks for reporting this @Auticons1 .

I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
Fixed, verified, and closed.
