### ISSUE TITLE
Can I show sdk version at device?

### ISSUE THREAD

**Issue by matsujirushi** [MicrosoftDocs/azure-sphere-issues#11]
Can I show sdk version at device or not?

**Comment by crushonme** [comment]
Refer to [show-ota-status
](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device#show-ota-status) .
But you cannot use it before TP4.2.1 Release.

TP4.2.1 Release Notes:
The azsphere.exe command-line utility now includes the azsphere device show-ota-status command,
which returns information about which version of the Azure Sphere OS your device is running and
whether an OS update is available or being downloaded.

**Comment by matsujirushi** [comment]
```
C:\>azsphere device show-ota-status
The Azure Sphere Security Service is targeting this device with OS version TP4.2.1
Your device has the expected version of the Azure Sphere OS: TP4.2.1.
Command completed successfully in 00:00:03.4456447.

C:\>
```
