### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ozhernan** [MicrosoftDocs/azure-sphere-issues#110]
this link is broken 

and the Hardware/README.md file in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d195d27b-e2ea-6583-7d6d-b33c8392c6bf
* Version Independent ID: 59e2ee21-3862-58f0-be3a-16313d0e1251
* Content: [Release Notes 19.05](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1905#feedback)
* Content Source: [AzureSphere/articles/resources/release-notes-1905.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/release-notes-1905.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by RohitMungi-MSFT** [comment]
@ozhernan Thanks for the feedback. We are investigating into the issue and will update you shortly.

**Comment by sergaz-msft** [comment]
Thank you for reporting it @ozhernan . [This](https://github.com/Azure/azure-sphere-samples/blob/master/Hardware/README.md) is the new link.

@pennyo can we have it fixed in the doc? Thanks!

**Comment by pennyo** [comment]
FIxed, verified, and closed.
