### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ozhernan** [MicrosoftDocs/azure-sphere-issues#112]
the link in this line is broken

The README.md file describes how to change the hardware target for the samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d195d27b-e2ea-6583-7d6d-b33c8392c6bf
* Version Independent ID: 59e2ee21-3862-58f0-be3a-16313d0e1251
* Content: [Release Notes 19.05](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1905)
* Content Source: [AzureSphere/articles/resources/release-notes-1905.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/release-notes-1905.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@ozhernan Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
@pennyo Would you please review the PR with the url change? Thanks!

**Comment by Alberto-Vega-MSFT** [comment]
@ozhernan Closing this issue since the fix has been merged.
