### ISSUE TITLE
I cannot delete a temporary image

### ISSUE THREAD

**Issue by rickeycv** [MicrosoftDocs/azure-sphere-issues#113]
Hello, I built and added the image as temporary, after, I downloaded the image to the device, but when I try to delete it, I can't do it and I get the following error:
error: Could not delete component '0da14a9e-b294-4511-84b2-ba6e36ace0a2': Operation not permitted; application development capability is required ('azsphere.exe device prep-debug').

Do you have any advice?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b25cf9-8383-e69a-777f-b67925ed4855
* Version Independent ID: 994e83e1-231a-9f71-ef5c-7fe9725d2a59
* Content: [Factory floor operations - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/factory-floor-tasks#feedback)
* Content Source: [AzureSphere/articles/hardware/factory-floor-tasks.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/factory-floor-tasks.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by DixitArora-MSFT** [comment]
Hi @rickeycv Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@rickeycv We are aware of this issue and product team is actively working on the fix. Appreciate your patience in this matter.

**Comment by AshokPeddakotla-MSFT** [comment]
@rickeycv We are closing this issue for now and will update you if there are further changes regarding this issue. 

Also, if this issue needs immediate resolution and really blocking your current work, please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can help get the support ticket opened for this issue. 

If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by AshokPeddakotla-MSFT** [comment]
Update: This issue has been resolved. Please check now and reach out to support as suggested above if you still encounter this issue. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
