### ISSUE TITLE
Avnet Azure Sphere Starter Kit does not work with the Ethernet examples (new hardware configuration build required)

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#114]
The Issue
 
The current Ethernet implementation requires that the user side load a special hardware imagepackage to the device as documented here.  This package configures the Sphere Hardware and OS to use the ENC28J60 Ethernet device on interface ISU0 with GPIO 5 to expose eth0 on the board.  This hardware configuration works fine with the Seeed board, since these interfaces are available on the header pins and are not being used for other development kit features.
 
On the Avnet Starter Kit the desired Ethernet hardware solution is to use a ETH Click board.  The ETH Click board uses the same ENC28J60 device, and using the click sockets makes for a clean solution.  The problem is that the Click Sockets do not use the same interfaces (ISU0 and GPIO 5) as the existing hardware configuration.  The click sockets use ISU1 and GPIO 2.
 
Because of these differences the current hardware configuration file, will not work with the Starter Kit.
 
The Solution
 
The solution to this issue is for have another hardware configuration that uses ISU1 and GPIO 2.  This should be an easy change, but we don’t have access to this source.  Microsoft needs to make these changes and supply the new hardware configuration file.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3781077-8806-0de8-85c1-a0e08b3abe8c
* Version Independent ID: f53b30fb-3874-c03e-bb5e-ab194b15fc53
* Content: [Connect Azure Sphere to Ethernet](https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet#feedback)
* Content Source: [AzureSphere/articles/network/connect-ethernet.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/connect-ethernet.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@bawilless Thanks for the detailed and actionable feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
@bawilless Azure Sphere engineering team is already looking into this but we can not share an ETA for it yet. Please stay tuned.

**Comment by bawilless** [comment]
Thanks for the update.  This would be a great Intern task!

**Comment by Alberto-Vega-MSFT** [comment]
We will be closing this issue for now since it is being tracked internally by the Product Group. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by errohitsinghal** [comment]
@Alberto-Vega-MSFT I am currently trying to Push Azure Sphere to one of my big client and unfortunately, I am stuck due to this issue. A Must-have requirement is Ethernet Connection and We have built 90% solution over Avnet Azure SK. Do you have any idea when new ImagePackage would be available? I mean any rough ETA will help us about taking critical decisions about the product. If its possible, can we get some beta copy? 

Looking forward to your response.

**Comment by dougjr17** [comment]
Also about to propose AVNET SDK of Azure Sphere for new solution dev kickoff meeting tomorrow but now concerned since hard wired ethernet will be a critical requirement.

**Comment by richardtaylorrt** [comment]
Hi @dougjr17 - if it helps, please note that other Azure Sphere dev kits support hard-wired Ethernet.  In particular, the [Seeed MT3620 dev kit](https://www.seeedstudio.com/Azure-Sphere-MT3620-Development-Kit-US-Version.html) has an [Ethernet shield ](http://wiki.seeedstudio.com/MT3620_Ethernet_Shield_v1.0/) available.

**Comment by errohitsinghal** [comment]
@bawilless I see that this issue is closed but don't see any solution in Microsoft docs. Any update if the fix for this issue will be available anytime soon?

**Comment by bawilless** [comment]
Avnet is currently working to release an Avnet Azure Starter Kit 2.0, that will have the required signals exposed to support the current Ethernet board configuration file that Microsoft provides.  We expect to see samples this week or next.  

There is currently no software only solution to use the Starter Kit 1.0 hardware with Ethernet.
