### ISSUE TITLE
Misreference under step 3.2

### ISSUE THREAD

**Issue by Auticons1** [MicrosoftDocs/azure-sphere-issues#115]
Step 3.2 meant to mention the CAcertificate.cer download on Step 2, not Step 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79eb45a2-0b0c-6449-5acc-504fb16583e6
* Version Independent ID: fa9be175-df4d-a165-144f-8abe62ecb7ea
* Content: [Set up Azure IoT Central to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-central)
* Content Source: [AzureSphere/articles/app-development/setup-iot-central.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-central.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by KrishnaG-MSFT** [comment]
@Auticons1 Thanks for your comment. We are actively investigating and will get back to you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@Auticons1 Thanks for reporting this issue. [PR](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/pull/102) has been created to address this and changes will go live by EOD.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
