### ISSUE TITLE
remove "Note: ADC is not currently supported in software."

### ISSUE THREAD

**Issue by ozhernan** [MicrosoftDocs/azure-sphere-issues#116]
This line is not true anymore 

"Note: ADC is not currently supported in software."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877d4170-58b8-f3a6-49f0-45b7f514b7e9
* Version Independent ID: 18c7d3f7-864d-da98-447c-5aac535c8a99
* Content: [MT3620 development board user guide - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-user-guide)
* Content Source: [AzureSphere/articles/hardware/mt3620-user-guide.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-user-guide.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AjayKumar-MSFT** [comment]
@ozhernan, Thanks for bringing this to our attention! We are taking a look into this and will get back to you soon.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding author @esalc for further review and update the document as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@esalc Could you check this and update the doc?

**Comment by pennyo** [comment]
@ozhernan Thank you for your feedback--and sorry for the delayed response. This will be updated with the next docs release.

**Comment by AshokPeddakotla-MSFT** [comment]
@ozhernan As mentioned above this will be addresses in the next doc update. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by ozhernan** [comment]
this was never fixed in the doc

**Comment by pennyo** [comment]
Oops. You're right. We'll get it this time.

**Comment by ericawes** [comment]
Update published with note removed.
