### ISSUE TITLE
Doc incorrect on #of GPIOs in block. GPIO group size is actually 4, not 8

### ISSUE THREAD

**Issue by JuergenSchwertl** [MicrosoftDocs/azure-sphere-issues#117]
Doc page states "On the MT3620, GPIOs are mapped to real-time cores in **blocks of eight**, starting with GPIO 0"
however, the chip documentation states that GPIOs are grouped in blocks of 4 (four) and you can actually successfully deploy and run two M4 apps using GPIO17 (LED2_BLUE) and GPIO23 (LED4_BLUE). The example is correct that GPIO 8 & 9 fails as both are within GPIO_GROUP_2.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd75646-48be-ac9d-9c7b-72e7b37cc2af
* Version Independent ID: e82f57e8-7c97-4e66-23bc-2993ffa9e3e8
* Content: [Use peripherals in a real-time capable  application - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/use-peripherals-rt)
* Content Source: [AzureSphere/articles/app-development/use-peripherals-rt.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/use-peripherals-rt.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@JuergenSchwertl Thanks for providing feedback! Would you please provide the link to the doc that contradicts this one? Thanks

**Comment by JuergenSchwertl** [comment]
It's the beforementioned "MT3620 M4 Datasheet" referenced on the very same page. May version has it as chapter "3. Peripherals", July version it is "4. Peripherals" as 2nd paragraph.
https://github.com/Azure/azure-sphere-samples/blob/master/Samples/GPIO/GPIO_RTApp_MT3620_BareMetal/main.c#L99 also hints at it

**Comment by Alberto-Vega-MSFT** [comment]
@JuergenSchwertl Thanks for the clarification! I have passed your feedback and assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
We've updated the documentation to include the correct information. Thanks for your feedback!

Closing this issue.
