### ISSUE TITLE
Can't follow steps as ordered

### ISSUE THREAD

**Issue by davidkwoods** [MicrosoftDocs/azure-sphere-issues#119]
Attempting to check the OS version on my yet-unclaimed Azure Sphere board using "azsphere device show-ota-status" gives an error saying I need to pick a tenant.  Perhaps the "Update the OS" step should come after claiming the device and assigning it to a tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f02a9e-3e9a-4e35-238b-0578585ce396
* Version Independent ID: 7062718a-92fa-12b5-e5e0-10fed9039b59
* Content: [Update the OS - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/install-os#feedback)
* Content Source: [AzureSphere/articles/install/install-os.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-os.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@davidkwoods Thanks for the feedback! I have assigned the issue to the content author @pennyo to evaluate and update as appropriate.

**Comment by andyNYS** [comment]
i have same issue. is this a bug or simply an order of operations issue in the docs?

**Comment by senssei** [comment]
In your organization, there may be already some Azure Sphere tenats. You may create new AAD (Azure Active Directory) and scope it.

**Comment by andyNYS** [comment]
I had started with a new Azure domain and account as per the instructions as I can't use my corporate account and my old personal account was still linked to a former employer so I did not have access to Azure AD.

**Comment by bjthomson** [comment]
@davidkwoods - I concur. The instructions seem to be in the wrong order.

**Comment by tscholze** [comment]
08/11/19 - the document command order is still not fixed.
Also, the help text to create a new tenant misses a required parameter `--name`.

**Comment by doomtoo** [comment]
"Update the OS"->" How to login with an overly complicated system, required to update the OS" O.o

I spent almost an hour, trying to find out the issue with why logging in with any Microsoft account is futile, before giving up, and skipping ahead.

**Comment by tschleining** [comment]
I recommend either changing the order of the steps ('Update the OS AFTER 'Set up an account') or give more context to the resources required to work through this successfully.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Can you please review this feedback and provide your suggestions?

**Comment by kristianjaeger** [comment]
Yes, these steps did not work for me either.  Step 3 "azsphere device show-ota-status" seems to assume that the user's account is already setup. Thanks.

**Comment by pennyo** [comment]
Thank you for your feedback. Thew Auzre Sphere teamcontinues to work on the start-up experience and  is committed to improving it. 

The documentation is incorrect. The 'azsphere device show-ota-status' command requires an account and tenant.  You need to update the OS manually only if you are using one of the original Seeed development kits that has never been claimed. This has been corrected for the next publication of the documentation.

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
