### ISSUE TITLE
Removing a link-feed?

### ISSUE THREAD

**Issue by Lnk2past** [MicrosoftDocs/azure-sphere-issues#120]
I wanted to remove a link-feed that was created while running through a tutorial, but there are no details on how to do that.

e.g.

```
>azsphere feed list
Listing all feeds.
Retrieved feeds:
--> [3369f0e1-dedf-49ec-a602-2aa98669fd61] 'Retail Azure Sphere OS'
--> [82bacf85-990d-4023-91c5-c6694a9fa5b4] 'Retail Evaluation Azure Sphere OS'
--> [409021f9-dac7-4a04-9b98-0dfa10760ee5] 'test-1'
```

I want to be able to remove the `test-1` link-feed from my system. The same goes for device-groups and skus. I effectively would like to be able to wipe any configuration data setup during tutorials so that I can start clean but nothing in the documentation describes how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16395218-fa75-bd42-ee22-d48eb25f61b2
* Version Independent ID: 161af554-9e3c-550c-4b0f-792446b9decc
* Content: [Link the device to a feed - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/link-to-feed)
* Content Source: [AzureSphere/articles/deployment/link-to-feed.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/link-to-feed.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Lnk2past  Thanks for the question! We are investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@Lnk2past In order to best address your question, could you provide us with the URL of the MS Doc that you were following, if any?

**Comment by Lnk2past** [comment]
Hi @CHEEKATLAPRADEEP-MSFT & @AshokPeddakotla-MSFT, thank you for following up!

I was following this: https://docs.microsoft.com/en-us/azure-sphere/deployment/link-to-feed

and was also looking at the reference documentation: https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-feed

I am really new to all of this (Azure, Azure Sphere, IoT) so maybe I am missing something simple :)

**Comment by AshokPeddakotla-MSFT** [comment]
@Lnk2past Thanks for the information. We are checking on this internally and will update you as earliest.

**Comment by AshokPeddakotla-MSFT** [comment]
@Lnk2past Currently, there is no way to delete the feeds and cloud config once set. I suggest you, please create a feedback item on the [UserVoice](https://feedback.azure.com/forums/915433-azure-sphere?) and upvote. All the feedback you share in these forums will be monitored and reviewed by the Microsoft engineering teams responsible for building Azure.

**Comment by MarekLani** [comment]
@AshokPeddakotla-MSFT please this is crucial capability. Removing feed from group as well as removing device from group. These capabilities should be provided no matter if they are stated UserVoice or not.
