### ISSUE TITLE
Failed device recover

### ISSUE THREAD

**Issue by senssei** [MicrosoftDocs/azure-sphere-issues#121]
On the `azsphere device recover` I got

```
Starting device recovery. Please note that this may take up to 10 minutes.
Downloading recovery images...
Download complete.
Board found. Sending recovery bootloader.
Erasing flash.
Sending images.
Sending image 1 of 16.
Sending image 2 of 16.
Sending image 3 of 16.
Sending image 4 of 16.
Sending image 5 of 16.
Sending image 6 of 16.
Sending image 7 of 16.
Sending image 8 of 16.
Sending image 9 of 16.
Sending image 10 of 16.
Sending image 11 of 16.
Sending image 12 of 16.
Sending image 13 of 16.
Sending image 14 of 16.
Sending image 15 of 16.
Sending image 16 of 16.
Finished writing images; rebooting board.
error: Failed to establish communication with device after recovery. Try unplugging the device and plugging it back in, and verifying communication using 'azsphere device show-attached'. If that fails, try recovering the device again.
error: Failed to establish communication with device after recovery.
error: Command failed in 00:10:45.8765855.
```
After unplugging device is attached correctly so it doesn't look bricked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f02a9e-3e9a-4e35-238b-0578585ce396
* Version Independent ID: 7062718a-92fa-12b5-e5e0-10fed9039b59
* Content: [Update the OS - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/install-os#feedback)
* Content Source: [AzureSphere/articles/install/install-os.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-os.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by senssei** [comment]
After creating tenant manually I got 

```
D:\Users\rafal\Documents>azsphere device show-ota-status
Your device is running Azure Sphere OS version 19.06.
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support.
error: Command failed in 00:00:02.7534352.
```

**Comment by senssei** [comment]
After the second recovery 

```
Finished writing images; rebooting board.
Device ID: <redacted>
Device recovered successfully.
Command completed successfully in 00:02:41.6906338.
```

**Comment by sergaz-msft** [comment]
Hi @senssei it means that you are not seeing the issue anymore? :). Tip: You can use "-v, --verbose" when running commands to have more details on logs.

**Comment by senssei** [comment]
@sergaz-msft Thank, I think I am good now. 

I was able to move forward and by `-v` flag get more info. The device needs to be claimed before `azsphere device show-ota-status`  otherwise you will get the issue with endpoint
```
https://prod.core.sphere.azure.net/tenants/<redacted>/devices/<redacted>/images
```
It's a pity but I don't have logs from the verbose mode. If this will be observable again, I will remember to attach them for future searches by others.

PS @sergaz-msft why there is a limit to a single claim even if the device is tightly coupled to tenant and AAD? This may be impractical in production environments when the device may change it's owner and/or ADD.

**Comment by sergaz-msft** [comment]
Thanks @senssei . Regarding your feedback, we are tracking it on userVoice. Please vote for the feature request: https://feedback.azure.com/forums/915433-azure-sphere/suggestions/36316705-development-mode

Thank you!
