### ISSUE TITLE
Dimensions of DC Power Jack for MT3620 Development Kit

### ISSUE THREAD

**Issue by irwincs** [MicrosoftDocs/azure-sphere-issues#122]
I need to run the MT3620 from an external 5VDC power supply but I cannot find the dimensions of the DC jack anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877d4170-58b8-f3a6-49f0-45b7f514b7e9
* Version Independent ID: 18c7d3f7-864d-da98-447c-5aac535c8a99
* Content: [MT3620 development board user guide - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-user-guide#power-supply)
* Content Source: [AzureSphere/articles/hardware/mt3620-user-guide.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-user-guide.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by DoctorWho8** [comment]
Which kit are you referring to? The Avnet board does not have one, it has two places where headers can be installed. The other guy's one if I am correct would be the typical 2.1mm style connector.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@irwincs  Thanks for the question! We are investigating and will update you shortly.

**Comment by irwincs** [comment]
It's the original MT3620 Kit, not the new one from Avnet. [https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-user-guide#power-supply](url)

**Comment by DoctorWho8** [comment]
Okay. That's the one I saw on the Microsoft site directly. Mine was courtesy an interesting process from E14 via Avnet. I'm still trying to decide what would be a good fit for the two specialty connectors on top.

**Comment by sergaz-msft** [comment]
Hi @irwincs did you look at the [Hardware definitions for the Mediatek MT3620 MCU](https://github.com/Azure/azure-sphere-samples/blob/master/Hardware/mt3620/README.md) ?

See also: [MT3620 reference board design](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-reference-board-design)

If you were already aware of those docs and couldn't find your answer I can check internally. Do let us know.

Thanks!

**Comment by irwincs** [comment]
Yes, I looked through all these documents but couldn’t find the diameter of the DC power jack.

**Comment by sergaz-msft** [comment]
Thanks for checking it @irwincs . @esalc can we add a note on the doc specifying the characteristics of DC power jack? Thank you!

**Comment by DoctorWho8** [comment]
I see the problem. Our friend @irwincs references a set of documents describing a reference board design. Most likely the board he has was built using those specs by a different company, then mine (@irwincs what is the name on the board?) And I will wager that those specs do not describe a default power jack style. I have seen plenty so far, and there are actually a lot to choose. The default is the size I mentioned a 2.1mm sized one, which is typically used on the Arduino boards for example.

**Comment by irwincs** [comment]
Here is the board I'm using. It's the standard MT3620 Development Kit (US Version) The DC Power jack is in the lower right hand corner of the illustration: ![mt3620-rdb-headers-1902](https://user-images.githubusercontent.com/31076972/62158745-326d0480-b2de-11e9-96f1-63fe6c2e576e.png)

**Comment by DoctorWho8** [comment]
And it seems I am right. Try plugging into it a standard 2.1mm power connector from a wall wart. Do not of course plug in the wart. It should fit.

**Comment by irwincs** [comment]
It's not a 2.1 mm connector.

**Comment by DoctorWho8** [comment]
There are (or should be) several style connectors out there.  Do you have the same wart but with multiple style connectors on it? Try the different barrel styles there, and please post the size that works.

**Comment by irwincs** [comment]
Thanks for your help. My wife suggested the same thing and we have already ordered an assorted set of barrel connectors and will post the size of the connector, once I've found one that works.  The specifications for the connector should really be provided to developers in the Azure Sphere SDK documentation.

**Comment by DoctorWho8** [comment]
You are welcome of course.

**Comment by DoctorWho8** [comment]
Of course the next one is where did you obtain this kit?

**Comment by irwincs** [comment]
Here are the dimensions of the connector from the [kit](http://www.aceyoon.com/index.php?route=product/search&search=38%20PCS&description=true) that fits into the DC power jack:
1.35mm ID (0.053"), 3.50mm OD (0.138")
Could someone from Microsoft verify that these are the correct dimensions?

**Comment by sergaz-msft** [comment]
@esalc can we validate this? Thanks!

**Comment by sergaz-msft** [comment]
@irwincs thanks for your patience.

**I have confirmed with Product Group:**

- The socket is 1.3mm ID and 3.7mm OD
- The part is Cliff FC68145S. Here is a link to the datasheet: https://uk.farnell.com/cliff-electronic-components/fc68145s/dc-socket-smd-dc-8s-1-3mm-pin/dp/1889307


For questions about the MT3620 dev board (big one, aka the CDVB/RDB), the schematics are on github here: https://github.com/Azure/azure-sphere-hardware-designs/tree/master/P-MT3620RDB-1-0

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
