### ISSUE TITLE
--EnableRTCoreDebugging should be --enablertcoredebugging

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#123]
Case sensitive 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296ad092-159d-212b-e6c0-a100decf5220
* Version Independent ID: b1ce8d45-b530-929a-2fa8-96e9a9055b54
* Content: [Build a real-time capable application quickstart- Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-real-time-application)
* Content Source: [AzureSphere/articles/quickstarts/qs-real-time-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-real-time-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by KrishnaG-MSFT** [comment]
@xiongyu0523 Thanks for the comment. We will actively investigate and get back to you with an update.

**Comment by sergaz-msft** [comment]
Thanks for pointing this @xiongyu0523 . I have submitted a PR and the doc will be fixed soon.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
