### ISSUE TITLE
Uhhh guys, this isn't a PC

### ISSUE THREAD

**Issue by bjthomson** [MicrosoftDocs/azure-sphere-issues#125]
"Between stages, the board will appear functional while the next group of updates is downloaded, but during the update you should expect the board to be unresponsive for several minutes at a time." I guess we'd better not install it in anything critical then, like a lift (elevator) or an HVAC controller.
User enters lift, presses button, doors close, lift starts rising, software update. Several minutes later the panicking user is rescued by fire crew. 
HVAC reaches low-level set point, turns on heating, and we get a software update... several minutes later the humans expire from heat stroke. 
At the very least, we need to be able to specify a time to check for update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db907e3-85a6-ab65-837b-7e6a5dc12224
* Version Independent ID: dfd84d21-060c-1ba2-6341-54ed7248ae23
* Content: [Configure networking - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi)
* Content Source: [AzureSphere/articles/install/configure-wifi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/configure-wifi.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by NobleAscent** [comment]
Totally agree with this!!!. Even simple commands fail
azsphere device show-ota-status
error: The device is not responding. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes.
error: Command failed in 00:00:21.6166302.

**Comment by Alberto-Vega-MSFT** [comment]
@bjthomson and @NobleAscent Thanks for reaching out. I will pass along your feedback!

**Comment by Alberto-Vega-MSFT** [comment]
@NobleAscent @bjthomson 
Thanks again for the feedback! Would you please post this as a feedback @ https://feedback.azure.com/forums/915433-azure-sphere?query=update . This will allow the community to upvote this request.

**Comment by mdtm1g14** [comment]
I believe this may be similar to the issue I am experienceing #128, looks like it might be a common issue

**Comment by bjthomson** [comment]
My comment isn't related to #128 - that covers implementation details. I was talking about getting someone to think at a higher level - the big picture.
As requested, I've posted in the feedback forum.

**Comment by mdtm1g14** [comment]
@bjthomson Sorry I was mainly refering to the comment from @NobleAscent

**Comment by Alberto-Vega-MSFT** [comment]
Thank you! linking the post here so people coming across this issue can upvote it https://feedback.azure.com/forums/915433-azure-sphere/suggestions/38323372-more-on-update

**Comment by Alberto-Vega-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
