### ISSUE TITLE
Unable to login with personal email account on Azure Sphere Kit

### ISSUE THREAD

**Issue by manyam09** [MicrosoftDocs/azure-sphere-issues#126]
Hi, when i try to login for the command "azsphere login", i tried with my personal email account. This didn't allow me to login and thrown an error. I even tried joining Azure Active Directory. But Still i am not able to login. The below is the error i am getting

Sorry, but we’re having trouble signing you in.
 

AADSTS50020: User account 'manyam.sk@outlook.com' from identity provider 'live.com' does not exist in tenant 'OsTechnology' and cannot access the application '0b1c8f7e-28d2-4378-97e2-7d7d63f7c87f'(Azure Sphere Utility) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by harrison314** [comment]
I had the same problem.

My soliution:
* You must login to the Azure portal, in Azure Active Directory create a new user. 
* Next, use your browser to sign in and change your password when prompted.
* Login to _Azure Sphere_ using a new user account.

See <https://docs.microsoft.com/en-us/azure-sphere/install/azure-directory-account>

**Comment by sergaz-msft** [comment]
@manyam09 can you confirm that you are now unblocked so we proceed and close this issue? Thank you for providing help @harrison314 !

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
