### ISSUE TITLE
Wrong link title

### ISSUE THREAD

**Issue by persello** [MicrosoftDocs/azure-sphere-issues#127]
Under "Structs" you have a link called "Networking_NetworkInterface" but it points and is described as "UART_Config".

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ca8d7748-ebda-bfb3-ab25-02d3943f2935
* Version Independent ID: 540f019e-429a-deb6-c7da-cc7a3626c2ab
* Content: [Informazioni di riferimento per Applibs di Azure Sphere per uart.h](https://docs.microsoft.com/it-it/azure-sphere/reference/applibs-reference/applibs-uart/uart-overview#feedback)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-uart/uart-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.it-IT/blob/live-sxs/AzureSphere/articles/reference/applibs-reference/applibs-uart/uart-overview.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Thanks for pointing this out @persello . The correct link should be: https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-networking/struct-networking-networkinterface

We will fix this in next update.

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by persello** [comment]
@sergaz-msft In my opinion, being that in the uart.h documentation and being described as related to a function included in uart.h, the error is in the title (the link seems correct as it points to the UART_Config struct).

**Comment by sergaz-msft** [comment]
@persello you are absolutely right! Making that change :)!
