### ISSUE TITLE
Connection issues the Azure Sphere MT3620 starter kit

### ISSUE THREAD

**Issue by mdtm1g14** [MicrosoftDocs/azure-sphere-issues#128]
I have recently received an Azure Sphere MT3620 starter kit and have been going through the steps to get it started.  However I soon had an issue where, when performing a lot of different operations I would get the message:

"error: The device is not responding.  The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes"

I checked the OS using "azsphere device show-ota-status" and it confirmed that the device has the latest OS (version 19.07).  I then tried restarting the PC in case that was part of the issue and upon restarting I encountered a new problem.  I can no longer connect to the board via the TAP adapter.  Specifically the adapter will connect momentarily and then disconnect again, repeating this process continuously.  I have tried reinstalling the SDK and following all steps in the troubleshooting guide but to no avail.

I would greatly appreciate any input on this issue

**Comment by residentx10** [comment]
return the product because Microsoft isn't really supporting this....

**Comment by AshokPeddakotla-MSFT** [comment]
@mdtm1g14 Thanks for the feedback! We are currently investigating and will update you shortly.
Please help with the link of document on which above document feedback request is created.

**Comment by richardtaylorrt** [comment]
@mdtm1g14 - please could you try the following:
1. Save a copy of this file: `c:\windows\serviceprofiles\localservice\appdata\local\Azure Sphere Tools\restore.json`
2. Delete this file
3. Run the Services Manager (services.msc).
4. Restart the "Azure Sphere Device Communications Service".

Please let us know if this solves the problem, and send the saved .json file to AzCommunity@microsoft.com, referencing this issue.  Thanks.

**Comment by Colcothar** [comment]
While trying to create a tenant I have experienced the same error message.
I've tried the steps above and I'm still encountering the same issue.

In case it was my machine I did try it on alternative machine but I'm still getting the same error.
Got a feeling it might be the board...

**Comment by mdtm1g14** [comment]
> @mdtm1g14 - please could you try the following:
> 
> 1. Save a copy of this file: `c:\windows\serviceprofiles\localservice\appdata\local\Azure Sphere Tools\restore.json`
> 2. Delete this file
> 3. Run the Services Manager (services.msc).
> 4. Restart the "Azure Sphere Device Communications Service".
> 
> Please let us know if this solves the problem, and send the saved .json file to [AzCommunity@microsoft.com](mailto:AzCommunity@microsoft.com), referencing this issue. Thanks.

This solved the second issue and I can now communicate with the board, however, I am now back to the original issue, an example of the output is bellow:

>azsphere device show-attached
Device ID: F0BBF9435F8D47E253534FEC6A018EAC073F7EEDDE303D1E1D9FAAEFBFF3CA147166EACD8B7CFB8BA0A0BAE228D4A7382FDA92404E53C94825B63F5F85CF86E7
IP address: 192.168.35.2
Connection path: 2123
Command completed successfully in 00:00:06.0027099.

>azsphere device prep-debug
error: The device is not responding. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes.
error: Command failed in 00:00:22.0545487.

>azsphere device prep-debug
Getting device capability configuration for application development.
Downloading device capability configuration for device ID 'F0BBF9435F8D47E253534FEC6A018EAC073F7EEDDE303D1E1D9FAAEFBFF3CA147166EACD8B7CFB8BA0A0BAE228D4A7382FDA92404E53C94825B63F5F85CF86E7'.
Successfully downloaded device capability configuration.
Successfully wrote device capability configuration file 'C:\Users\mmcdo\AppData\Local\Temp\tmp184B.tmp'.
Setting device group ID 'cd037ae5-27ca-4a13-9e3b-2a9d87f9d7bd' for device with ID 'F0BBF9435F8D47E253534FEC6A018EAC073F7EEDDE303D1E1D9FAAEFBFF3CA147166EACD8B7CFB8BA0A0BAE228D4A7382FDA92404E53C94825B63F5F85CF86E7'.
Successfully disabled over-the-air updates.
Enabling application development capability on attached device.
Applying device capability configuration to device.
Successfully applied device capability configuration to device.
The device is rebooting.
Installing debugging server to device.
Deploying 'C:\Program Files (x86)\Microsoft Azure Sphere SDK\DebugTools\gdbserver.imagepackage' to the attached device.
error: The device is not responding. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes.
error: Command failed in 00:01:13.6297563.

**Comment by AshokPeddakotla-MSFT** [comment]
@mdtm1g14 Please share the link of document on which above document feedback request is created so that it can be linked. 

Also, please check the [troubleshooting steps](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#failure-to-connect-to-device) and let us know if that helps to resolve this issue.

If issue still persists, Can you please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can help get the support ticket opened for this issue.

**Comment by AshokPeddakotla-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by Colcothar** [comment]
@AshokPeddakotla-MSFT 
I've noticed the troubleshooting guide references the correct ip as "192.168.35.1".

Both @mdtm1g14 and I's boards seem to be connected on "192.168.35.2" - a different ip.
Could this perhaps explain the error we are encountering?

**Comment by Alberto-Vega-MSFT** [comment]
@Colcothar did changing the IP solved the problem?

**Comment by Colcothar** [comment]
@mdtm1g14 

I'm unsure how to go about changing the IP.
A futher thing to note, I have more than one TAP adapter - Three to be precise. Could this perhaps be why the connecting IP is different?

**Comment by Alberto-Vega-MSFT** [comment]
@Colcothar This will require some deeper analysis. Can you please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can help get the support ticket opened for this issue.

**Comment by Colcothar** [comment]
> 
> 
> @Colcothar This will require some deeper analysis. Can you please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ [AZCommunity@microsoft.com](mailto:AZCommunity@microsoft.com) with a link to this Doc/Issue as well as your subscription ID and we can help get the support ticket opened for this issue.

Will do.

I've done a little deeper analysis of my own. Seems one of my TAP adapters (a VM Ware one) seems to use 192.168.35.1

**Comment by sunillnaik** [comment]
@Colcothar how did you fix the device issue "The device is not responding2? please explain.

**Comment by Colcothar** [comment]
@sunillnaik I haven't been able to fix it. Dispite the issue being closed, its far from fixed. I gave up in the end however I theorise that there is an issue if other TAP adapters are installed, I would be interested to see your network connections.

I did file a support request, with no response.

**Comment by sunillnaik** [comment]
Thats really strange when they close issue without solving!
![httpsstatics3 seeedstudio comseeedfile2018-09bazaar925076_102991012_14](https://user-images.githubusercontent.com/44568355/74812706-55710b80-5337-11ea-9174-5f238d89147d.jpg)
I have this dev kit new one unboxed, but unable to run any azsphere command, its throws "error: The device is not responding. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes."

tried uninstalling multiple times, dev recover, but fails.

**Comment by AshokPeddakotla-MSFT** [comment]
@richardtaylorrt can you please look into this issue and update? 
@mdtm1g14 Issue is closed since a support request is created and you will receive 1-1 help with an engineer. Please share the SR number to track and check the status.
@sunillnaik This issue is bit old and a lot has changed/updated in the SDK. Latest version of SDK is 20.01. Please see [this](https://docs.microsoft.com/en-us/azure-sphere/product-overview/retail-evaluation-2001) for more information. 
Ensure that you have installed latest SDK in your system and the device is connected and your network connectivity is working properly. Please see the [troubleshooting guide](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#device-does-not-respond) for more details.

If you are still blocked, please create a new issue with complete details so that we can assist accordingly.
