### ISSUE TITLE
"you need a Microsoft work or school account"

### ISSUE THREAD

**Issue by AkosLukacs** [MicrosoftDocs/azure-sphere-issues#129]
I think the wording is less than perfect: "you need a Microsoft work or school account" sounds like you need something only a corporation or school can have. My first reaction - someone who has used Azure for some things, but not really familiar with Azure lingo - was "Does this mean I can't create one as an individual?"

I guess there is/will be an influx of people from Avnet's competition, and I guess most of those people almost certainly never dealt with Azure and AAD.
I think some clarification would be welcome...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5cac582-108f-ed21-5ebd-02d35aaf6c3d
* Version Independent ID: 47d7bf64-ece8-a0c1-b2b7-3b6b447f9a03
* Content: [Account requirements for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/azure-directory-account#create-a-new-account-and-directory-that-are-not-associated-with-any-other-account)
* Content Source: [AzureSphere/articles/install/azure-directory-account.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/azure-directory-account.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@AkosLukacs  Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by K1rdro** [comment]
Can confirm, coming in from the Avnet competition, and wording in step 3 (Specify the username@directoryname.onmicrosoft.com) is confusing.

**Comment by DoctorWho8** [comment]
Group so can I. While waiting for my rig's SDK to properly install and the device to be recognized, I read the documents in question.  I then decided to wait for those issues to be resolved before I would try again.

And I have used Azure before, typically to try out examples, and even to participate in events regarding Azure itself, not what we are talking about in these discussions.

The article implied that if someone has an Office365 account, he has access to resources running there, but not the credentials to make use of Azure itself.  

To be honest it was my understanding originally that anyone who has a regular account on the Microsoft website itself, does have access to  Azure..... But what changed when this widget and its siblings were released?

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo @esalc please check this issue and provide an update

**Comment by pennyo** [comment]
We're aware that this is a pain point and are working to improve the documentation for the next release. 

@DoctorWho8  You need an account that is associated with an Azure Active Directory (AAD). Not all accounts on the Microsoft website have one. The AAD is used to manage access to your Azure Sphere tenant.

**Comment by DoctorWho8** [comment]
@pennyo I understood the documents implicitly. And indeed it mentions what does, and what doesn't and what may not,. And there the documents need to be updated, and need to be easier to understand. For example what _does indeed_ contain an AAD function for the purposes of doing that.
You state that  > The AAD is used to manage access to your Azure Sphere tenant.<  I understand that function. Okay so what what can be created to support that.

**Comment by DoctorWho8** [comment]
Actually @AkosLukacs what we need happens to be easier to understand documentation.

**Comment by AkosLukacs** [comment]
> Actually @AkosLukacs what we need happens to be easier to understand documentation.

Exactly. Raised this issue after I already successfully claimed my device, but the documentation felt unclear.

**Comment by drunkscientist** [comment]
just got visual studio running. am part of avnet crowd coming from an arduino/esp8266 background, the documentation for this is OBTUSE at best. it feels like a full sacrifice of usability for the sake of security. tenants? domains? active account directories? i get as far as the command line but it doesnt recognize azsphere as a command. is that now how a tenant is selected?

**Comment by pennyo** [comment]
Using the azsphere command requires the Azure Sphere Developer Command Prompt, which is installed as part of the Azure Sphere DSK. It should appear on the Start menu; if not, click the Cortana search box and type ‘Azure’; it should appear in the results.  You can then proceed to determine whether you need to create aa Azure Sphere tenant or whether your organization already has one.

In addition to the tenant information in the online documentation, you might find this useful:  https://azure.microsoft.com/updates/background-on-azure-sphere-tenant-concept/

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Can you check this and provide an update?

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Please have a look at the above response and provide suggestions.

**Comment by AshokPeddakotla-MSFT** [comment]
@AkosLukacs We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
