### ISSUE TITLE
Document of claim your device

### ISSUE THREAD

**Issue by matsujirushi** [MicrosoftDocs/azure-sphere-issues#13]
Now, `Install Azure Sphere' include that claim your device. before Configure Wi-Fi.
Little confusing. And 'claim your device' is important.

I think to better you write 'claim your device' chapter after 'Configure Wi-Fi'.

**Comment by pennyo** [comment]
Thank you for your feedback. We are constantly revising the documentation and plan to address issues with claiming in an upcoming update.
