### ISSUE TITLE
Beyond I2CMaster_WriteThenRead

### ISSUE THREAD

**Issue by qiutongs** [MicrosoftDocs/azure-sphere-issues#130]
Hi,

I2CMaster_WriteThenRead API combines a "write then read" as a single bus transaction. I am wondering why Azure Sphere doesn't provide an API to generalize it to multiple read/write operations in a single transaction. 

For example, this is what Linux provides. 
https://github.com/torvalds/linux/blob/master/Documentation/i2c/dev-interface

```
  struct i2c_rdwr_ioctl_data {
      struct i2c_msg *msgs;  /* ptr to array of simple messages */
      int nmsgs;             /* number of messages to exchange */
  }
```

Thanks,
Qiutong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadc4a17-7ca5-1ef5-1952-6f3712c77a2b
* Version Independent ID: 282cf84e-09c0-a393-d21f-b264690e029c
* Content: [I2CMaster_WriteThenRead function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-i2c/function-i2cmaster-writethenread)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-i2c/function-i2cmaster-writethenread.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-i2c/function-i2cmaster-writethenread.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@qiutongs Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @qiutongs would you please provide that valuable feedback at https://feedback.azure.com/forums/915433-azure-sphere/filters/top?page=2 this way it can get upvoted and prioritized by the product team.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @qiutongs Since this feedback is related to the actual product vs the documentation. We will be closing this issue now.
Please share the link to your feedback post so others coming across this issue can go and up-vote your idea. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
