### ISSUE TITLE
Highlight 'NetworkConfig' capability in manifest must be set to true before call Networking_SetInterfaceState API

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#132]
The only place mentioned is in Networking_SetInterfaceState API reference part of document. Should provide all information in this single page to guide customer setup ethernet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3781077-8806-0de8-85c1-a0e08b3abe8c
* Version Independent ID: f53b30fb-3874-c03e-bb5e-ab194b15fc53
* Content: [Connect Azure Sphere to Ethernet](https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet)
* Content Source: [AzureSphere/articles/network/connect-ethernet.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/connect-ethernet.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
We will add this information in an upcoming release of the documentation.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Thanks for the confirmation.
@xiongyu0523 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
