### ISSUE TITLE
Why the restriction?

### ISSUE THREAD

**Issue by techyg** [MicrosoftDocs/azure-sphere-issues#134]
I don't understand the rationale for the restriction: 

"Claiming is a one-time operation that you cannot undo even if the device is sold or transferred to another person or organization"

Why have this as a limitation? Is it purely for economic / sales reasons? I can't think of a good technical reason for this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device#feedback)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi @techyg Adding the Feedback Entries below as I believe it relates with this discussion and we want to make sure that is voted so we can prioritize:

https://feedback.azure.com/forums/915433-azure-sphere/suggestions/36316705-development-mode

https://feedback.azure.com/forums/915433-azure-sphere/suggestions/36196912-allow-for-transfering-device-ownership

Thank you!

**Comment by Alberto-Vega-MSFT** [comment]
@techyg We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
