### ISSUE TITLE
Settings for the SPIMaster_Open function have swapped descriptions.

### ISSUE THREAD

**Issue by persello** [MicrosoftDocs/azure-sphere-issues#135]
"SPI_Mode_0" is described as the SPI bit order,
"SPI_BitOrder_MsbFirst" is described as the communication mode.

I think, based on the names themselves, that these descriptions are swapped.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ff26fc0d-9baf-d571-da12-01d8fefeb209
* Version Independent ID: 535d773b-af8c-23ca-cae9-20e7124db74d
* Content: [Uso di SPI con Azure Sphere](https://docs.microsoft.com/it-it/azure-sphere/app-development/spi)
* Content Source: [AzureSphere/articles/app-development/spi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.it-IT/blob/live-sxs/AzureSphere/articles/app-development/spi.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@persello Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@persello As mentioned, this will be addressed in the next update.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
