### ISSUE TITLE
[Blink] No explanation on how to change board

### ISSUE THREAD

**Issue by henrygab** [MicrosoftDocs/azure-sphere-issues#136]
This is feedback from a user who has experience with creating projects for various MCUs (Cypress PSoC, nRF52840, etc.).  This is my attempt to follow the instructions to get Blink working.  The documentation leaves the introductory user with questions, not answers, which is not desirable for a blink / hello world sample.

#### Where in the docs...
In section "Prerequisites", there's a warning/callout that the sample is based on the reference board design, such as the Seeed MT3620 DK.  It even properly warns to "check with the manufacturer's documentation" to find out whether to change the sample.

#### My thoughts when following the instructions

1. My board is the Avnet MT3620, not the Seeed MT3620 DK.
2. <grumble> … why can't VS allow me to choose my board?
3. I know that the azure-sphere-samples repository has some JSON that describes all the pins for my device.
4. How do I tell the blink sample to use that JSON for board definitions?
5. Huh.  No JSON in the blink sample... so I can't just replace it with the one from the samples repo.
6. UGH! The sample itself says not to use this as a starting point.

#### Requests / suggestions
1. First, change the `blink` sample to have, as the first line after `#include`'s, a line such as:
```C
#define BLINK_LED_PIN 9
```
and use that define (rather than a magic number) in the call to `GPIO_OpenAsOutput()`.  This can help the documentation identify the value to be changed, and the user being onboarded won't have to look through the entirety of the Blink sample to ensure it's not also used elsewhere.

2. Update the documentation to indicate that the sample uses **_only_** a single GPIO pin, and that's the only one that needs to be verified as being available for the Blink sample to work.

3. Update the documentation to indicate the two places where the GPIO value would need to change (the `#define` at the top of main.c, and the `"GPIO"` line in app_manifest_schema.json.

This is the minimum needed to ensure success with blink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d6e378-a8c1-6984-2a5c-30f2d2ae9971
* Version Independent ID: de2f147d-3f19-2f80-0427-b25c8061b51b
* Content: [Azure Sphere Blink sample application Quickstart](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-blink-application)
* Content Source: [AzureSphere/articles/quickstarts/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@henrygab Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@henrygab Thank you for the detailed feedback. We plan to revise this for the next release.

**Comment by henrygab** [comment]
@pennyo Thanks, Penny!
Another useful addition: Explicitly list the known dev kits / starter kits that do **_not_** require any changes for the sample to work.

Given this is the "hello world" equivalent, reducing mental load for an onboarding user is key, and simply checking if their board is in the list (and thus can avoid the changes) seems an even better path.  This is also currently reasonable, given the limited number of distinct kits available currently.

Finally, I want to express that the process is **_definitely_** simpler than it was a number of months ago.  So, it's definitely progress in the right direction! 👍

**Comment by AshokPeddakotla-MSFT** [comment]
@henrygab Thanks for the additional information and feedback. As @pennyo mentioned this will be addressed in the next release. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by richardtaylorrt** [comment]
Hi @henrygab - thanks again for the feedback.  FYI we have an approach for targeting different boards that is explained [here](https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies).  All of our GitHub [sample apps ](https://github.com/Azure/azure-sphere-samples)already use this, using these [hardware definition files](https://github.com/Azure/azure-sphere-samples/tree/master/Hardware).  

We're exploring how we can have a similar experience at start-of-day, either by acquiring Blinky and all of the board definitions directly from GitHub, or by replicating them in the SDK as templates.  Both options have their upsides and downsides.   

Further feedback welcome.
