### ISSUE TITLE
GCC for BareMetal

### ISSUE THREAD

**Issue by Wiz-IO** [MicrosoftDocs/azure-sphere-issues#137]
Hi,

Can you publish **gcc & linker settings** for **baremetal** as:
https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build#compile-the-application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0db551c-2484-3af9-ac08-d9978e82b445
* Version Independent ID: dea4dddf-46d1-cb41-2dcf-b77dece8c581
* Content: [How to manually build and load an Azure Sphere high-level application](https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build#compile-the-application)
* Content Source: [AzureSphere/articles/app-development/manual-build.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/manual-build.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by MicahMcKittrick-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Wiz-IO** [comment]
BTW I make this settigs and work fine... you can add to documentation 
https://github.com/Wiz-IO/platform-azure/blob/1157b786250277b2da1ce55959329363830a345b/builder/frameworks/baremetal-MT3620.py#L62

**Comment by Alberto-Vega-MSFT** [comment]
@Wiz-IO Thanks for sharing  I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Please check the above response and update the doc as appropriate.

**Comment by Wiz-IO** [comment]
you are welcome

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Thanks for an update!
@Wiz-IO We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
