### ISSUE TITLE
[BUG] [FIX KNOWN] Link for admin consent broken

### ISSUE THREAD

**Issue by henrygab** [MicrosoftDocs/azure-sphere-issues#138]
The instructions for the administrator to grant permissions to Azure Sphere say the administrator should use the link:
https://login.microsoftonline.com/common/adminconsent?client_id=0b1c8f7e-28d2-4378-97e2-7d7d63f7c87f&redirect_uri=https://docs.microsoft.com/azure-sphere/install/admin-consent-success

However, that consistently fails.  Thanks to an Escalation Engineer on the Azure IoT Developer Support Team, the issue is the parameter `redirect_uri`.  Removing that portion allows this to work.  Specifically, the above URI should be changed to simply:
https://login.microsoftonline.com/common/adminconsent?client_id=0b1c8f7e-28d2-4378-97e2-7d7d63f7c87f

For internal Microsoft tracking, this was issue:
`[REG:119081224004958] Cannot authorize Azure Sphere for [***redacted***].com AAD`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7480c6ab-3005-7ed2-aba4-518e4fda5895
* Version Independent ID: 0131fb64-58da-8646-2a58-2f7dd1ee68b6
* Content: [Obtain admin approval](https://docs.microsoft.com/en-us/azure-sphere/install/admin-consent)
* Content Source: [AzureSphere/articles/install/admin-consent.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/admin-consent.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@henrygab Thank you for helping make this docs better. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
The docs have been updated. Closing this issue.
