### ISSUE TITLE
DPS can't be created on free subscription but Sphere need DPS

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#139]
The free subscription does not allowed user to create DPS instance, even we give them 200$ free credit for 30days on the free subscription, they can't spend. As far as I know this force customers to use pay-as-you-go subscription which is not a good option for people who do not want to be charged. Any workaround?

Currently Sphere only works with IoT Hub DPS, not IoT Hub itself. This increase the difficulty in bootcamp hands-on. 

"If you choose to test an Azure IoT-based application that uses the Device Provisioning Service (DPS), be aware that DPS charges $0.10 per 1000 transactions (ten U.S. cents per one thousand transactions). We expect that the free credit that applies to many new subscriptions will cover any DPS charges, but we recommend that you check the details of your subscription agreement."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faedf864-4477-e53a-f711-0e5deaf3197b
* Version Independent ID: 416a2b64-8c07-f6bc-8393-307639bd9b3a
* Content: [Set up an Azure IoT Hub to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub)
* Content Source: [AzureSphere/articles/app-development/setup-iot-hub.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-hub.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@xiongyu0523 Thanks for your valuable feedback! Would you please post this feedback on Azure Sphere User voice? This way other customers can up-vote your proposal and helps the Product Team to  prioritize.

**Comment by xiongyu0523** [comment]
This is actually not a Azure Sphere issue. This is about how we are going to give user an out-of-box experience about seamless integration of Azure Sphere and Azure IoT Hub. 

Either we allow Azure Sphere to connect to IoT Hub without involve DPS or DPS itself can uses free subscription (may be limited to 5 devices like IoT Central did)

**Comment by Alberto-Vega-MSFT** [comment]
That's great feedback would you please add it here https://feedback.azure.com/forums/915433-azure-sphere so it can be upvoted?

**Comment by KranthiPakala-MSFT** [comment]
@xiongyu0523 We will now proceed to close this thread. If there are further questions regarding this matter, please reply and reopen the issue. We will gladly continue the discussion.
