### ISSUE TITLE
Sequence of events are not in order, for complete novices

### ISSUE THREAD

**Issue by c2carey** [MicrosoftDocs/azure-sphere-issues#141]
the Install outline is Overview, Set up azure Sphere Device, Update the OS, Set up an account, Claim your device.
I can't "Update the OS" even though the laptop sees the MT3620 on com ports.
I can't log in on the "Azure Sphere Developer Command Prompt" window until I have an Azure Active Directory, and a User Name in that AAD.
Since I can't log in, I can't run "azure show ota-status" on the ASDCPrompt.

Having a Microsoft email account is not enough to get Azure access.
I had to sign up my email user name for Azure.
Then I had to go into the AAD and add a new user.  format   "user@emailmsn.onmicrosoft.com"  where user is the name I created, emailmsn is my email user name concatentated with the domain of that email address, followed by .onmicrosoft.com
And make sure you copy the password for "user@emailmsn.onmicrosoft.com" 

so "Update the OS" should be after "Set up an account" and probably after Claim your device, although I have not struggled that far just yet.

You really need to test the sequence with pristine people and email addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f02a9e-3e9a-4e35-238b-0578585ce396
* Version Independent ID: 7062718a-92fa-12b5-e5e0-10fed9039b59
* Content: [Update the OS - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/install-os#feedback)
* Content Source: [AzureSphere/articles/install/install-os.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-os.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi @c2carey Thanks for providing your feedback. I assigned the issue to the content author so she can evaluate and update as appropriate.

**Comment by pennyo** [comment]
@c2carey  Thank you for your feedback. We're working to address this problem in the next documentation update.

**Comment by AshokPeddakotla-MSFT** [comment]
@c2carey  As mentioned, we will address this in the next update. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
