### ISSUE TITLE
Very nice!

### ISSUE THREAD

**Issue by Ravenwater** [MicrosoftDocs/azure-sphere-issues#142]
this is an awesome page. In depth architecture description with clear writing and motivation. This is absolutely perfect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c633320-8eba-48f0-4deb-7eb3a4846e6a
* Version Independent ID: 3dc7b225-3661-b61a-2b0a-13f7db2caa47
* Content: [What is Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/product-overview/what-is-azure-sphere#feedback)
* Content Source: [AzureSphere/articles/product-overview/what-is-azure-sphere.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/product-overview/what-is-azure-sphere.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi @Ravenwater Thank you for your feedback! Adding content author @pennyo

**Comment by pennyo** [comment]
@Ravenwater Thank you!
