### ISSUE TITLE
azsphere not recognized as internal or external command...

### ISSUE THREAD

**Issue by drunkscientist** [MicrosoftDocs/azure-sphere-issues#143]
so at first i thought it was because i was running windows 7, but after finally updating to 10, i still cannot access any kind of functionality of this mt3620 board. the 'azure sphere command prompt' tool that is downloaded with the azure sphere sdk for visual stuidio doesnt recognize this tool which is apparantly the only way to 'claim the device' to a 'tenant,' which is _apparantly_ the only way to program this board...
![sphereFail](https://user-images.githubusercontent.com/5492064/63735371-90452b80-c84d-11e9-82f6-5b750a2acdd8.png)

so is there any other way to interact with this board? maybe through a standard usb-ttl programmer? open a normal putty terminal or something? for what was labeled as a 'starter kit,' this isnt building confidence its going to be very usable...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d05fffa-483d-d92c-f8e9-b0deebd969c1
* Version Independent ID: c5f8e59f-c88d-5f5a-6dac-34f59fa4d4df
* Content: [Azure Sphere CLI Overview](https://docs.microsoft.com/en-us/azure-sphere/reference/overview)
* Content Source: [AzureSphere/articles/reference/overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/overview.md)
* Product: **azure-sphere**
* GitHub Login: @toddph
* Microsoft Alias: **azurespheredocs**

**Comment by KetanChawda-MSFT** [comment]
@drunkscientist Thank you for your question! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.
