### ISSUE TITLE
Azure Sphere/FTDI EEPROM/Standard configuration file instruction

### ISSUE THREAD

**Issue by hiumezu** [MicrosoftDocs/azure-sphere-issues#144]
HI Expert
WIth seeing following link instruction, I have questions.
https://docs.microsoft.com/ja-jp/azure-sphere/hardware/mt3620-mcu-program-debug-interface

There are instruction about XML file, MT3620_FTDI_Interface_4.xml,  saying no modification, but we are assuming "serial number" should be changed in case it is not the same number written on the file. Will you please tell me instruct following case?
1) What is this serial number actually stands? e.g. Production unique number that is created by moduke maker 
2) " serial number" need to be changed to the one if Module maker created Sphere Module by their own serial number.

If above assamption is correct, hoping the instruction need few explanation as above. Please advice.
 
Thank you!

H.U
 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dab9ea38-0619-6245-da46-33c535a7f92f
* Version Independent ID: 8e7168b8-055f-408a-aaad-0cefc6880d61
* Content: [MCU プログラミングおよびデバッグ インターフェイス ガイド - Azure Sphere](https://docs.microsoft.com/ja-jp/azure-sphere/hardware/mt3620-mcu-program-debug-interface)
* Content Source: [AzureSphere/articles/hardware/mt3620-mcu-program-debug-interface.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.ja-JP/blob/live-sxs/AzureSphere/articles/hardware/mt3620-mcu-program-debug-interface.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@hiumezu Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@hiumezu Please find the below answers.

1. Serial number should be the same as the one used in the GitHub XML file.
2. No, module makers should not change the serial number. Also, note that the XML file listing on the page is currently incorrect; if you are creating own programming/debug interface should use the XML file in the azure sphere hardware samples GitHub without modification.

Also, we would like to inform you that, we are updating the configuration file and changes will be done as earliest.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
