### ISSUE TITLE
How to connect to port 2342 and 2345?

### ISSUE THREAD

**Issue by aaronjense** [MicrosoftDocs/azure-sphere-issues#145]
Could you specify how to connect to port 2342 and 2345.  Those ports do not appear to be open after successful sideloading the imagepackage and manually starting the application with debug.

The remote debugging host, 192.168.35.1, shows to be available with the following ports open:
PORT     STATE SERVICE       VERSION
135/tcp  open  msrpc         Microsoft Windows RPC
139/tcp  open  netbios-ssn   Microsoft Windows netbios-ssn
445/tcp  open  microsoft-ds?
3389/tcp open  ms-wbt-server Microsoft Terminal Services

This is all after this status:
cd037ae5-27ca-4a13-9e3b-2a9d87f9d7bd
App state   : debugging
GDB port    : 2345
Output port : 2342
Core        : High-level

Ive been attempting to use:
(gdb)  target remote 192.168.35.1:2345

I now think I need to use something such as msvsmon.exe that can remote debug ARM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11552bd6-1719-603b-bc32-de16461da47f
* Version Independent ID: 1f6a56c4-ef01-2d47-57a2-e80cece5347a
* Content: [Sideload an application for testing - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/sideload-app)
* Content Source: [AzureSphere/articles/app-development/sideload-app.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/sideload-app.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi @aaronjense Thanks for reaching out. Have you seen this doc? https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build#sideload-and-debug

**Comment by aaronjense** [comment]
@Alberto-Vega-MSFT Your first link is what I needed.  I must've not delved deep enough into the documentation to find 'Develop High Level-Applications'->'Develop Without Visual Studio'.  I was just looking at 'Load and unload application during testing'.  Thank you for your time and help.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @aaronjense Thanks again for reaching out! I'm glad to hear that you were able to resolve the issue.
