### ISSUE TITLE
'arm-none-eabi-readelf.exe -S' should be 'arm-none-eabi-readelf.exe -l' to read program headers

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#146]
as title explained 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d869ddd-8dfb-d767-8bc5-ecdd16711d34
* Version Independent ID: a121d5cc-02d3-d8b8-fbe8-72842cd75be9
* Content: [Manage memory and latency considerations - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/memory-latency)
* Content Source: [AzureSphere/articles/app-development/memory-latency.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/memory-latency.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
This will be fixed in the 19.10 docs release.
