### ISSUE TITLE
Download link for Azure Sphere Developer Tools

### ISSUE THREAD

**Issue by amang2205** [MicrosoftDocs/azure-sphere-issues#15]
Where does one download the Azure Sphere Developer Tools from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97065dd-068c-6c33-310f-fd1c722cf04c
* Version Independent ID: 2301900c-0c6d-80b4-6fbd-9b0b18f9e640
* Content: [Azure Sphere installation and device setup quickstart](https://docs.microsoft.com/en-us/azure-sphere/quickstart/qs-install)
* Content Source: [AzureSphere/articles/QuickStart/qs-install.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/QuickStart/qs-install.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your question. The developer tools are currently available to private preview participants only. They are not yet publicly distributed. 

If you already have an Azure Sphere development kit, please contact the person who arranged it for you to provide access to the tools via the Microsoft Collaborate tool.

If you don't have a development kit, you can pre-order one through the [Azure Sphere website](https://www.microsoft.com/en-us/azure-sphere).

**Comment by weiqing-beijing** [comment]
Thanks. Consider this as closed.

**Comment by matsujirushi** [comment]
You can download 'Download the Azure Sphere SDK Preview for Visual Studio' link of [here](https://docs.microsoft.com/ja-jp/azure-sphere/quickstart/qs-install).
