### ISSUE TITLE
This page suggests that you must update the OS before configuring networking. That's not possible.

### ISSUE THREAD

**Issue by thecodemonk** [MicrosoftDocs/azure-sphere-issues#150]
Just got a board, newest SDK installed as of today, and I have an older version of the OS. But it will NOT update the OS until it is connected to my wifi, which the page clearly states at the top that you need to update the OS before continuing. 

I think you need to review the steps to this process. You need to be signed in, claim the device, configure networking, then reset the device for it to update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db907e3-85a6-ab65-837b-7e6a5dc12224
* Version Independent ID: dfd84d21-060c-1ba2-6341-54ed7248ae23
* Content: [Configure networking - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi#feedback)
* Content Source: [AzureSphere/articles/install/configure-wifi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/configure-wifi.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@thecodemonk Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by kmstory** [comment]
@thecodemonk if you 'azsphere device recover' from the Azure Sphere Developer Command Prompt with the board connected over USB, your computer will download the latest OS and update it over USB.

**Comment by thecodemonk** [comment]
@kmstory I think I saw that in another page somewhere, but if one is following all the steps in the order listed, they will probably not see, or do that step. If I remember,  they are told to run that command if it says their device is version is to old. My device specifically said, as an output to a previous step, that I needed to configure networking before it would update. 

While most of us are technically savvy enough to get through all this, its probably in the projects best interest to have accurate documentation.

**Comment by kmstory** [comment]
@thecodemonk those instructions are on the "Update the OS" page, 3 pages before this one in the instructions: [https://docs.microsoft.com/en-us/azure-sphere/install/install-os](https://docs.microsoft.com/en-us/azure-sphere/install/install-os)
So if someone is following the "Install" section of the docs in order, they'll update their board before they even set up an Azure account.

**Comment by thecodemonk** [comment]
Then perhaps that's the page with the issue? Step 4:
If the output from the preceding command shows that the device is running an unknown release, a deprecated release, or a TP release, you'll need to run the recovery procedure to update it

When I ran that command the output said it was ready to update but needed to be connected to a network first. It never said I was on a unknown or deprecated release. I wish I would have saved the wording, but the output of azsphere device show-ota-status definitely made me believe that I was fine and just needed to continue without doing a device recover.

**Comment by kmstory** [comment]
I agree that the "Update the OS" page should be modified. I forget what mine said on that step, but I remember that I skipped the recover at first. Then, when I tried to claim mine, it kept giving me errors saying that the device was waiting/trying to update. I think the only reason I ended up fixing it is because the page is named "Update the OS", even though the instructions aren't very clear.

Maybe they should use this example from the "Reference" section to show what will be returned if the device is _already_ up to date: [https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device#example-13](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device#example-13)

So the beginning of Step 4 would read something like:

> If the output from the preceding command includes "Your device has the expected version of the Azure Sphere OS: \<versionNumber\>", then the device is up to date and you can move on to the next step (Set up an account). Otherwise, you'll need to run the recovery procedure to update it:

> `azsphere device recover`

**Comment by thecodemonk** [comment]
I agree with that. It probably would have gone smoother for me as well if it was that clear that if it was not up to date, that I can easily just do that command.

**Comment by pennyo** [comment]
Thank you for your feedback. The Azure Sphere team continues to work on the start-up experience and is committed to improving it.

**Comment by pennyo** [comment]
We've reworked the start-up experience and documentation and believe this issue has been solved.

**Comment by AshokPeddakotla-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
