### ISSUE TITLE
Will not install on Visual Studio 2017, Version 15.9.1

### ISSUE THREAD

**Issue by kriston** [MicrosoftDocs/azure-sphere-issues#151]
When installing on a system running Visual Studio 2017, Version 15.9.1, the following message appears:
"Setup Failed
This product requires Visual Studio 2017, Version 15.9 or newer."

System: Windows 10 Pro 1903

Log attached.

[dd_VC_AzureSphere_20190909212607.log](https://github.com/MicrosoftDocs/azure-sphere-issues/files/3593229/dd_VC_AzureSphere_20190909212607.log)

**Comment by AshokPeddakotla-MSFT** [comment]
@kriston Please help with the link of document on which above document feedback request is created.
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by yuehuang010** [comment]
Hello, could you verify if VS has a pending restart?

**Comment by kriston** [comment]
There is no document. I submitted this issue per the request of Microsoft.There was also no pending restart.The installer cannot identify the latest version of Visual Studio 2017.Kris
-------- Original message --------From: AshokPeddakotla-MSFT <notifications@github.com> Date: 9/10/19  02:00  (GMT-05:00) To: MicrosoftDocs/azure-sphere-issues <azure-sphere-issues@noreply.github.com> Cc: Kriston <me@kriston.net>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/azure-sphere-issues] Will not install on Visual Studio 2017, Version 15.9.1 (#151) @kriston Please help with the link of document on which above document feedback request is created.
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/azure-sphere-issues/issues/151?email_source=notifications\u0026email_token=AASKCBEX6452I7AZEQADUH3QI4ZXPA5CNFSM4IVBZ2Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6J5VNI#issuecomment-529783477",
"url": "https://github.com/MicrosoftDocs/azure-sphere-issues/issues/151?email_source=notifications\u0026email_token=AASKCBEX6452I7AZEQADUH3QI4ZXPA5CNFSM4IVBZ2Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6J5VNI#issuecomment-529783477",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by olegkhar** [comment]
@kriston
Can you please run `"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -format json`, and paste its output here?

**Comment by kriston** [comment]
@olegkhar 

```
C:\WINDOWS\system32>"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -format json
[]

C:\WINDOWS\system32>

```

**Comment by olegkhar** [comment]
@kriston
Thanks!  Can you please run it again with these parameters: `-all -prerelease -format json`

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
