### ISSUE TITLE
Feedback on the troubleshooting guide

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#152]
First off, this is an awesome document!  It contains great details on what to look for and what to do when encountering issues.  I have some feedback that I think would made the documentation even better.

1.  Consider moving the "Failure to create three COM ports" before the "Check the TAP-Windows adapter configuration" section.  I've helped lots of Azure Sphere students who had connectivity problems.  9 times out of 10, the COM ports were not correctly installed.  By asking the reader to look at the COM ports before looking at the TAP driver details, you'll likely save them some frustration and time.

2.  Add more details to the COM ports section.  Many times when the COM ports are not correctly configured (FTDI driver not correctly installed) the devices show up under the "Other devices" folder in the device manager.  You should consider adding hints to look there for the COM ports if they are not in the correct location.  I've also seen the case where the FTDI drivers had to be installed twice on each port before it was correctly installed.  You should considering mentioning that.  

Thanks for listening  . . .

  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Troubleshooting for Azure Sphere installation and setup](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#feedback)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
@bawilless Thanks for the feedback! Those are great suggestions for things, and we'll add them to our backlog.

**Comment by abrahamiab** [comment]
Yo tuve la siguiente experiencia, realice la desinstalación, al volver a instalar este me marco erro al finalizar "azure sphere device communication service failed to start...." La solución en mi caso fue la siguiente.
1. Durante la instalación note que se creaba un nuevo adaptador de red de tipo "Tap-Windows Adapter V9" pero con el nombre Ethernet 1... en este punto actualice el nombre por Azure Sphere y le di continuar a la instalación en el botón de reintentar, la instalación finalizo de forma satisfactoria.
2. Al reclamar el dispositivo este volvió a marcar error , la solución fue la siguiente, tuve que setear la dirección IP (192.168.35.1) de forma manual en el apartado de TCP/IPv4 del adaptador "Azure Sphere".
Adjunto referencia donde viene esta especificación del adaptador de red para "Azure Sphere"
https://docs.microsoft.com/en-us/azure-sphere/network/ports-protocols-domains

Listo con esto resolví ambos problemas de comunicación e instalación para el uso de mi Tarjeta.

Yo tengo la MT3620

**Comment by pennyo** [comment]
@bawilless We updated the troubleshooting docs in the last release to incorporate much of your feedback above. Thank you for the suggestions!
