### ISSUE TITLE
non-NDA MT3620 datasheet

### ISSUE THREAD

**Issue by javagoza** [MicrosoftDocs/azure-sphere-issues#153]
Mediatek has released a non-NDA MT3620 datasheet:
https://www.mediatek.com/products/azureSphere/mt3620
MT3620-Datasheet-v1.0.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32117582-c78b-3495-da7f-8427aff8e957
* Version Independent ID: 3e771f90-da18-51bb-cd56-455f4d828e69
* Content: [MT3620 Support Status - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status#feedback)
* Content Source: [AzureSphere/articles/hardware/mt3620-product-status.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-product-status.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
@javagoza Thanks for the update!
