### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#154]
When private developers need to create a new Azure Sphere Tenant, this is the documentation where they start.  I've never had to create an Azure Sphere Tenant, because my organization already had once setup.  But I've been seeing lots of on-line comments around issues with setting up Azure Sphere Tenants, so I thought I would use a personal email address and setup a new Azure Account and try to create my own Azure Sphere Tenant to see what all the fuss is about.

Here's some constructive feedback:

1. Under the "Create a new account and directory that are not associated with any other account" section we're creating a new account and directory because we don't have a work/school account associated with a Azure Sphere Tenant.

The statement below is confusing.  I don't have a work/school account that works, I have a personal account.  But the documentation is telling me "you can create a new directory that has a new work/school account."  But I'm in this section because I only have a personal account.

2. The last step in this documentation is to claim your device.  You can't claim the device until you create an Azure Sphere Tenant.  It would be helpful to make the next step "login to your tenant, or create a new tenant"  You have documentation on creating a new tenant here:  https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant

My recommendation is for someone (not  an Azure or Azure Sphere developer) to actually walk through the process to setup a new Azure Sphere Tenant from scratch using a personal email account.  They should use a personal email account not associated with Microsoft.  To begin with they don't have a Azure Account, they don't have an Azure Sphere Tenant.  Capture all the steps with screenshots for each step.  I think if you did that you would identify all the missing/confusing pieces.  

Thanks for listening,

Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5cac582-108f-ed21-5ebd-02d35aaf6c3d
* Version Independent ID: 47d7bf64-ece8-a0c1-b2b7-3b6b447f9a03
* Content: [Account requirements for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/azure-directory-account#next-steps)
* Content Source: [AzureSphere/articles/install/azure-directory-account.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/azure-directory-account.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by NavtejSaini-MSFT** [comment]
@bawilless Thanks for the feedback. We are checking this and will get back to you.

**Comment by Alberto-Vega-MSFT** [comment]
@bawilless Thanks for the feedback and I agree with you that we have an opportunity to make this document clearer. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@bawilless Thanks again for your feedback. When we changed the user/tenant authentication model at the 19.10 release, we revised much of this material. Our goal was to make both the underlying model and the documentation clearer and easier to use. Please let us know if you feel it needs additional changes.

**Comment by asergaz** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
