### ISSUE TITLE
Clarify if the device used to create a tenant needs to be unclaimed

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#155]
Under step 1.  Connect an Azure Sphere device to your PC by USB.

A note explaining details about the device you're connecting to the PC would be helpful.  Does this device need to be an "unclaimed" device?  The documentation states that each Azure Sphere device can be used to create one and only one tenant, but it does not say anything about the status of that device being used to create the tenant.  The documentations says "This command creates a tenant but does not claim the device into the tenant. You can claim your device after you have created the tenant."

So you can claim your device once the tenant has been created, but can you use a device that's been claimed already?

Thanks listening,

Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddb0412b-b17a-01c3-120a-66c714522d58
* Version Independent ID: 4e8f2f68-ad6f-983f-3dd8-b535cc06ac80
* Content: [Create an Azure Sphere tenant](https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant)
* Content Source: [AzureSphere/articles/install/create-tenant.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/create-tenant.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by NavtejSaini-MSFT** [comment]
@bawilless Thanks for the question. We are looking into this and will get back to you regarding this.

**Comment by Alberto-Vega-MSFT** [comment]
@bawilless Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@bawilless Great question! We plan major updates to setup/tenant/claiming documentation in an upcoming release and will address this in that release.

**Comment by AshokPeddakotla-MSFT** [comment]
@bawilless As mentioned, we will address this and update the doc in an upcoming release.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
