### ISSUE TITLE
Can we use two Uarts in one application

### ISSUE THREAD

**Issue by shijiong** [MicrosoftDocs/azure-sphere-issues#156]
Dear Team,

It seems that we can use multiple uarts in our application. However, when i set the uart capability in Application manifest settings as 
 "Uart": [ "ISU0, ISU1" ],
I will get "Device would not sideload app: Application manifest specifies peripherals that use the same underlying pin (DeviceClientException)" error.
So, does this mean that one high A7 application can only use one uart?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb08dc5-0c1b-142f-c6cb-b8bba1d608c6
* Version Independent ID: 65cd99d0-6826-35ed-1bea-4842f35ab2f3
* Content: [Azure Sphere application manifest](https://docs.microsoft.com/en-us/azure-sphere/app-development/app-manifest)
* Content Source: [AzureSphere/articles/app-development/app-manifest.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/app-manifest.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@shijiong Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by bawilless** [comment]
I've seen this issue before.  

Each ISUx device consumes a block of pins on the device.  In the case of ISU0, GPIO 26, 27, 28, and 29 are all considered part of the ISU0 block.  So if your application is using ISU0 and only using the TX and RX pins (shared with GPIO 26 and 28) your application can't use the other pins in the ISU0 block (GPIOs 27 and 29) even though your not using them for the ISU0 interface.

In the case of ISU1, GPIO pins 31, 32, 33, and 34 are included in the ISU1 block.  

In your application if you want to use ISU0 and ISU1 make sure you're not trying to use GPIOs 26 - 29 (ISU0) or GPIOs 31 - 34 (ISU1).

Hope this helps!

**Comment by shijiong** [comment]
> [ "ISU0", "ISU1" ]
@AshokPeddakotla-MSFT Dear friend, I've tried this and the problem still exists.

**Comment by shijiong** [comment]
@AshokPeddakotla-MSFT @bawilless 
Thank you very much for all your help. Now the issue is resolved.
First of all, we should use "Uart": [ "ISU0", "ISU1" ]  instead of "Uart": [ "ISU0, ISU1" ] in the Application manifest settings. So, we should modify the docs page on https://docs.microsoft.com/en-us/azure-sphere/app-development/uart.
Secondly,  any try to use GPIOs 26 - 29 (ISU0) and GPIOs 31 - 34 (ISU1) should be avoid if we want to use both Uart0 and Uart1 in one A7 application.

**Comment by AshokPeddakotla-MSFT** [comment]
@shijiong Thanks for the confirmation. Glad to hear that your issue is resolved.
@pennyo Please review the above suggestions and update the doc as appropriate. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
