### ISSUE TITLE
"Uart": [ "ISU0, ISU1" ] should be modified to "Uart": [ "ISU0"," ISU1" ] 

### ISSUE THREAD

**Issue by shijiong** [MicrosoftDocs/azure-sphere-issues#157]
[Enter feedback here]
According to the test, the uart capability in Application manifest settings should be changed to
"Uart": [ "ISU0", "ISU1" ] instead of "Uart": [ "ISU0, ISU1" ] if user want to use both Uart0 and Uart1 in one A7 application.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd2f13a7-82f4-418b-6e28-df525c5e9c63
* Version Independent ID: 661299b9-b908-e4a3-2b9e-30cb34c71510
* Content: [UART on Azure Sphere - overview](https://docs.microsoft.com/en-us/azure-sphere/app-development/uart#feedback)
* Content Source: [AzureSphere/articles/app-development/uart.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/uart.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Linking the conversation here: https://github.com/microsoftdocs/azure-sphere-issues/issues/156

**Comment by AshokPeddakotla-MSFT** [comment]
@shijiong Thanks for the feedback. [PR](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/pull/113) has been created to update the doc and changes will go live once it has been merged. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
