### ISSUE TITLE
An image with the same ID ('72089893-1888-4297-a9f8-5c534c9f8ac7') already exists.

### ISSUE THREAD

**Issue by jeffgar** [MicrosoftDocs/azure-sphere-issues#158]
When trying to update a feed I get an error saying that the image already exists.  However it isn't clear how to resolve that.  Do I need to change something, increment a version perhaps?  

Thanks,
Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ef8942-08f8-51b6-d3ef-85652e65b03d
* Version Independent ID: 1a567fe3-447a-a688-4bec-cdc87e850011
* Content: [Azure Sphere CLI image-set (ims) command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-image-set)
* Content Source: [AzureSphere/articles/reference/azsphere-image-set.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-image-set.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@jeffgar Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by bawilless** [comment]
I've encountered this issue before and was able to resolve the issue by changing the name field in the app_manifest.json file.  It looks like AS3 identifies application builds by the ComponentId and the Name fields in the app_manifest.json file.  

 "Name": "MyNewUniqueName",

I use the name field in conjunction with my application version string, that is I make sure they match before building a new production image and uploading it to AS3.

Hope this helps!

**Comment by Alberto-Vega-MSFT** [comment]
@jeffgar was the previous suggestion helpful?

**Comment by Alberto-Vega-MSFT** [comment]
@jeffgar Since we haven't heard back from you. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue. 
@bawilless Thanks for the help!
