### ISSUE TITLE
[Warning]No Azure Sphere tenants found under the selected AAD user

### ISSUE THREAD

**Issue by gowribhuthanatha** [MicrosoftDocs/azure-sphere-issues#159]
Hi, I created an Azure sphere tenant. After that I try to log in from the Azure Sphere Developer Command Prompt Window and I get the following Warning: No Azure Sphere tenants found under the selected AAD user.

Can you please let me know where am I going wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddb0412b-b17a-01c3-120a-66c714522d58
* Version Independent ID: 4e8f2f68-ad6f-983f-3dd8-b535cc06ac80
* Content: [Create an Azure Sphere tenant](https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant)
* Content Source: [AzureSphere/articles/install/create-tenant.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/create-tenant.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for your question. Please provide us with the link to the documentation you are referring to so we can better assist.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @gowribhuthanatha Thank you for your feedback. Could you link the URL of the documentation you were following? That way, we can pass your feedback to the appropriate content author?

**Comment by Alberto-Vega-MSFT** [comment]
@gowribhuthanatha Did you get to see my previous message? Are you still seeing this issue?

**Comment by Alberto-Vega-MSFT** [comment]
Hi @gowribhuthanatha do you still need help?

**Comment by gowribhuthanatha** [comment]
Thank you. I was able to successfully create a  tenant now.

Regards,

Gowri B

________________________________

**Comment by gowribhuthanatha** [comment]
Hi Albreto,

I am trying to create a tenant as per the documentation below:

https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant

but i get the following error:
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant>
Create an Azure Sphere tenant | Microsoft Docs<https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant>
Create an Azure Sphere tenant. 03/11/2019; 2 minutes to read; In this article. An Azure Sphere tenant isolates your organization's Azure Sphere devices from all other Azure Sphere devices and enables your organization to manage them.
docs.microsoft.com


C:\Users>azsphere tenant create --name MyTenant1
error: Failed to create an Azure Sphere tenant with name 'MyTenant1'.
Trace ID: deb14d9a-d576-4a36-ac70-1f05bd8cc7fe
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support.
error: Command failed in 00:00:16.3381370.

can you please help?


Regards,

Gowri B

________________________________

**Comment by gowribhuthanatha** [comment]
adding to my previous email, please find the additional log as below:
C:\Users>azsphere tenant -v create --name MyAzureSpherePOCTenant
Azure Sphere Utility version 19.5.4.53731
Copyright (C) Microsoft Corporation. All rights reserved.

Start time (UTC): Wednesday, 25 September 2019 18:48:15
verbose: Creating new Azure Sphere tenant with name 'MyAzureSpherePOCTenant'.
verbose: No Azure Sphere tenants found under the selected AAD user.
verbose: Successfully logged in with the selected AAD user. This authentication will be used for subsequent commands.
verbose: No SerialSlipToTunService port is set in the registry; defaulting to 56665.
verbose: Using attached device ID '220E341419680E17ABBA143C313A48535E3530D2158C85A9A26B43865DB25723E1BDA905D351EC4906331BF87F5104AFA7DAE169DD6D217EF6E6E211CE87AA5E'.
error: Failed to create an Azure Sphere tenant with name 'MyAzureSpherePOCTenant'.
Trace ID: 9c2e963b-cfd1-4cb4-8825-dc5b07adcad0
Received HTTP response: 400 (Bad Request)
-> Endpoint: POST https://prod.core.sphere.azure.net/tenants
-> Content Type: NULL
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support. Trace ID: 9c2e963b-cfd1-4cb4-8825-dc5b07adcad0
Response: {
  "RequestUri": "https://prod.core.sphere.azure.net/tenants",
  "StringContent": null,
  "StatusCode": 400,
  "ReasonPhrase": "Bad Request",
  "Method": {
    "Method": "POST"
  },
  "RequestHeaders": {
    "x-open-tracing-span-traceid": [
      "9c2e963b-cfd1-4cb4-8825-dc5b07adcad0"
    ],
    "User-Agent": [
      "azsphere/19.5.4.53731",
      "Microsoft.Azure.Sphere.Tools.SecurityServiceOperations/19.5.4.53731",
      "(Microsoft Windows NT 6.2.9200.0)"
    ]
  },
  "ResponseHeaders": {
    "Request-Context": [
      "appId=cid-v1:b521a172-2c33-47a3-9b54-05ca8b9a1053"
    ],
    "Strict-Transport-Security": [
      "max-age=31536000; includeSubDomains"
    ],
    "X-Content-Type-Options": [
      "nosniff"
    ],
    "Date": [
      "Wed, 25 Sep 2019 18:49:07 GMT"
    ],
    "Server": [
      "Kestrel"
    ]
  },
  "ContentType": null
}
Microsoft.Azure.Sphere.PublicApi.Clients.Exceptions.PublicApiBadRequestException: Bad Request
   at Microsoft.Azure.Sphere.PublicApi.Clients.PublicApiClient.<CreateTenantAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Sphere.Tools.SecurityServiceOperations.TenantManager.<CreateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Sphere.Tools.AzSphere.TenantCreateCommand.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Sphere.Tools.AzSphere.TenantCreateCommand.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommandLine.SuperCommand`1.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CommandLine.EntryPoint.<ExecuteAsync>d__1`2.MoveNext()
error: Command failed in 00:00:52.8698312.


Regards,

Gowri B

________________________________

**Comment by Alberto-Vega-MSFT** [comment]
Hi @gowribhuthanatha You can only create a tenant once using this device, so subsequent attempts to create a tenant will fail.

Once you create a tenant it will "live" in the AAD account you are logged in at the moment of creation.  In order to find the tenant you originally created you have to log in to the correct AAD account.

**Comment by gowribhuthanatha** [comment]
Hi Alberto, From your reply it seems that this device has been claimed by some other tenant. is there any way to figure out which is the account/tenant that owns this device at present?
Thank you


Regards,

Gowri B

________________________________

**Comment by Alberto-Vega-MSFT** [comment]
@gowribhuthanatha I don't think there is a way for you to do this. Please ask the people in your team about the tenant they used.

**Comment by gowribhuthanatha** [comment]
Thank you very much for the support.



Regards,

Gowri B

________________________________

**Comment by Alberto-Vega-MSFT** [comment]
@gowribhuthanatha Thanks for reaching out. If you have any feedback about the docs please feel free to reach out here or if you need support please open a question on MSDN forum https://social.msdn.microsoft.com/Forums/en-US/home?forum=azuresphere
