### ISSUE TITLE
device recovery to TP4.2.1

### ISSUE THREAD

**Issue by BillyHsu** [MicrosoftDocs/azure-sphere-issues#16]
Dear Sir,

After recover my device to TP4.2.1, the error message as below.
How to solve it?
Thanks.

Starting device recovery. Please note that this may take up to 10 minutes.
Board found. Sending recovery bootloader.
Erasing flash.
Sending images.
Sending image 1 of 16.
Sending image 2 of 16.
Sending image 3 of 16.
Sending image 4 of 16.
Sending image 5 of 16.
Sending image 6 of 16.
Sending image 7 of 16.
Sending image 8 of 16.
Sending image 9 of 16.
Sending image 10 of 16.
Sending image 11 of 16.
Sending image 12 of 16.
Sending image 13 of 16.
Sending image 14 of 16.
Sending image 15 of 16.
Sending image 16 of 16.
Finished writing images; rebooting board.
error: Timed out trying to get device security state after recovery
error: Timed out waiting for boot after recovery.
error: Device recovery failed. Please ensure you are using the correct recovery
images, and that the SDK is up to date.
error: Command failed in 00:03:51.1747530.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d97065dd-068c-6c33-310f-fd1c722cf04c
* Version Independent ID: 2301900c-0c6d-80b4-6fbd-9b0b18f9e640
* Content: [Azure Sphere installation and device setup quickstart](https://docs.microsoft.com/zh-tw/azure-sphere/quickstart/qs-install)
* Content Source: [AzureSphere/articles/QuickStart/qs-install.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/QuickStart/qs-install.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by crushonme** [comment]
I have the same issue. And the device comes back after click the reset button.
![](https://crushonme-1256821258.cos.ap-shanghai.myqcloud.com/AzureSphere.png)
![](https://crushonme-1256821258.cos.ap-shanghai.myqcloud.com/AzureSphere2.png)

**Comment by JamesLee-MSFT** [comment]
Hi,

I ran through the steps on here and did not get the error.

https://docs.microsoft.com/en-us/azure-sphere/quickstart/qs-install

Can you confirm you installed the 4.2.1 VS_Tools_Preview_For_Azure_Sphere.exe update?


![image](https://user-images.githubusercontent.com/41642493/44806194-22531f00-ab7b-11e8-80a1-9bf6436b6284.png)

**Comment by JamesLee-MSFT** [comment]
Hi, I received clarification from the product team.  Basically, the error is caused by the device still in the rebooting process.  The upgrade is still successful and resetting the device will fix the problem as you have already done so in your screen shot.

Thanks.

James

**Comment by BillyHsu** [comment]
Hi James,

How to process the resetting on the device? 
We already did the recovery process to TP4.2.1.
My VS_Tools_Preview_For_Azure_Sphere.exe is 0.49.2.45617. 

Best Regards,
Billy

**Comment by BillyHsu** [comment]
Dear Sir,

I try to rebuild the development in new computer.
In new system to recovery it again, the question in gone now.
Thanks.

Billy
