### ISSUE TITLE
Documentation needs to specify for Visual Studio 2019, you must install the "Linux development with C++" workload, or the SDK will not install

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#160]
I ran into this issue myself and I've been helping others having issues installing the Azure Sphere tools.  On this page it states that for VS installations "You can install any workloads, or none."  While this is true for VS2017, this is not true for VS2019.  In my experience if you install VS2019 with no workloads, then the Azure Sphere SDK will not install.  

I recommend trying to install VS2019 with no workloads on a fresh Windows10 install, then try to install the Azure Sphere SDK, to verify this behavior for yourself.  Next install the "Linux development with C++" workload and try the SDK install again.

I think the fix is an easy one . . . 

Change: "You can install any workloads, or none."
To: "For Visual Studio 2019 development environments, you must install the "Linux development with C++" workload before attempting to install the Azure Sphere SDK."

Thanks for listening,

Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de08ad95-5a5b-7d0d-860c-f9eb2e20c25e
* Version Independent ID: 496bd01d-da35-136d-cfec-c5b4c5479bab
* Content: [Set up your device and install the Azure Sphere SDK](https://docs.microsoft.com/en-us/azure-sphere/install/install#feedback)
* Content Source: [AzureSphere/articles/install/install.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi @bawilless Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
We are looking into this and will update the issue when we have more information.

**Comment by olegkhar** [comment]
@bawilless
We're sorry to hear that the first installation attempt didn't work for you.  This scenario is supported, and we're interested in learning why.  There might still be logs on your system that will help us with our investigation; they can be collected by running the VSCollect tool at https://aka.ms/vscollect [output stored as `%TEMP%\vslogs.zip`].

The best way to share the logs with us is by reporting an issue though https://developercommunity.visualstudio.com/spaces/8/index.html

Thanks!

**Comment by pentium10** [comment]
I installed today no workloads and everything looks fine. So no linux c++ is necessary

**Comment by pennyo** [comment]
Closing issue
