### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by ronitsrma16** [MicrosoftDocs/azure-sphere-issues#161]
Hii,
I recently got an Azure MT3620. when I open my Azure sphere command prompt and try to see OTA version one login window pop-out but when I logged in with my Microsoft account, it's saying 

![azure error](https://user-images.githubusercontent.com/43707140/66259185-adb1d180-e7cb-11e9-8503-4b43d1101b10.JPG)
 
my email does not exist in tenant. To know full error open the image linked above.

**Comment by richardtaylorrt** [comment]
Hi - you can't currently use a personal account (such as @outlook.com) with Azure Sphere.  For more advice on this, and how to create a work/school account that will work, please see [here](https://docs.microsoft.com/en-us/azure-sphere/install/azure-directory-account).

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
