### ISSUE TITLE
OTA deployment

### ISSUE THREAD

**Issue by ronitsrma16** [MicrosoftDocs/azure-sphere-issues#162]
Hii
After giving feed command I got a message that command completed successfully then I pressed Reset button but still LED is not blinking. Then I checked with the image list-installed command and it's saying NO installed images. 
can you tell where could be the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e04f52b-e1a2-44ae-1102-efb2e2096731
* Version Independent ID: 004091d7-2e9e-9074-98b9-b1c364f8603a
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment)
* Content Source: [AzureSphere/articles/quickstarts/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by RohitMungi-MSFT** [comment]
@ronitsrma16 Could you please let us know the documentation link that you followed for this setup. This will help us direct you to the right team.

**Comment by ronitsrma16** [comment]
https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment

**Comment by sergaz-msft** [comment]
Hi @ronitsrma16 can you share with us the output of performing the different steps?

1. azsphere feed list
2. azsphere device link-feed --dependentfeedid 3369f0e1-dedf-49ec-a602-2aa98669fd61 --imagepath <path-to-image> --newfeedname <unique-name>

Also make sure you are connected to the internet so that the application can be installed OTA. It can take some time. What's the result of:

1. azsphere device wifi list

Finally let us know the output of:

1. azsphere device show-ota-config
2. azsphere device show-ota-status

Thanks!

**Comment by ronitsrma16** [comment]
I think the problem is something else. When I'm trying to connect my device with my mobile hotspot my device is working fine but when trying to connect my D-Link modem its not able to connect and I think that is the reason I'm not able to get OTA updates.  

The command to connect to wifi is : 

C:\Users\CG-DTE\Documents>azsphere device wifi add --ssid "Sai sadan 5th" --key "6305253810"- 
ID                  : 0
SSID                : Sai sadan 5th
Configuration state : enabled
Connection state    : unknown
Security state      : psk

And then the response of that command

C:\Users\CG-DTE\Documents>azsphere device wifi show-status
SSID                :
Configuration state : unknown
Connection state    : disconnected
Security state      : unknown
Frequency           :
Mode                :
Key management      : UNKNOWN
WPA State           : SCANNING
IP Address          :
MAC Address         : 00:02:b5:03:4a:dc

Command completed successfully in 00:00:02.3888813.

are Are you able to identify the problem?

**Comment by sergaz-msft** [comment]
Hi @ronitsrma16 ,
I am glad that the original issue is now resolved.

Please [see here](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi#set-up-wi-fi-on-your-azure-sphere-device) for more details around limitations of Wifi, eg:

- Azure Sphere devices do not support WEP, nor can they connect to hidden SSIDs. Network SSIDs are case-sensitive

If your issue persists with your modem and you believe that you have all prerequisites, please open a new issue under the proper doc or file a new issue on [MSDN](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azuresphere).

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
