### ISSUE TITLE
Moving from Prototype to Manufacturing

### ISSUE THREAD

**Issue by irwincs** [MicrosoftDocs/azure-sphere-issues#163]
We've prototyped a device using the MT3620 and want to initiate the manufacturing process. We have a reference design that leverages the MT3620 and requires RS-232 to TTL conversion support and 12VDC to 5 VDC support. (https://www.irwincs.com)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b317d-f63d-82da-2e1a-258a9f526c69
* Version Independent ID: 0dcdcbc8-f6d9-f5d7-22c9-57fdec54ed39
* Content: [Manufacturing connected devices - Azure Sphere](https://docs.microsoft.com/en-ca/azure-sphere/hardware/manufacturing-guide#feedback)
* Content Source: [AzureSphere/articles/hardware/manufacturing-guide.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/manufacturing-guide.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by KranthiPakala-MSFT** [comment]
@irwincs Thanks for reaching out. At this time we are reviewing the ask and will provide an update as appropriate.

**Comment by sergaz-msft** [comment]
Hi @irwincs not sure I understand the question? Can you please provide more details and how it relates with the document? Thanks!

**Comment by irwincs** [comment]
Hi António,

We are an independent software vendor and we have developed a solution using the Azure Sphere MT3620 Software Development Kit; however, it’s not clear from the documentation how to move this solution forward into manufacturing.

Do we need to work with Microsoft directly or one of Microsoft’s silicon partners?

Are you able to provide some direction?

Please advise.

Thanks and best regards,

George Irwin, P.Eng.
President/Chief Software Engineer

Irwin Consulting Services Inc.
w| 647.938.8463 m| 416.301.6127 f| 905.471.9834
email | george@irwincs.com<mailto:george@irwincs.com> <mailto:george@irwincs.com>
30 Ridley Crescent | Markham, ON | L3S 3P5
https://www.irwincs.com<https://www.irwincs.com/>

**Comment by sergaz-msft** [comment]
Hi @irwincs ,
Thanks for the clarification. 

> Do we need to work with Microsoft directly or one of Microsoft’s silicon partners?

Yes, please can you reach out to us using the email AZCommunity@microsoft.com with a link to this Doc/Issue? We will follow-up with you with additional steps.

Thank you!

**Comment by irwincs** [comment]
We've prototyped a device using the MT3620 and want to initiate the manufacturing process. We have a reference design that leverages the MT3620 and requires RS-232 to TTL conversion support and 12VDC to 5 VDC support. https://www.irwincs.com

We are an independent software vendor and we have developed a solution using the Azure Sphere MT3620 Software Development Kit; however, it's not clear from the documentation how to move this solution forward into manufacturing.

Do we need to work with Microsoft directly or one of Microsoft's silicon partners?

Are you able to provide some direction?

Please advise.

Thanks and best regards,

George Irwin, P.Eng.
President/Chief Software Engineer

Irwin Consulting Services Inc.
w| 647.938.8463 m| 416.301.6127 f| 905.471.9834
email | george@irwincs.com<mailto:george@irwincs.com> <mailto:george@irwincs.com>
30 Ridley Crescent | Markham, ON | L3S 3P5
https://www.irwincs.com<https://www.irwincs.com/>

**Comment by sergaz-msft** [comment]
Thank you @irwincs . I am closing this issue as we will follow-up with you on email.

If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
