### ISSUE TITLE
Incorrect parameter when adding wifi

### ISSUE THREAD

**Issue by Bradley-Cooley** [MicrosoftDocs/azure-sphere-issues#164]
The command to add wifi is incorrect. 

azsphere device wifi add --ssid &lt;yourSSID&gt; --psk &lt;yourNetworkKey&gt;

The --psk parameter should be replaced with --key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db907e3-85a6-ab65-837b-7e6a5dc12224
* Version Independent ID: dfd84d21-060c-1ba2-6341-54ed7248ae23
* Content: [Configure networking - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi#feedback)
* Content Source: [AzureSphere/articles/install/configure-wifi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/configure-wifi.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@Bradley-Cooley Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
The parameter changed to --psk with the 19.09 release.
Closing issue.
