### ISSUE TITLE
libtlsutils.so need to be added to project

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#165]
This page does not describe this mandatory step so compilation will fail when user try to use mutual authentication. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f45a46-1962-0a73-0bdd-df377f382d38
* Version Independent ID: 80147160-89c5-3683-8c4e-557b38678acf
* Content: [Connect to web services - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/curl#feedback)
* Content Source: [AzureSphere/articles/app-development/curl.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/curl.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by YutongTie-MSFT** [comment]
@xiongyu0523 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

@pennyo 
Hi Pennyo, could you please check this issue and update the document if necessary? Thanks.

**Comment by asergaz** [comment]
Hello @pennyo can you please follow-up on this request? Thanks!

**Comment by pennyo** [comment]
This is fixed in the upcoming release of the docs.
