### ISSUE TITLE
When do you know "GPIO 9 is not accessible"?

### ISSUE THREAD

**Issue by djaus2** [MicrosoftDocs/azure-sphere-issues#166]
[Enter feedback here]
_In the section "Build and run the Blink sample" it says:
_"If you are using hardware on which GPIO 9 is not accessible, change the GPIO. For example, on the Seeed Mini Dev Board, change GPIO 9 to GPIO 7:"__
On my Seed MT3620 not making the change was correct.

So my question is on what boards should you make that change? The point needs detail.
NB: I skim read that instruction and made the change and didn't get the blink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d6e378-a8c1-6984-2a5c-30f2d2ae9971
* Version Independent ID: de2f147d-3f19-2f80-0427-b25c8061b51b
* Content: [Azure Sphere Blink sample application Quickstart](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-blink-application)
* Content Source: [AzureSphere/articles/quickstarts/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by himanshusinha-msft** [comment]
@djaus2  :Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by asergaz** [comment]
@djaus Thanks for the feedback!

As the important note on this doc says:

These instructions assume that you are using hardware that follows the [MT3620 reference board design (RBD)](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-reference-board-design), such as the Seeed MT3620 Development Kit. If you are using different Azure Sphere hardware, consult the manufacturer's documentation to find out whether the GPIO is exposed and how to access it. You might need to update the sample code and the "Gpio" field of the app_manifest.json file to use a different GPIO.

Did you miss that note or still think we need to add more clarity on the doc?

Thanks :)!

**Comment by asergaz** [comment]
@djaus2 I had a sync with the author of this doc and understood better your feedback :)!

There is both:
1.	The [regular Seeed dev kit.](https://www.seeedstudio.com/Azure-Sphere-MT3620-Development-Kit-US-Version.html)
2.	The [mini Seeed dev kit.  ](https://www.seeedstudio.com/MT3620-Mini-Dev-Board-p-2919.html)

When on the doc says "For example, on the Seeed Mini Dev Board, change GPIO 9 to GPIO 7" it applies only to the 2nd which explains why not making the change on the 1st worked well.

Requesting @pennyo to add more clarity on the doc based on your feedback.

Thank you so much!

**Comment by asergaz** [comment]
Hi @pennyo can you please follow-up on this issue? Thanks

**Comment by asergaz** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
