### ISSUE TITLE
mention how to read current os version

### ISSUE THREAD

**Issue by pentium10** [MicrosoftDocs/azure-sphere-issues#167]
You are saying that "If your device is already in use and is running the 18.11 OS release (or more recent), it should receive the updated OS after it connects to the internet"
You should also mention, how to check the current OS version, or link to a page where it is described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f02a9e-3e9a-4e35-238b-0578585ce396
* Version Independent ID: 7062718a-92fa-12b5-e5e0-10fed9039b59
* Content: [Update the OS - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/install-os#feedback)
* Content Source: [AzureSphere/articles/install/install-os.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-os.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by MarileeTurscak-MSFT** [comment]
@pentium10 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Alberto-Vega-MSFT** [comment]
@pentium10 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
We are updating the documentation with a section that describes how to find OS and SDK versions for the upcoming release.

**Comment by pennyo** [comment]
Updated documentation is now available that includes a topic on  [how to check software versions](https://docs.microsoft.com/en-us/azure-sphere/deployment/check-software-versions)
