### ISSUE TITLE
azsphere device list (unsupported) command throws an incorrect exception message 

### ISSUE THREAD

**Issue by kkomand** [MicrosoftDocs/azure-sphere-issues#168]
The unsupported command below throws an exception to run "azsphere tenant migrate" which is not an available option. 

C:\Users\kkomand\Documents>azsphere show-version
19.09
Command completed successfully in 00:00:00.3327300.
C:\Users\kkomand\Documents>azsphere device list
error: Failed to retrieve devices.
Trace ID: b4582d61-03fe-4353-af15-a2f1ca3b7aeb
Received HTTP response: 410 (Gone)
-> Endpoint: GET https://prod.core.sphere.azure.net/v2/tenants/1476a609-fccc-46da-b195-bdbb4f467758/devices
-> Content: {"Code":2,"Message":"Your Azure Sphere SDK no longer supports this functionality. Please update your SDK to the latest and run azsphere tenant migrate. See https://aka.ms/migratespheretenant-customer-link for additional information."}
error: This Azure Sphere SDK is not compatible with the current Azure Sphere Security Service. Please update the SDK and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8b72a7-de1a-9d94-acc9-e1e3936ee587
* Version Independent ID: 21dae1e6-308a-4c55-dfe5-7f380dc86f47
* Content: [Azure Sphere CLI device (dev) command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device)
* Content Source: [AzureSphere/articles/reference/azsphere-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by MarileeTurscak-MSFT** [comment]
@kkomand 
Thanks for your feedback! Can you please provide the link to the document that you are following?

**Comment by asergaz** [comment]
Thanks for catching and reporting this @kkomand ! I am filing a new bug with Azure Sphere team so that we provide a better error message.

**Comment by asergaz** [comment]
Hi @kkomand ,
We received confirmation that this issue will be fixed on next release of the SDK. See also [this blog post](https://techcommunity.microsoft.com/t5/Internet-of-Things/Plan-for-changes-coming-to-the-Azure-Sphere-SDK-in-next-release/ba-p/916078) with the plan for changes coming to the Azure Sphere SDK in next release.

Thank you again for reporting the issue! :)

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
