### ISSUE TITLE
Each write transfer operation is limited to 4096 bytes is not an accurate description

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#169]
'write transfer' is not accurate here. As SPI is always fullduplex, if I want to read more than 4096 bytes in a transfer descriptor, I also get a -1 error. I think it is because I need write dummy data to generate clock for getting data back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f8b6aa-fcea-ac50-f15f-163db892896d
* Version Independent ID: 3a902c4e-1b7e-3601-e21e-558ec4f855a1
* Content: [SPIMaster_TransferSequential function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-spi/function-spimaster-transfersequential)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-spi/function-spimaster-transfersequential.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-spi/function-spimaster-transfersequential.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by MarileeTurscak-MSFT** [comment]
@xiongyu0523 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by asergaz** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by asergaz** [comment]
Related MSDN Thread fyi: https://social.msdn.microsoft.com/Forums/en-US/36430988-1aec-414f-a4e2-2d75541d9810/transfer-size-limiation-of-spimastertransfersequential-?forum=azuresphere

**Comment by pennyo** [comment]
Each call to **SPIMaster_TransferSequential** or **SPIMaster_WriteThenRead**is limited to at most 4096 bytes to read, and 4096 bytes to write, independent of the number of actual transfers. To transfer additional data, you need to call this function multiple times. Note that chip select will be asserted multiple times in this case.

The online documentation will be updated to include this information later this week.

Thank you for your patience.
