### ISSUE TITLE
azsphere command not recognized

### ISSUE THREAD

**Issue by dtbarn** [MicrosoftDocs/azure-sphere-issues#170]
In the Windows Azure SDK Environment Command Window, executing azsphere login returns the following:

'azsphere' is not recognized as an internal or external command, operable progrsm or batch file.

This is not addressed in the troubleshooting information.  Also, in another user response, someone described the same problem but not solution was provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Azure Sphere requires the user of the Azure Sphere Developer Command Prompt, not the Windows Azure SDK Environment Command Window.
We’ll add this to the Troubleshooting topic for the next release.

**Comment by dtbarn** [comment]
Thank you.  I don’t know how the wrong command window was selected.  When I search for ‘az’ now, the proper command window is available and the SDK window is not listed.

Dan

**Comment by pennyo** [comment]
Closing, as problem has been resolved.
