### ISSUE TITLE
Use Prod SKU and Group instead of Device Id

### ISSUE THREAD

**Issue by marcusmaker** [MicrosoftDocs/azure-sphere-issues#171]
Wouldn't it be more consistent to use Prod SKU and Group when linking feeds, instead of Device Id?

**Comment by MarileeTurscak-MSFT** [comment]
@marcusmaker thanks for your feedback! Please provide a link to the document you are following so that we can better assist.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @marcusmaker We use the link to pass your feedback to the right content author, it looks like your feedback is not for the doc but for the product itself if that is the case would you please open a feedback entry in the User Voice for Azure Sphere? https://feedback.azure.com/forums/915433-azure-sphere this process allows for your feedback to be upvoted by other customers and helps the team prioritize.

**Comment by Alberto-Vega-MSFT** [comment]
@marcusmaker Since we haven't heard back from you, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
