### ISSUE TITLE
Enterprise WiFi

### ISSUE THREAD

**Issue by pburke77** [MicrosoftDocs/azure-sphere-issues#172]
How do we connect to wifi using a user name and password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7768e3c0-7ead-9135-4558-938ce49f8dbb
* Version Independent ID: 825a32a0-865b-6562-3260-74b4619743b9
* Content: [Connect Azure Sphere to Wi-Fi](https://docs.microsoft.com/en-us/azure-sphere/network/wifi-including-ble)
* Content Source: [AzureSphere/articles/network/wifi-including-ble.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/wifi-including-ble.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by TravisCragg-MSFT** [comment]
@pburke77 Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by Alberto-Vega-MSFT** [comment]
@pburke77 This currently not supported please upvote this [User Voice entry](https://feedback.azure.com/forums/915433-azure-sphere/suggestions/36175345-support-for-enterprise-networks-http-s-and-wpa2-e) this will help the Sphere team prioritize.
