### ISSUE TITLE
UART no reading 0x00

### ISSUE THREAD

**Issue by judios** [MicrosoftDocs/azure-sphere-issues#173]
I am reading data from a device through the serial port.  I am using a Max3232 converter RS232 to TTL.  The odd thing here is that when I use the read function to retrieve the data received by the UART it eliminates all the 0x00 bytes. 
I have used the same converter to read data from the same device using both Arduino Mega and Raspberry PI 3 B+. With both I can read the 0x00 values.

**Reading with Arduino and Raspberry**
f7 00 00 15 10 22 00 02 28 02 00 00
f2 16 06 00 00 00 00 67 63 02 45 43

**Same readings with Azure Sphere**
f7 15 10 22 02 28 02 
f2 16 06 67 63 02 45 43

Am I missing some setting?

**Comment by ChiragMishra-MSFT** [comment]
@judios Thanks for the feedback. As this channel is made for feedback on azure docs, can you please help us with the doc that you are following ?

**Comment by Alberto-Vega-MSFT** [comment]
Hi @judios just to add to what Chirag said. We will need the link to the document you are following so we can pass the feedback to the content author. If this is not feedback for the docs. You might want to create a thread on StakOverflow, MSDN where there is a developer community that can help .

**Comment by Alberto-Vega-MSFT** [comment]
@judios We will be closing this issue for now. If you open a question on the forums please feel free to share it here and I can get you help if it doesn't get an answer there.
