### ISSUE TITLE
Is SPI slave mode possible for next version?

### ISSUE THREAD

**Issue by Lulixue** [MicrosoftDocs/azure-sphere-issues#174]
Now only SPI Master Mode supported, is there any plan for feature versions that make it possible for azure sphere board working as a spi slave ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9eb269-0b66-ffee-7ebf-1271d958b460
* Version Independent ID: b8f0641a-6c52-a96f-7e4e-977f3a80f7e0
* Content: [Azure Sphere Applibs spi.h reference](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-spi/spi-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-spi/spi-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-spi/spi-overview.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@Lulixue Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@Lulixue Yes, Currently Azure sphere only support [Serial Peripheral Interface (SPI)](https://docs.microsoft.com/en-us/azure-sphere/app-development/spi) in master mode. I haven't found information regarding the same. Kindly ask you to open a new feature request on azure sphere feedback forum [here](https://feedback.azure.com/forums/915433-azure-sphere?query=spi). As this is out of the scope of this doc.  We will close the issue and follow-up with you on the feedback forum. Please share the link when you do so.

**Comment by Lulixue** [comment]
https://feedback.azure.com/forums/915433-azure-sphere/suggestions/38958154-enable-spi-slave-mode
