### ISSUE TITLE
Command "azsphere device app stop --componentid <ComponentId>" is incorrect

### ISSUE THREAD

**Issue by Gilgamesh82** [MicrosoftDocs/azure-sphere-issues#175]
The command "azsphere device app stop --componentid <ComponentId>" is incorrect.

The command should be:
"azsphere device sl stop --componentid <ComponentId>"

"sl" instead of "app".

Also true for the command:
"azsphere device app start --debug --componentid <ComponentId>"

**Comment by YutongTie-MSFT** [comment]
@Gilgamesh82 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by pennyo** [comment]
The documentation accurately describes the contents of the 19.10 SDK, which was released yesterday. It is correct. If you haven't updated, please see [What's New](https://docs.microsoft.com/azure-sphere/product-overview/whats-new) to learn about new features and how to update  your installation.

**Comment by Gilgamesh82** [comment]
Ah!  OK Thanks!  I'll take a look!

**Comment by AshokPeddakotla-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
