### ISSUE TITLE
The command: "arm-poky-linux-musleabi-gdb HelloWorld_HighLevelApp.out" is incorrect.

### ISSUE THREAD

**Issue by Gilgamesh82** [MicrosoftDocs/azure-sphere-issues#176]
The command: "arm-poky-linux-musleabi-gdb HelloWorld_HighLevelApp.out" is incorrect.

You do not need to specify the app name ("HelloWorld_HighLevelApp.out" in this case).  Simply running arm-poky-linux-musleabi-gdb is sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0db551c-2484-3af9-ac08-d9978e82b445
* Version Independent ID: dea4dddf-46d1-cb41-2dcf-b77dece8c581
* Content: [Build, deploy, and debug a high-level application from the Windows command line](https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build#feedback)
* Content Source: [AzureSphere/articles/app-development/manual-build.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/manual-build.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@Gilgamesh82 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@Gilgamesh82 Are you able to set breakpoints if you start the debugger without the target?

**Comment by AshokPeddakotla-MSFT** [comment]
@Gilgamesh82 Have you had a chance to see the above response?

**Comment by Gilgamesh82** [comment]
IIRC yes.

**Comment by pennyo** [comment]
To enable full source code debugging, you need to pass the .out app binary from your build as a parameter to gdb.
