### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GiovanniFiorini** [MicrosoftDocs/azure-sphere-issues#177]
This CLI command doesn't exist:

azsphere device prep-sideload --enablertcoredebugging

Paragraph: https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-application#prepare-your-device-for-development-and-debugging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a9ebb5-700e-4490-11de-66a0b0fbf07a
* Version Independent ID: f6ab3c9c-906b-928a-a997-698e9738a11f
* Content: [Build a real-time capable application with Visual Studio quickstart- Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-application#prepare-your-device-for-development-and-debugging)
* Content Source: [AzureSphere/articles/install/qs-real-time-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-real-time-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@GiovanniFiorini Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@GiovanniFiorini Yes, you are correct. We are in the process of updating the documentation with the contents of the 19.10 SDK, which was released recently and changes will be available as earliest. Please see [What's New](https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new) to learn about new features and how to update your installation.

Please refer : https://github.com/MicrosoftDocs/azure-sphere-issues/issues/178 for more details.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
