### ISSUE TITLE
"azsphere device prep-sideload --enablertcoredebugging" is not a valid command line option

### ISSUE THREAD

**Issue by Gilgamesh82** [MicrosoftDocs/azure-sphere-issues#178]
With the 19.10 version of the SDK, I get this error when I run the command above:

'prep-sideload' is not a valid value for the 'Operation' command line option.
  Possible argument values include: 'app', 'capability', 'claim', 'enable-cloud-test', 'enable-development', 'image', 'list', 'list-attached', 'manufacturing-state', 'recover', 'restart', 'show', 'show-attached', 'show-count', 'show-deployment-status', 'show-os-version', 'sideload', 'update', 'wifi'.
Unrecognized command line argument '--enablertcoredebugging'.

I believe the correct command as per the --help text is:
azsphere device enable-development --enablertcoredebugging

However that command requires admin privileges.  Why would that require admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a9ebb5-700e-4490-11de-66a0b0fbf07a
* Version Independent ID: f6ab3c9c-906b-928a-a997-698e9738a11f
* Content: [Build a real-time capable application with Visual Studio quickstart- Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-application)
* Content Source: [AzureSphere/articles/install/qs-real-time-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-real-time-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@Gilgamesh82 Thanks for the feedback!  We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@Gilgamesh82 The documentation accurately describes the contents of the 19.10 SDK, which was released recently. Yes, you are correct. we are in the process of updating the documentation and changes will be available as earliest. Please see [What's New](https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new) to learn about new features and how to update your installation.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pennyo** [comment]
To expand on the answer: the --enablertcoredebugging option requires admin privileges because setting up for RT core debugging requires the installation of software that, in turn, needs admin privileges.
