### ISSUE TITLE
After move to 19.10, all projects are default cmake based. The picture showing linker setting for libcurl show be replaced by a change in cmake file

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#179]
better to review the whole document to see if similar improvement should be made

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f45a46-1962-0a73-0bdd-df377f382d38
* Version Independent ID: 80147160-89c5-3683-8c4e-557b38678acf
* Content: [Connect to web services - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/curl)
* Content Source: [AzureSphere/articles/app-development/curl.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/curl.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by YutongTie-MSFT** [comment]
@xiongyu0523 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by pennyo** [comment]
Thank you for your feedback! We'll fix this in upcoming release of the documentation.

**Comment by YutongTie-MSFT** [comment]
@pennyo 
Thanks a lot!

@xiongyu0523 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
