### ISSUE TITLE
Page need to be updated after 19.10

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#180]
As title explained. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6fff5c-8c9b-cdf9-5df3-4b211c91c0a9
* Version Independent ID: 9a2f0e11-0532-3194-423f-84e79f47dd07
* Content: [Azure Sphere CLI login command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-login)
* Content Source: [AzureSphere/articles/reference/azsphere-login.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-login.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Please check this and update the documentation.

**Comment by pennyo** [comment]
@xiongyu0523 Thanks for the feedback. We'll fix this in the next publication of the docs.

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 As Penny mentioned, this will be fixed in the next documentation updates. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
