### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gregsmi** [MicrosoftDocs/azure-sphere-issues#181]
"New features and changes in the 19.10 SDK release
The *19.09* release"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0ed2e36-f487-37a8-8cff-05022dc22770
* Version Independent ID: 4503a566-0ccf-063f-6855-0b22cc3bc5fe
* Content: [Release Notes 19.09](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1910#feedback)
* Content Source: [AzureSphere/articles/resources/release-notes-1910.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/release-notes-1910.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Good catch! Thanks for the feedback. We'll fix this the next time we publish the docs.

**Comment by AshokPeddakotla-MSFT** [comment]
@gregsmi As Penny Mentioned, We will fix this documentation in the next release. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
