### ISSUE TITLE
Consider adding another section talking about the "Azure Sphere Device Communication" Service

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#182]
Recently I've encountered a few Azure Sphere students who could not communicate with their Azure Sphere Dev kit.  In a few cases, simply restarting the Azure Sphere Device Communication service resolved the issue.  This would be a nice addition to this troubleshooting guide.

You kind of address this under the "Device does not respond" section.  This is a simple thing to try when the PC can't talk to the board.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Troubleshooting for Azure Sphere installation and setup on Windows](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@bawilless Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Please review this feedback. 
@bawilless We will incorporate the changes in the next release of docs if appropriate. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
