### ISSUE TITLE
PartnerGUID should be ComponentId to align with terminology

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#183]
When I first read this document, I do not know what is PartnerGUID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11552bd6-1719-603b-bc32-de16461da47f
* Version Independent ID: 1f6a56c4-ef01-2d47-57a2-e80cece5347a
* Content: [Sideload an application for testing - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/sideload-app)
* Content Source: [AzureSphere/articles/app-development/sideload-app.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/sideload-app.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
Assigning this to the author @pennyo to review this and update the documentation as appropriate.

**Comment by pennyo** [comment]
@xiongyu0523 Thank you for your feedback. We'll update this in the next version of the documentation.
