### ISSUE TITLE
sideload a production-signed application do not need 'appdevelopment capability'

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#184]
'To sideload an SDK-signed application, or to start, stop, debug, or delete an SDK-signed application or a production-signed application, the device must have the appdevelopment capability'

This description is confused, a production-signed application should be able to side to unclaimed device without appdevelopment capability. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8b72a7-de1a-9d94-acc9-e1e3936ee587
* Version Independent ID: 21dae1e6-308a-4c55-dfe5-7f380dc86f47
* Content: [Azure Sphere CLI device (dev) command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device)
* Content Source: [AzureSphere/articles/reference/azsphere-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding author @pennyo to confirm on this and update the doc as appropriate.

**Comment by pennyo** [comment]
@xiongyu0523 Thank you for the feedback. The azsphere-device information is intended for use by post-manufacturing customers; that is, it assumes that the device has been claimed. For information about loading software in a factory-floor setting with an unclaimed device, please see [Factory-floor tasks](https://docs.microsoft.com/azure-sphere/hardware/factory-floor-tasks).

**Comment by pennyo** [comment]
Closing this issue.
