### ISSUE TITLE
Add Remove Deployment Topic to this page

### ISSUE THREAD

**Issue by rickgregory1905** [MicrosoftDocs/azure-sphere-issues#186]
It would be helpful following the https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment#create-the-deployment topic to have a topic describe how to remove the imagepackage from the deployment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f06ff328-8ce0-ed53-ec16-77557571701c
* Version Independent ID: 6f534143-977d-a964-f170-ee07f0a3e083
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment#create-the-deployment)
* Content Source: [AzureSphere/articles/install/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@rickgregory1905 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@rickgregory1905  We'll update this in the next version of the documentation if appropriate. 
Adding author @pennyo for further review.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
