### ISSUE TITLE
References to Project Properties

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/azure-sphere-issues#187]
This page and a number of other pages still reference the project properties dialog which was removed in the transition to using CMake as the primary build engine.  This is extremely confusing for new starters and also misses a key piece of information: How to discover the currently available API versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f03e66-a9f8-b1ee-f565-5cf23cf06cae
* Version Independent ID: 4d29ef11-49b6-d29b-72c8-8e8cf73725ab
* Content: [Use beta features - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/use-beta#feedback)
* Content Source: [AzureSphere/articles/app-development/use-beta.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/use-beta.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@ld0614 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@ld0614 Thanks for the feedback. This will be fixed the next time we republish the docs.
