### ISSUE TITLE
cmake CMAKE_TOOLCHAIN_FILE incorrect, use AzureSphereRTCoreToolchain.cmake

### ISSUE THREAD

**Issue by maseman** [MicrosoftDocs/azure-sphere-issues#188]
-DCMAKE_TOOLCHAIN_FILE=<path to sdk>"CMakeFiles\AzureSphere**RTCore**Toolchain.cmake"

This seems to be required to pick up the ARM GNU tools specified in ARM_GNU_PATH in order to build the HelloWorld_RTApp_MT3620_BareMetal sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96ea0aa-11c0-c2cc-e936-eecd824bd89d
* Version Independent ID: d927434b-1b90-0f6b-0f98-ea59ea462bcb
* Content: [Build a real-time capable application on the Windows command line Quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-app-cli)
* Content Source: [AzureSphere/articles/install/qs-real-time-app-cli.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-real-time-app-cli.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@maseman Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@maseman Thank you for the feedback. This will be fixed in the next release of the documentation.

**Comment by pennyo** [comment]
Verified the fix on https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-app-cli and closing the issue.
