### ISSUE TITLE
openocd gdb listen port is defaulted to 4444 not 3333

### ISSUE THREAD

**Issue by maseman** [MicrosoftDocs/azure-sphere-issues#189]
Clarify example debug session to use port 4444. This is the default for the gdb connection as setup in the example NOT the usual 3333.

(Default appears to be set in C:\Program Files (x86)\Microsoft Azure Sphere SDK\Sysroots\3+Beta1909\tools\openocd\mt3620-rdb-ftdi.cfg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96ea0aa-11c0-c2cc-e936-eecd824bd89d
* Version Independent ID: d927434b-1b90-0f6b-0f98-ea59ea462bcb
* Content: [Build a real-time capable application on the Windows command line Quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-app-cli)
* Content Source: [AzureSphere/articles/install/qs-real-time-app-cli.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-real-time-app-cli.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@maseman Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
This is fixed in the current release of the documentation.
