### ISSUE TITLE
Cannot report floating-point value to DeviceTwin using AzureIoT_TwinReportState()

### ISSUE THREAD

**Issue by matsujirushi** [MicrosoftDocs/azure-sphere-issues#19]
in azure_iot_utilities.h:
```
void AzureIoT_TwinReportState(const char *propertyName, size_t propertyValue);
```

azure_iot_utilities.h is auto-generated.

**Comment by Mike-Ubezzi-MSFT** [comment]
@matsujirushi The auto-generated code, azure_iot_utilities.c/h, is sample code added to the app to show one way you can use the underlying Azure IoT SDK.  It doesn’t cover all scenarios.  Customers are encouraged to adapt this code for their purposes.  In this case, they could adapt the ‘ReportState’ function to handle floating point values in the underlying JSON twin document.  We might be able to provide further guidance if this still isn’t enough to unblock the customer.
If you require very specific examples, please let us know how we can assist you but, we did want emphasis that what you see is sample code, and not to be treated like an API itself. Regards, ~Mike
