### ISSUE TITLE
Preview install script fails as it tests Microsoft_Azure_Sphere_SDK.tar.gz NOT Azure_Sphere_SDK_Preview_Bundle.tar.gz

### ISSUE THREAD

**Issue by maseman** [MicrosoftDocs/azure-sphere-issues#190]
Curl download of sdk redirects SDK_TARBALL_URL to the "preview bundle".

	curl -L -O -J -v https://aka.ms/AzureSphereSDKDownload/Linux
	...
	Location: https://software-download.microsoft.com/download/pr/Azure_Sphere_SDK_Preview_Bundle.tar.gz

BUT the install script tests for "Microsoft_Azure_Sphere_SDK.tar.gz" (presumably the production name).

Temporary fix to make the preview install below.

diff --git a/install_azure_sphere_sdk.sh b/install_azure_sphere_sdk.sh
index bb311aa..990d0c5 100644
--- a/install_azure_sphere_sdk.sh
+++ b/install_azure_sphere_sdk.sh
@@ -272,7 +272,7 @@ get_sdk_tarball() {
     if [[ "$CURL_RESULT" != 0 ]]; then exit_with_error "Curl encountered an error downloading the Azure Sphere SDK. Please try again later or visit $SDK_INSTALL_DOC_URL for more information."; fi
 
     # Check we got the file we were expecting from the download
-    SDK_TARBALL="$TEMP_DIR/Microsoft_Azure_Sphere_SDK.tar.gz"
+    SDK_TARBALL="$TEMP_DIR/Azure_Sphere_SDK_Preview_Bundle.tar.gz"
     if [[ ! -f "$SDK_TARBALL" ]]; then exit_with_error "Error occurred downloading Azure Sphere SDK. Please try again later or visit $SDK_INSTALL_DOC_URL for more information." ; fi
   fi
 }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d74497-55b9-cf91-47a3-13126cd0e79f
* Version Independent ID: 3ecce7c5-23ab-ff8a-dc4c-35b3044f0d96
* Content: [Install the Azure Sphere SDK for Linux](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux)
* Content Source: [AzureSphere/articles/install/install-sdk-linux.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-sdk-linux.md)
* Product: **azure-sphere**
* GitHub Login: @sethmcevoy
* Microsoft Alias: **azurespheredocs**

**Comment by richardtaylorrt** [comment]
@maseman - thanks for raising this. We're fixing this as quickly as we can.  In the meantime, you should be able to install following [these instructions](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux#install-the-sdk-without-an-internet-connection) to manually download the bundle and point the installer script at it.

**Comment by Alberto-Vega-MSFT** [comment]
@maseman were you able to get unblock by following Richard's instructions?

**Comment by Alberto-Vega-MSFT** [comment]
@maseman We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
