### ISSUE TITLE
Getting the RF Tools package

### ISSUE THREAD

**Issue by danlevtonyukcoax** [MicrosoftDocs/azure-sphere-issues#192]
The documentation on this page (https://docs.microsoft.com/en-us/azure-sphere/hardware/rf-tools) says that the "RF Tools package" is available upon request.
Who do I reach out to to get access to that tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c02b89c-3777-fbec-1e37-8f33b4a3283c
* Version Independent ID: 5cd5717c-f46c-be69-8c2b-3f805b8c8e54
* Content: [Radio frequency (RF) test tools - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/rf-tools)
* Content Source: [AzureSphere/articles/hardware/rf-tools.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/rf-tools.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by MarileeTurscak-MSFT** [comment]
@danlevtonyukcoax 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Alberto-Vega-MSFT** [comment]
@danlevtonyukcoax Would you please email @ AZCommunity@microsoft.com with a link to this Doc/Issue

**Comment by AshokPeddakotla-MSFT** [comment]
Since we are discussing this offline, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
