### ISSUE TITLE
What will happen if "temporary" image escape from factory process

### ISSUE THREAD

**Issue by fanshaoshan** [MicrosoftDocs/azure-sphere-issues#194]
Will it expire automatically, erased automatically? What's the difference between regular factory preload image vs factory temporary image?

**Comment by AshokPeddakotla-MSFT** [comment]
@fanshaoshan Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
