### ISSUE TITLE
Typo under Wi-Fi antennas section

### ISSUE THREAD

**Issue by jlk** [MicrosoftDocs/azure-sphere-issues#195]
On the MT3620 development board user guide page - last sentence of 2nd paragraph under "Wi-Fi antennas" section 

> The images on the second row show the re-oriented capacitor positions in green.

There ain't no green in the [2nd image](https://docs.microsoft.com/en-us/azure-sphere/media/mt3620-c23repositioned.png). :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877d4170-58b8-f3a6-49f0-45b7f514b7e9
* Version Independent ID: 18c7d3f7-864d-da98-447c-5aac535c8a99
* Content: [MT3620 development board user guide - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-user-guide)
* Content Source: [AzureSphere/articles/hardware/mt3620-user-guide.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-user-guide.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by mike-urnun-msft** [comment]
@jlk Thank you for your feedback! We will review and update as appropriate.

**Comment by asergaz** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
Thank you for your feedback! We've fixed this in the docs that will be published later this week.
