### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by push7joshi** [MicrosoftDocs/azure-sphere-issues#196]
While trying to install the SDK on Raspbian:

`There was an error extracting the toolchain from '/opt/azurespheresdk/Sysroots/3/tools/exp23-appsdk-linux-blanca.sh'.`
Unsure if this is specific to the platform, working on raspberry pi 3B.
Could you provide me with some pointers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d74497-55b9-cf91-47a3-13126cd0e79f
* Version Independent ID: 3ecce7c5-23ab-ff8a-dc4c-35b3044f0d96
* Content: [Install the Azure Sphere SDK for Linux](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux)
* Content Source: [AzureSphere/articles/install/install-sdk-linux.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-sdk-linux.md)
* Product: **azure-sphere**
* GitHub Login: @sethmcevoy
* Microsoft Alias: **azurespheredocs**

**Comment by asergaz** [comment]
Hello @push7joshi , thank you for your feedback.

Please see the documentation [here](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux). As a prerequisite you will need "A computer running Ubuntu 18.04 LTS Edition. Only this edition is supported in the current release."

All Best

**Comment by push7joshi** [comment]
rookie mistake, my bad.
Thanks for your prompt response
