### ISSUE TITLE
Other header file in Azure Sphere Blank Template

### ISSUE THREAD

**Issue by caminsha** [MicrosoftDocs/azure-sphere-issues#197]
Hi

I wanted to create a new Azure Sphere project. For developing I'm using Visual Studio Enterprise 2019.

I created a new project based on the template "Azure Sphere MT3620 blank". During the development I wanted to use the Function `Storage_GetAbsolutePathInImagePackage`.

I got an error that the function is defined implicit which makes sense when looking into the file `storage.h`. In this header file there is no function declaration for this method.

Visual Studio Version: 16.4.2

Do you have an idea why I don't have the correct header file with all the function declarations?

Thanks,
caminsha
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45089e6-7e6e-ec62-010d-553d9d7a1666
* Version Independent ID: 5eb9998c-6272-cee5-721a-fe9f0271ea1f
* Content: [Azure Sphere Applibs storage.h reference](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-storage/storage-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-storage/storage-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-storage/storage-overview.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by caminsha** [comment]
I just found a link to a description about the API versions. For more informations about API versions, see  [here](https://docs.microsoft.com/en-us/azure-sphere/app-development/use-beta#specify-beta-apis-in-cmake-for-visual-studio).

In my opinion, it makes sense that the template projects are based on the stable APIs.

**Comment by AshokPeddakotla-MSFT** [comment]
@caminsha Glad to hear that you have found a resolution for your issue. 
Adding author @esalc to check this and update the doc as appropriate.
