### ISSUE TITLE
Missing space between "samples" and "provide"

### ISSUE THREAD

**Issue by msjsheridan** [MicrosoftDocs/azure-sphere-issues#198]
"The application development documentation and the Azure Sphere samplesprovide information about application design."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b25cf9-8383-e69a-777f-b67925ed4855
* Version Independent ID: 994e83e1-231a-9f71-ef5c-7fe9725d2a59
* Content: [Factory floor operations - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/factory-floor-tasks)
* Content Source: [AzureSphere/articles/hardware/factory-floor-tasks.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/factory-floor-tasks.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@msjsheridan Thank you very much for taking the time to report this minor detail. It is greatly appreciated. I will get this corrected now.

**Comment by Mike-Ubezzi-MSFT** [comment]
@pennyo I created a PR to address the following issue raised by @msjsheridan.

**Comment by pennyo** [comment]
Thans for your feedback. This has been fixed in the  current release of the docs.
