### ISSUE TITLE
Could not find the download link of the Visual Studio Tools Preview for Azure Sphere

### ISSUE THREAD

**Issue by weiqing-beijing** [MicrosoftDocs/azure-sphere-issues#20]
Hi there, has the download link been removed? I could not find any link of the VS Tools from this page.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97065dd-068c-6c33-310f-fd1c722cf04c
* Version Independent ID: 2301900c-0c6d-80b4-6fbd-9b0b18f9e640
* Content: [Azure Sphere installation and device setup quickstart](https://docs.microsoft.com/en-us/azure-sphere/quickstart/qs-install#install-the-visual-studio-tools-preview-for-azure-sphere)
* Content Source: [AzureSphere/articles/QuickStart/qs-install.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/QuickStart/qs-install.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by matsujirushi** [comment]
#15

**Comment by matsujirushi** [comment]
You can download 'Download the Azure Sphere SDK Preview for Visual Studio' link of [here](https://docs.microsoft.com/ja-jp/azure-sphere/quickstart/qs-install).
