### ISSUE TITLE
Mailboxes

### ISSUE THREAD

**Issue by clarkebowers** [MicrosoftDocs/azure-sphere-issues#200]
The diagram show the MediaTek Mailboxes as supported by the OS. I cannot find any OS call to use the mailboxes. I cannot find any documentation on the hardware implementation of the mailboxes. How can I utilize the mailboxes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32117582-c78b-3495-da7f-8427aff8e957
* Version Independent ID: 3e771f90-da18-51bb-cd56-455f4d828e69
* Content: [MT3620 Support Status - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status)
* Content Source: [AzureSphere/articles/hardware/mt3620-product-status.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-product-status.md)
* Product: **azure-sphere**
* GitHub Login: @v-phkane
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@clarkebowers Thank you for the feedback. The [MT3620 Block Diagram](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status#mt3620-block-diagram) states the following:

>The block diagram shows the MT3620. Features that are not yet supported are shown in white and features that are partially supported are shown with gradient shading.

![Screenshot (634)](https://user-images.githubusercontent.com/37126106/73014702-7e9d8b00-3dcf-11ea-8b80-7d1262253d45.png)

Are mailboxes supported, is there additional documentation?

**Comment by clarkebowers** [comment]
It show it as supported, but nothing is written about it on the page. So how would I use the mailboxes?

**Comment by Mike-Ubezzi-MSFT** [comment]
@clarkebowers I believe that lite grey shading indicates that it is supported by the OS only, which means any application logic has no access. I will confirm this.

**Comment by Mike-Ubezzi-MSFT** [comment]
@clarkebowers I have confirmed the following:

>Currently mailboxes are used for intercore communications by the OS. They’re not available to customer apps.

Please let me know if you have additional questions or would like me to clarify the information provided but, we will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by Mike-Ubezzi-MSFT** [comment]
@clarkebowers There is some additional discussion around this, and my previous response might not be entirely true. Please take a look at the following: [Communicate with a high-level application](https://docs.microsoft.com/en-us/azure-sphere/app-development/inter-app-communication) 

I am going to reopen this while I am in the process of receiving some additional information. Thank you!

**Comment by Mike-Ubezzi-MSFT** [comment]
@clarkebowers After some back and forth it has been confirmed that the Mailboxes are only accessible by the O/S as the documentation indicates. The link I have provided is the closest in functionality that is available.
