### ISSUE TITLE
azsphere CLI error for all tenant-related commands: "Failed to retrieve the user's Azure Sphere tenants."

### ISSUE THREAD

**Issue by Zoidborg7** [MicrosoftDocs/azure-sphere-issues#201]
I set up an Avnet Starter Kit just this month (January 2020) with the latest SDK and OS version 19.11. I was able to set up the dev kit, register, create a tenant, and claim the device with no troubles. I have been using the device in development/sideload mode and have not changed that.

It's been several days since I've had the device connected to my computer, but I haven't changed anything in that time. Now suddenly when I try to use any azsphere commands that need the tenants (including `login` and `dev show`, for example), I get the same error messsage:

```
error: Failed to retrieve the user's Azure Sphere tenants.
error: Trace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/AzureSphereSDKHelp/Cloud for troubleshooting suggestions and support.
```

I've just been using my Microsoft account for login. It's the same login I used to set everything up. And I'm even using the same computer that I used when setting it up only a week or two ago. I haven't been able to find anything online (including the suggested link and many searches) to help with this. I'm hoping it's just something random with my account, but it could also be something larger. Thanks.

**Comment by Zoidborg7** [comment]
Update: I had been working on this for an hour or more, and right after I completed this issue, I went to try some other things. I don't know if this action made any difference, but on the `azsphere login` dialog, I attempted to select my Work account (Office 365). It came back with an error message that the account doesn't exist in the Azure Sphere tenant (which I expected). Then, I selected my Microsoft account, the one I had been trying. For some reason, this time it was able to login successfully.

Not sure if the problem was transient, or if somehow trying to login with an invalid account first somehow caused it to work. But I figured I'd make a note of it here. Thanks.

**Comment by TravisCragg-MSFT** [comment]
@Zoidborg7 Thanks for the follow up. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
