### ISSUE TITLE
Azure Sphere SDK preview for Windows Documentation

### ISSUE THREAD

**Issue by kkomand** [MicrosoftDocs/azure-sphere-issues#202]
Team,

Please update the documentation (the install instructions page)  to clarify that if using Azure Sphere SDK preview for Windows  is for VSCode  as i have seen users downloading Azure Sphere SDK preview for Windows and trying it with Visual Studio which doesn't work  

Request to update the instructions in the document:

https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk

Best,
Kumar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3859174a-d1d6-d10e-5fbf-8d83f8e0f150
* Version Independent ID: 93000ca6-7a4d-11da-27d0-ba7430e83d6a
* Content: [Set up a dev kit and install the Azure Sphere SDK for Windows](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk)
* Content Source: [AzureSphere/articles/install/install-sdk.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-sdk.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@kkomand Thank you for making us aware of this, and suggesting a doc enhancement to be made. I am going to have the content owner review this and make an update as appropriate.

**Comment by Mike-Ubezzi-MSFT** [comment]
@kkomand In working with the content author on this topic, we feel there is sufficient detail covering the topic. If there is a specific detail you feel is missing or is not that clear, can you highlight the specific portion of the document. Thank you!

> The current section on [installing a Windows SDK](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk#install-an-azure-sphere-sdk-for-windows) includes the following text:

> Azure Sphere supports two SDKs for Windows:

>- Azure Sphere SDK Preview for Visual Studio supports development on Windows using the Visual Studio integrated development environment (IDE). Azure Sphere requires Visual Studio Enterprise, Professional, or Community 2019 version 16.04 or later, or 2017 version 15.9 or later.
>
- The Azure Sphere SDK Preview for Windows supports development on the Windows command line.

>You can use either SDK with VS Code. You cannot install both SDKs on the same PC.

> Later on the same page,  the [SDK for Windows](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk#azure-sphere-sdk-preview-for-windows) section states:

> The Azure Sphere SDK Preview for Windows enables you to develop Azure Sphere applications on the Windows command line or with Visual Studio Code. Do not install this SDK if you plan to use Visual Studio; the Azure Sphere SDK Preview for Visual Studio is the only SDK you need with Visual Studio.

**Comment by bawilless** [comment]
The documentation to successfully install and configure a visual studio code development environment is missing. A few of the steps are there, but try to follow the instructions and see if you can configure the system to build an Azure Sphere application.


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless Thank you for the detail feedback. Indeed, the SDK Preview for Windows document will get the bits installed but you will need a sperate doc, such as: [Quickstart: Build the Hello World application with Visual Studio Code](https://docs.microsoft.com/en-us/azure-sphere/install/qs-blink-vscode) to take steps after the SDK is installed.
Additionally, in the [Next Steps](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk#next-steps) section of the SDK install document, there are steps detailed to setup your PC where there is a section detailed for [Developing with VS Code](https://docs.microsoft.com/en-us/azure-sphere/install/development-environment-windows#develop-with-vs-code).
I realize you were responding on a mobile device, and perhaps you have gone through this all before but, if you haven't can you please take a peak when you have the capacity.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding @pennyo for further review

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
