### ISSUE TITLE
Small typo on this page

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#203]
In the blue box close to the bottom of the page . . . 

 . . . If this happens, contact the others in your organization whoa re working with Azure Sphere. 

Should be 

 . . . If this happens, contact the others in your organization who are working with Azure Sphere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a64c8c-5d46-40a3-5936-8efb68242ff6
* Version Independent ID: 358f12a7-a6b8-0350-9155-9108f4b374d1
* Content: [About migration - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/resources/rbac-device-migration#feedback)
* Content Source: [AzureSphere/articles/resources/rbac-device-migration.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/rbac-device-migration.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless Thank you for bringing this to our attention. I will have a PR created and approved to be published to the public facing copy of this document.

**Comment by Mike-Ubezzi-MSFT** [comment]
@pennyo Minor edit, as I don't seem to have access to this page to submit a PR.

**Comment by AshokPeddakotla-MSFT** [comment]
@bawilless Thanks for reporting this issue. PR has been created to address this. After peer review and merge the doc will be updated. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
