### ISSUE TITLE
Instructions for building without the hardware abstraction layer does not work

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#204]
I'm busy converting all my Visual Studio projects to use CMake.  Most of my Visual Studio projects originated before the Hardware Abstraction layer was implemented.  

I tried to follow the instructions above in the purple note stating how to build CMake projects without the hardware abstraction layer, but I get a fatal build error.  The AzureSphereToolchainBase.cmake file is looking for these hardware definitions and if they are not found the build fails with a fatal error.

This is the code in the AzureSphereToolchainBase.cmake file that executes:

# Check if the hardware definition file exists at the specified path

IF((NOT ("${AZURE_SPHERE_HW_DEFINITION}" STREQUAL "")) AND (NOT ("${AZURE_SPHERE_HW_DIRECTORY}" STREQUAL "")))
    SET(GENERIC_HW_MESSAGE_ERROR "The target hardware is not valid. To resolve this, you'll need to update the CMake build. The necessary steps vary depending on if you are building in Visual Studio, in Visual Studio Code or via the command line. See https://aka.ms/AzureSphereHardwareDefinitions for more details. ")
    IF(NOT EXISTS "${AZURE_SPHERE_HW_DIRECTORY}/${AZURE_SPHERE_HW_DEFINITION}")
       MESSAGE(FATAL_ERROR "${AZURE_SPHERE_HW_DIRECTORY}/${AZURE_SPHERE_HW_DEFINITION} does not exist. ${GENERIC_HW_MESSAGE_ERROR}")
    ELSEIF(EXISTS "${AZURE_SPHERE_HW_DIRECTORY}/${AZURE_SPHERE_HW_DEFINITION}" AND IS_DIRECTORY "${AZURE_SPHERE_HW_DIRECTORY}/${AZURE_SPHERE_HW_DEFINITION}")
        MESSAGE(FATAL_ERROR "${AZURE_SPHERE_HW_DIRECTORY}/${AZURE_SPHERE_HW_DEFINITION} is a directory, not a .json file.  ${GENERIC_HW_MESSAGE_ERROR}")
    ENDIF()
ENDIF()

As the 20.01 SDK rolls out and Visual Studio projects are no longer supported this will be an issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fe303-324f-149e-d664-95b3f335bbb0
* Version Independent ID: 98bfc861-2906-8225-455c-573035403312
* Content: [Target hardware dependencies](https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies)
* Content Source: [AzureSphere/articles/app-development/manage-hardware-dependencies.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/manage-hardware-dependencies.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless Thank you for making us aware of this issue. I will investigate this issue and get you a response from the product group. Thank you for taking the time to create this issue and providing the level of detail.

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless I did wan to follow up to this to detail the following information for hardware profile information. Did these steps not work?

Set the Target Hardware Definition Directory and the Target Hardware Definition for your hardware.

The Target Hardware Definition Directory identifies the folder that contains the hardware definition files for the target hardware. This path is relative to the workspace of the project. The Target Hardware Definition identifies the JSON file in the Target Hardware Definition Directory that defines the mappings from the sample application code to the target hardware.

If you're using Visual Studio, edit the AzureSphereTargetHardwareDefinitionDirectory and AzureSphereTargetHardwareDefinition fields in the CMakeSettings.json file. For example:


Copy
 ```json
 "AzureSphereTargetHardwareDefinitionDirectory": "<path to cloned samples\Hardware\mt3620_rdb",
 "AzureSphereTargetHardwareDefinition": "mt3620_rdb.json"
 ```
If you're using VS Code, edit the AZURE_SPHERE_TARGET_HARDWARE_DEFINITION_DIRECTORY and AZURE_SPHERE_TARGET_HARDWARE_DEFINITION values in the .vscode/settings.json file:


Copy
  ```json
  "AZURE_SPHERE_TARGET_HARDWARE_DEFINITION_DIRECTORY": "<path to cloned samples\Hardware\mt3620_rdb",
 "AZURE_SPHERE_TARGET_HARDWARE_DEFINITION": "mt3620_rdb.json",
 ```
If you're building on the command line for either Windows or Linux, include the parameters shown in the following example. The path to the target directory is relative to the location of the CMakeLists.txt file.


Copy
 ```console 
 -DAZURE_SPHERE_TARGET_HARDWARE_DEFINITION_DIRECTORY="<path to cloned samples>\azure-sphere-samples\Hardware\mt3620_rdb"
 -DAZURE_SPHERE_TARGET_HARDWARE_DEFINITION="mt3620_rdb.json"
 ```

**Comment by bawilless** [comment]
I wanted to do a CMake build without using the hardware abstraction layer. There are instructions on how to accomplish that, but it does not work.

Brian


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by Mike-Ubezzi-MSFT** [comment]
@pennyo I created a Azure Sphere support escalation ([115630](https://dev.azure.com/msresearch/4x4/_workitems/edit/115630)) to inquire about this issue. I have made this a doc-enhancement but there is a product-question component to this; is the customer's approach currently supported and is this documented? Thank you!

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless The documentation has been updated. Can you please review and provide feedback that the updates address the issue. Thank you.

**Comment by bawilless** [comment]
I’ve confirmed that I can build and run a CMake application without the hardware abstraction layer.  Thank you!

**Comment by Mike-Ubezzi-MSFT** [comment]
Cool! We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
