### ISSUE TITLE
Fix Command for OS Feed Type is RetailEval in the instructions

### ISSUE THREAD

**Issue by kkomand** [MicrosoftDocs/azure-sphere-issues#205]
G'day Team,
I think you need to update this last intruction on the page.  OSFeed for retail evaluation should be "RetailEval".  If I try this command with Retail option for evalaution it doesn't work.  When  i changed it to "RetailEval" , was able to update the OS to 20.01

If the OS Feed Type is RetailEval, change it to Retail:
azsphere device-group update --productname <product> --devicegroupname "Development" --osfeed "Retail"

Best,
Kumar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f06ff328-8ce0-ed53-ec16-77557571701c
* Version Independent ID: 6f534143-977d-a964-f170-ee07f0a3e083
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment)
* Content Source: [AzureSphere/articles/install/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
@kkomand Thank you for your feedback. 

As described in [Important News about Retail Evaluation](https://docs.microsoft.com/azure-sphere/product-overview/retail-evaluation-2001), we recommend that customers create  a device group specifically for Retail Evaluation and maintain their development devices on the Retail OS feed. We believe that this approach will lead to the best customer experience.

**Comment by kkomand** [comment]
G'day Team,

(1) When I tried the command with the Flag "Retail" as in the document for evaluation. It did not update the device to 20.01. Only when I tried the command with "RetailEval" flag it updated the device to 20.01.  Please review the command
azsphere device-group update --productname --devicegroupname "Development" --osfeed "Retail"

(2) The instructions are slightly convoluted and would request a sequenced instructions for the scenarios below:
  
   (a) Procedure to update a device to Retail Evaluation version  for those who are using 19.11 OS 
       version  &  corresponding known issues/fixes.

   (b) Procedure to update a device to Retail Evaluation version for those who are running Out-of-the box OS such as 18.x.  (Ex: New kits). The newer commands (such as azsphere enable cloud-test) doesn't work with 18.x OS versions. So if you can provide instructions on how to update a device that's on older version to  20.01 , that would ease the process .

Best,
Kumar

**Comment by pennyo** [comment]
@kkomand Were you unable to deploy an app to the device with 19.11 OS/SDK?
