### ISSUE TITLE
Device does not respond for the first time setup

### ISSUE THREAD

**Issue by sunillnaik** [MicrosoftDocs/azure-sphere-issues#206]
I have received the Azure Sphere MT3620 Dev Kit 
![maxresdefsphere](https://user-images.githubusercontent.com/44568355/74307538-f9dbd680-4da8-11ea-8bbc-f75bcce96d0d.jpg)

Newly updated windows and Visual Studio 2019. gives me below error, 

`C:\Windows\system32>azsphere device show-os-version
error: The device is not responding. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes.

C:\Windows\system32>azsphere show-version
20.01.eval`

I tried all the instruction on troubleshoot page of Microsoft, still same error on both kit.
Is this SDK not supported on the kit?

**Comment by Adam-Smith-MSFT** [comment]
@sunillnaik Please post this thread in either MSDN forums, or stackOVerflow, since this medium is only reserved to documentation. 
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
