### ISSUE TITLE
QS for AS: multiple style guide violations

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/azure-sphere-issues#207]
Needs MS style guide edit. I'll do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12650c79-5696-6c6c-b1f6-f26f3d8a2f81
* Version Independent ID: f5dd3da4-3e30-f29d-b9a2-0951fef1a005
* Content: [Quickstarts for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-overview?source=docs)
* Content Source: [AzureSphere/articles/install/qs-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@Rick-Anderson Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Could you please check this issue and update?

**Comment by pennyo** [comment]
@Rick-Anderson thanks for the feedback. Since we've discussed offline, I'll close the issue.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson thanks for the feedback. Since we've discussed offline, I'll close the issue.

@pennyo The document doesn't conform to the Microsoft style guide. That's not how open source generally works. When my PR #153 merges to address the style guide problems, that closes the issue.
