### ISSUE TITLE
Event bit mask undocuments

### ISSUE THREAD

**Issue by clarkebowers** [MicrosoftDocs/azure-sphere-issues#208]
The enumeration EventLoop_IoEvents is not documented. How do I use EventLoop_Input = 0x01? I want an event ever time a GPIO input line goes from low to high. How do I register this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b9d7077-1cb0-da2c-8f9a-4c81e6f51b07
* Version Independent ID: e65bb220-daa5-dfbb-2d48-04b4f7d087be
* Content: [EventLoop_RegisterIo function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-eventloop/function-eventloop-registerio)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-eventloop/function-eventloop-registerio.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-eventloop/function-eventloop-registerio.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@clarkebowers Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@clarkebowers Here is the documentation for [EventLoop_IoEvents](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-eventloop/enum-eventloop-ioevents). Please check and let us know if that helps.

**Comment by clarkebowers** [comment]
The text "The descriptor is available for read operations." is not helpful. The referenced sample does not use the EventLoop_RegisterIo function, so it is no help.

**Comment by AshokPeddakotla-MSFT** [comment]
@clarkebowers  I have assigned the issue to the content author @esalc  to evaluate and update the doc with samples as appropriate.

**Comment by pennyo** [comment]
@clarkebowers Thank you for your feedback. The EventLoop API supports only file descriptor events. Support for interrupts on the GPIO file descriptors is not currently available. 

If this feature is critical to your scenarios, please submit [product feedback or new feature requests](https://feedback.azure.com/forums/915433-azure-sphere).

**Comment by AshokPeddakotla-MSFT** [comment]
@clarkebowers I hope that answers your question. Please create a feedback entry in the user voice and provide your feedback. 

All the feedback you share in these forums will be monitored and reviewed by the Microsoft engineering teams responsible for building Azure.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
