### ISSUE TITLE
Maximum period_nsec value

### ISSUE THREAD

**Issue by clarkebowers** [MicrosoftDocs/azure-sphere-issues#209]
The maximum value for the period is 30000000ns. Greater than this value will result in EINVAL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d2af37-84d3-c7c2-87e1-9cb3915e9dbb
* Version Independent ID: 394be125-8bbf-101d-618a-c2bcbee6987c
* Content: [PwmState struct - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-pwm/struct-pwmstate#period_nsec)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-pwm/struct-pwmstate.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-pwm/struct-pwmstate.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@clarkebowers Thank you for bringing this to our attention. I will have the content team evaluate this and update the document as appropriate.

**[period_nsec](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-pwm/struct-pwmstate#period_nsec)**
The length of each period, in nanoseconds. This includes the total length of both the high and low states.

**Comment by pennyo** [comment]
@clarkebowers The period is hardware-dependent. This information has been updated in the documentation.
