### ISSUE TITLE
unique GUID for application.

### ISSUE THREAD

**Issue by Expecho** [MicrosoftDocs/azure-sphere-issues#212]
At the start of this document there is this note *"Each component in a deployment must have a unique GUID."*. What GUID are we talking about? Is it the ComponentId in the app_manifest.json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beac72a-149e-49d6-a9ce-13ae89ed3cd5
* Version Independent ID: 8cf3bf3d-8b58-5956-3d57-42fe9ceb6620
* Content: [Create a deployment - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/create-a-deployment)
* Content Source: [AzureSphere/articles/deployment/create-a-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/create-a-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by MarileeTurscak-MSFT** [comment]
@Expecho 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@Expecho  GUID means device group id. As specified in the doc, The --devicegroupid parameter supplies a GUID, which uniquely identifies the device group across all products." 
It would be great if you can elaborate more on "**ComponentId in the app_manifest.json**"

**Comment by AshokPeddakotla-MSFT** [comment]
@Expecho Answer is Yes. Your understanding is correct. It is the ID of the component in the application manifest file. It uniquely identifies the application itself.  Each type you rebuild, you get a new image ID, but the component ID remains the same. Please see [Contents of the application manifest](https://docs.microsoft.com/en-us/azure-sphere/app-development/app-manifest#contents-of-the-application-manifest) for more context.
Hope that answers your query. Do let us know if you have further questions.

**Comment by Expecho** [comment]
Great, thanks for the info!
