### ISSUE TITLE
Connection issues the Azure Sphere MT3620 starter kit

### ISSUE THREAD

**Issue by millena7** [MicrosoftDocs/azure-sphere-issues#213]
(1)	I have recently received the MT3620 to test, but I’m with some problems when I execute this command: 
 
**azsphere tenant create --name <name>**
Error: The device is not responding. The device may be unreponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes.
Error: Failed to retrieve device ID from attached device: 'Could not connect to the device; please ensure it is attached.'

(2)	Follow the items that I have already checked:

-	Change the USB port that the hardware is connect.
-	Uninstall and reinstall the SDK.
-	Check if I have only one TAP windows adapter and confirm that the IP Addres is 192.168.35.1:
-	Restart the Azure Sphere Device Communication Service
-	Restart my computer
-	Check the 3 Ports COM

![ports](https://user-images.githubusercontent.com/62349034/76986390-5c803f00-6920-11ea-830e-b8ccc692b89f.png)

(3)	It was not possible to execute the following steps, because I did'nt find the folder **APPDATA**:

Save a copy of this file: c:\windows\serviceprofiles\localservice\appdata\local\Azure Sphere Tools\restore.json
Delete this file
Run the Services Manager (services.msc).
Restart the "Azure Sphere Device Communications Service"

(4)	Follow attached the hardware photo
![IMG_20200318_133207363](https://user-images.githubusercontent.com/62349034/76985786-85ec9b00-691f-11ea-99ac-6c3f22e88318.jpg)
![IMG_20200318_133201201](https://user-images.githubusercontent.com/62349034/76985796-8ab14f00-691f-11ea-8910-965f9b19426e.jpg)
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32117582-c78b-3495-da7f-8427aff8e957
* Version Independent ID: 3e771f90-da18-51bb-cd56-455f4d828e69
* Content: [MT3620 Support Status - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status)
* Content Source: [AzureSphere/articles/hardware/mt3620-product-status.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-product-status.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by femsulu** [comment]
@millena7, happy to help. Mind sharing the related Azure documentation so we are investigate further?

**Comment by millena7** [comment]
> @millena7, happy to help. Mind sharing a link to the related Azure documentation so we can investigate further?

Thank you for helping.
Follow the documentation about this hardware:
https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status

**Comment by millena7** [comment]
Hi,
I deleted the file restore.json as recommended by Microsoft. It was in a hidden folder.
But the error still the same.

**Comment by aywolman** [comment]
test

**Comment by aywolman** [comment]
test

**Comment by asergaz** [comment]
Hello @millena7 you mentioned that you are following what's described [on this doc](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status) though I need to be sure that you followed all the steps as described here: [Overview of set-up procedures](https://docs.microsoft.com/en-us/azure-sphere/install/overview) ?

This is you installed the proper software , set up the development environment, claimed the device and just then tried to create a new tenant?

Thanks!

**Comment by millena7** [comment]
> Hello @millena7 you mentioned that you are following what's described [on this doc](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-product-status) though I need to be sure that you followed all the steps as described here: [Overview of set-up procedures](https://docs.microsoft.com/en-us/azure-sphere/install/overview) ?
> 
> This is you installed the proper software , set up the development environment, claimed the device and just then tried to create a new tenant?
> 
> Thanks!

Hi! 

I installed Azure SDK (Visual Studio) for Windows, set up the development environment but before claim the device, it is necessary to create a new tenant. See at picture below:
![Claim](https://user-images.githubusercontent.com/62349034/77368791-c4c58b00-6d3b-11ea-8a71-b0ab32c47713.JPG)

So that, it was not possible to claim.

**Comment by asergaz** [comment]
Thanks for the details @millena7 ,
Can you [check the related thread on MSDN](https://social.msdn.microsoft.com/Forums/en-US/a7ca80ba-8119-4cc8-89ef-d142421c84b5/azure-sphere-device-is-not-responding?forum=azuresphere) and try the following:

1. If you are connected to a VPN, disconnect from the VPN and try again

2. Verify that the com ports all have the correct driver (troubleshooting guide should have covered that)

3. Verify that the "Azure Sphere Device Communication Service" service is running.  Try to restart it. 

4. What do you get when doing "azsphere device show-attached -v" ?

5. Please also confirm that you are using SDK version 20.01

Thanks

**Comment by millena7** [comment]
António, thank you for helping.

**1. If you are connected to a VPN, disconnect from the VPN and try again**

I already did this test.

**2. Verify that the com ports all have the correct driver (troubleshooting guide should have covered that)**

![image](https://user-images.githubusercontent.com/62349034/77419593-751ca900-6da7-11ea-9914-ed8daa3cb898.png)

**3. Verify that the "Azure Sphere Device Communication Service" service is running. Try to restart it.**
The service is running and I already tried to restart it.

**4. What do you get when doing "azsphere device show-attached -v" ?**

![image](https://user-images.githubusercontent.com/62349034/77419716-9c737600-6da7-11ea-9d1c-68ea511e13ec.png)

**5. Please also confirm that you are using SDK version 20.01**

The version is 20.1.7.495.

![image](https://user-images.githubusercontent.com/62349034/77420102-3affd700-6da8-11ea-9030-e99e0998d491.png)

**Comment by asergaz** [comment]
Thanks for the details @millena7 , can you also try the command **"azsphere device recover -v"** ?

If you continue to see the issue after trying to recover please run "azsphere get-support-data --output logs.zip" and send the logs to me on email.

Thanks!

**Comment by millena7** [comment]
Hi!!

Good news! 

![image](https://user-images.githubusercontent.com/62349034/77458532-183be580-6ddd-11ea-9da4-fd4de0890bf5.png)

Thank you!! It's working :)

**Comment by asergaz** [comment]
Glad that you are up and running now :). Please reach out if other help is needed. Happy coding!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
