### ISSUE TITLE
How to get the id of a stored network?

### ISSUE THREAD

**Issue by rickeycv** [MicrosoftDocs/azure-sphere-issues#214]
Hi,
Is there a way to get the id of a stored network?
I cannot find the id in the WifiConfig_StoredNetwork struct.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501c500d-3afe-6ebd-8968-3e6faf355bcf
* Version Independent ID: 90fea6d5-13ba-c1a1-96df-fe82ce8e665a
* Content: [WifiConfig_ForgetNetworkById function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-forgetnetworkbyid)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-forgetnetworkbyid.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-forgetnetworkbyid.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@rickeycv Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@rickeycv  As specified in the doc [WifiConfig_GetStoredNetworks](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-getstorednetworks), before  you call WifiConfig_GetStoredNetworks, you must call WifiConfig_GetStoredNetworkCount and use the result as the array size for the WifiConfig_StoredNetwork array that is passed in as the storedNetworkArray parameter.

You can also get the SSID of the network by using the below commands. 
Type **azsphere device wifi** for a complete list, or **azsphere device wifi** option --help for help on an individual option. 

Do let us now if that helps.

**Comment by rickeycv** [comment]
Thanks, but I want to get the same id that I can see in the Sphere cli when I call **azsphere device wifi list** command which shows the following: id, SSID, Configuration state, Connection state, Security state, Targeted scan. On the other hand, when I call the [WifiConfig_GetStoredNetworks](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-getstorednetworks) API function, the id parameter is not part of the [WifiConfig_StoredNetwork](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/struct-wificonfig-storednetwork) structure and I need it to forget a network using 
the [WifiConfig_ForgetNetworkById](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-forgetnetworkbyid) API function.
Is there a way to get the id (not the SSID) of a network using the API?

Regards.

**Comment by AshokPeddakotla-MSFT** [comment]
@rickeycv Let me check this internally and update you as earliest. Appreciate your time and patience.

**Comment by AshokPeddakotla-MSFT** [comment]
@rickeycv Please see the below suggestions and let us know if you have further queries.

1. WifiConfig_GetConnectedNetworkId can get your the currently connected network  and then call WifiConfig_GetCurrentNetwork for more data about that network
 a.This only get the connected network

2. Use WifiConfig_SetConfigName  to set the network name and use WifiConfig_GetNetworkIdByConfigName  to get ID
 a.This only works if you set the friendly name

**Comment by rickeycv** [comment]
@AshokPeddakotla-MSFT 
I cannot find the WifiConfig_GetConnectedNetworkId function you mentioned.
Regarding point 2, WifiConfig_SetConfigNam and WifiConfig_GetNetworkIdByConfigName functions work, but the name's length is limited to 15 characters and there are a lot of WiFi networks with the same SSID with small changes in their last characters (more than 15 characters). Another issue found is that you cannot get ids by using WifiConfig_GetNetworkIdByConfigName function of the networks you add using the Azure CLI.

**Comment by maskimthedog** [comment]
The only other option is to store a table of network ids and ssid yourself in mutable storage and look up that way.

**Comment by pennyo** [comment]
@rickeycv I think this question is answered in [WifiConfig_GetConnectedNetworkId](https://docs.microsoft.com/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-getconnectednetworkid) in the current documentation.
