### ISSUE TITLE
Typo in the example configuration settings

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/azure-sphere-issues#216]
cmake.cmakePath has a mal-formed string: \\CMake\CMake\\.  There needs to be an extra '\' between the two CMake directories.  Otherwise VSCode complains about "Invalid escape character in string.  jsonc(261)".

Generally, all of the path separators need to be escaped on this page, as settings like
"cmake.cmakePath": "&lt;Path to VS Installation&gt;\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
won't work without more '\' characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8b84a97-17b0-f673-f8ca-c0376e0f66a1
* Version Independent ID: f74cbfdf-cb6e-0d91-f9ad-d5149a46cced
* Content: [Set up for development on Windows - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/development-environment-windows#feedback)
* Content Source: [AzureSphere/articles/install/development-environment-windows.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/development-environment-windows.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you shortly. Thanks for your patience.

**Comment by asergaz** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@BarryBo We fixed this in last week's update: https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/development-environment-windows.md

Closing.
