### ISSUE TITLE
Steps order

### ISSUE THREAD

**Issue by ihorbond** [MicrosoftDocs/azure-sphere-issues#217]
In my case I had to claim device first (step 6) and only then was I able to enable development mode on it otherwise would get an error saying the tenant had no devices assigned

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by femsulu** [comment]
Thanks for your comment. The feedback has been shared with the content owner for further review. Thanks for your patience.

**Comment by andremuz** [comment]
femsulu is right. I stumbled on the same issue.

**Comment by pennyo** [comment]
Thank you for the feedback This has been fixed and will appear in the next regular weekly update.
