### ISSUE TITLE
EACCESS also is returned if the real-time capable app isn't present

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/azure-sphere-issues#218]
This can happen if you forget to update launch.vs.json's partnerComponents.  Otherwise, VS will delete the real-time capable app when deploying the high-level app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae555d0-3bbf-68e0-4848-6b86f45d8de5
* Version Independent ID: f0fe5c0c-89f1-e46c-783b-19966ca53454
* Content: [Application_Socket function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-application/function-application-socket)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-application/function-application-socket.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-application/function-application-socket.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@BarryBo Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding author @esalc to check this feedback and update the doc as appropriate.

**Comment by LouisBerner** [comment]
Updated the topic. Revised content will be published in an upcoming doc refresh.

Thank you for your contribution!
