### ISSUE TITLE
Clarification on application memory usage

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#219]
In the "Debug.MIDebugExec info proc status" example on this page the dump is showing the Virtual Memory used by the application.  These numbers are much larger than the documented 256KB application memory usage  limit.  Is this dump also capturing memory usage from the GDB debugger?  Is there a way to see how much RAM just the application is consuming?

Is there any documentation on the Virtual Memory and it's maximum usable size?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c1eef5-ba8d-43f9-7547-1b9b5f71760e
* Version Independent ID: 1323ac90-3ba4-d47b-1c42-238cb0029b63
* Content: [Memory use in high-level applications - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/application-memory-usage)
* Content Source: [AzureSphere/articles/app-development/application-memory-usage.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/application-memory-usage.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by BharathNimmala-MSFT** [comment]
@bawilless Thank you for your query, our team will further look into it and get back to you at the earliest.

**Comment by asergaz** [comment]
Thanks for the feedback @bawilless . I am assigning this issue to @pennyo to comment on your current questions and enhance the doc as needed.

**Comment by pennyo** [comment]
We've added support for memory visualization in Visual Studio for the 20.10 release. Please see
[Application memory use](https://docs.microsoft.com/en-us/azure-sphere/app-development/application-memory-usage) for details.
