### ISSUE TITLE
AzureSphere first impressions

### ISSUE THREAD

**Issue by JolleyLama** [MicrosoftDocs/azure-sphere-issues#22]
I just got my MT3620 kit yesterday. Thank you very much for your effort in this community. It is going to have very limited adoption in the community since it requires a PC running Windows 10. Most people in the IoT/SBC community use Linux or Mac. The expectation is that IoT IDEs will support Windows/Mac/Linux. I think that requiring the full version of Visual Studio 17 and Windows 10 is going to kill this device before it ever starts. PLEASE enable support for this device in VS Code, which would provide coverage for all platforms.

The device seems nice. I like the plastic pads to give it something to stand on. PLEASE provide a 3D model for a case so the community can 3D print a case.

Thanks again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8218af32-d2bc-7635-e0b6-039a65df7673
* Version Independent ID: 23b08056-f351-fe3e-ef2d-f2f47d509ad8
* Content: [Quickstarts for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstart/qs-overview)
* Content Source: [AzureSphere/articles/QuickStart/qs-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/QuickStart/qs-overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by robotdad** [comment]
Thank you for the feedback. VS Code support for Linux and Mac is on our roadmap, but we don’t have a timeframe for that to share yet. You can open a feature request for the Azure Sphere team to enable Linux and Mac OS support [here](https://feedback.azure.com/forums/915433-azure-sphere).

We’re looking around to see if we have any 3D models for a case we can share. If we do we’ll post them to our [samples repository](https://github.com/azure/azure-sphere-samples). You may find [Seeed’s mechanical drawings](https://github.com/SeeedDocument/Azure_Sphere_MT3620_Development_Kit/tree/master/mechanical) useful for designing a case yourself.

**Comment by JolleyLama** [comment]
Marc,

Thank you very much for your reply. Good to know it’s being read. I’ll put in a feature request. 

---Jeff

**Comment by sergaz-msft** [comment]
@JolleyLama we will proceed and close this case now. If you have opened a feature request please share the link here so others can vote :). Thank you!

**Comment by joostd** [comment]
> VS Code support for Linux and Mac is on our roadmap, but we don’t have a timeframe for that to share yet

Is that roadmap public or is there an ETA yet? I have the same problem: acquired an  MT3620 Kit but no idea how to use it from my MacOS or Linux systems. I don’t have any windows 10 systems unfortunately.

**Comment by hosek** [comment]
Im also interested in VS Code support, haven't seen such platform locked IoT device (Azure Sphere MT3620) for a quite long time.

**Comment by sergaz-msft** [comment]
Hello. We will update the status of the feature requests soon on user voice soon. Thank you so much for bringing this up!

- https://feedback.azure.com/forums/915433-azure-sphere/suggestions/35567668-add-mac-vs-code-support
- https://feedback.azure.com/forums/915433-azure-sphere/suggestions/35968183-support-linux-distros
