### ISSUE TITLE
Memory Usage Command [Visual Studio Code] [Ubuntu]

### ISSUE THREAD

**Issue by mehrdadh** [MicrosoftDocs/azure-sphere-issues#220]
How can I run the same command in Visual Studio Code in Ubuntu to get the memory usage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c1eef5-ba8d-43f9-7547-1b9b5f71760e
* Version Independent ID: 1323ac90-3ba4-d47b-1c42-238cb0029b63
* Content: [Memory use in high-level applications - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/application-memory-usage#feedback)
* Content Source: [AzureSphere/articles/app-development/application-memory-usage.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/application-memory-usage.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe I haven't found the steps for VS Code. I am assigning this issue to the author @pennyo to comment on your current question and enhance the doc as needed.

**Comment by mehrdadhe** [comment]
@AshokPeddakotla-MSFT Thanks for the follow up.
@pennyo appreciate your help.

**Comment by pennyo** [comment]
@mehrdadhe Great question! And definitely something we should document. We're looking into it.

**Comment by mehrdadhe** [comment]
Is there any update on this?
Basically I'm looking for a way to get memory usage while debugging in VS Code on ubuntu.

**Comment by pennyo** [comment]
@mehrdadhe We're still investigating. When we find an answer we'll update this issue and the documentation.

**Comment by pennyo** [comment]
We don't have a solution for getting memory usage on Ubuntu at present. 

Closing the issue.
