### ISSUE TITLE
Memory Jump Segmentation Fault [SIGSEGV]

### ISSUE THREAD

**Issue by mehrdadhe** [MicrosoftDocs/azure-sphere-issues#221]
I tried to do something like this on Azure Sphere and it failed with segmentation fault error:
**Program received signal SIGSEGV, Segmentation fault.**
Is memory jump blocked on Azure Sphere OS?

```bash
int compute_foo(int x) __attribute__((section (".data")));
int compute_foo(int x){
  return x + 2;
}

int main(int argc, char **argv) {
  Log_Debug("foo: %d\n", compute_foo(2));
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c1eef5-ba8d-43f9-7547-1b9b5f71760e
* Version Independent ID: 1323ac90-3ba4-d47b-1c42-238cb0029b63
* Content: [Memory use in high-level applications - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/application-memory-usage#feedback)
* Content Source: [AzureSphere/articles/app-development/application-memory-usage.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/application-memory-usage.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Unable to find this info on the docs [Memory use in high-level applications](https://docs.microsoft.com/en-us/azure-sphere/app-development/memory-latency). Do you have any other suggestions for the customer query? **Is memory jump blocked on Azure Sphere OS?**

**Comment by pennyo** [comment]
@mehrdadhe  The cause of the problem is that you're trying to execute code from the .data section. The .data section, however, is mapped readable/writable but not executable.  As a result, any attempt to jump into the .data section will result in a segfault.  This is a security precaution designed to prevent execution of malicious code delivered as data payloads.

**Comment by mehrdadhe** [comment]
@pennyo Thanks for clarifying.
