### ISSUE TITLE
Cannot Telnet to port 2342 to see Debug Output on sideload

### ISSUE THREAD

**Issue by maskimthedog** [MicrosoftDocs/azure-sphere-issues#222]
We are trying to follow these instructions to see debug output on 192.168.35.2 port 2342 via Telnet after sideloading an application with --debug option.  However we keep getting connection refused.  However, we can connect to 192.168.35.2 port 2345 via Telnet, but it is gdb.  Please advise.

https://docs.microsoft.com/en-us/azure-sphere/install/qs-blink-cli  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d1a6db2-a0b8-7c2c-31a3-8ab9e66296a3
* Version Independent ID: 85df7f2f-635a-1490-3073-d88f7cd6c8a2
* Content: [Azure Sphere Hello World sample application Quickstart for Windows CLI](https://docs.microsoft.com/en-us/azure-sphere/install/qs-blink-cli)
* Content Source: [AzureSphere/articles/install/qs-blink-cli.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-blink-cli.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@maskimthedog Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@maskimthedog  If your PC can connect to the Azure Sphere device, but often drops the connection, you may have a conflict in the IP subnet.

Azure Sphere uses subnet 192.168.35.*. If you have other software that uses the same subnet, either disable that software or limit the range of IP addresses that it uses.

For high-level application, you can see the port 2342 with gdb. Please refer [Build, deploy, and debug a high-level application from the Windows command line](https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build#sideload-and-debug) 

"Open a command prompt and use any Windows terminal client to read the output stream from the process. Specify 192.168.35.2 as the IP address and 2342 as the port."

For more information about debugging with gdb, see GDB: [The GNU Project Debugger](https://www.gnu.org/software/gdb/documentation/)

**Comment by mehrdadhe** [comment]
I have the same issue.

**Comment by mehrdadhe** [comment]
Could be related to the OS update?

**Comment by mehrdadhe** [comment]
@AshokPeddakotla-MSFT I tested the ip and port. When target is not connected, the address is free and nothing on the output. When target is connected, connection is refused which I guess that is because of the target using this address.

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe Which version of SDK and OS your device is running?

**Comment by mehrdadhe** [comment]
@AshokPeddakotla-MSFT here it is:
SDK version: 20.01
OS version: 20.03

**Comment by robkrakora** [comment]
I have the same versions as @mehrdadhe.

**Comment by maskimthedog** [comment]
I have the same versions as @mehrdadhe.

**Comment by mehrdadhe** [comment]
@maskimthedog , @robkrakora 
Just to share my experience, my code didn't work with debugger and I tried the sample code (Hello world) again to figure out why. First few tries didn't help. After few tries the debugger works again. No idea what's going on but maybe this could help.

**Comment by maskimthedog** [comment]
@mehrdadhe Thanks, my co-worker was finally able to get it to work with his Sphere after unsuccessful attempts.  It just started working as in your case.

**Comment by AshokPeddakotla-MSFT** [comment]
@maskimthedog Just to confirm, Are you still seeing this issue or resolved after trying multiple times?

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
