### ISSUE TITLE
Azure Sphere Tool Version vs Target OS Version

### ISSUE THREAD

**Issue by mehrdadhe** [MicrosoftDocs/azure-sphere-issues#223]
Should both azure sphere tools and OS running on the target have the same version?
Here is the output of ```azsphere show-version```: **20.01**
and here is the output of ```azsphere device show-os-version``` on my Ubuntu 18.04:
**Your device is running Azure Sphere OS version 20.03.**

I have an issue with the debugger and I suspect may this incompatibility could be the reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by JonasHuelEON** [comment]
After 20.03 today 20.04 got released while the Linux SDK is still on 20.01.

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe You have mentioned that after retrying your issue got resolved on 
https://github.com/MicrosoftDocs/azure-sphere-issues/issues/222
do let us know if you are still blocked and need further help.

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you and your issue is resolved as per the feedback specified on the another issue, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
