### ISSUE TITLE
[Azure Sphere] Ethernet Image Memory Usage

### ISSUE THREAD

**Issue by mehrdadh** [MicrosoftDocs/azure-sphere-issues#225]
Does ethernet image takes memory usage out of 256KiB memory or it runs separately?
It would be great if you could clarify this in the doc.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3781077-8806-0de8-85c1-a0e08b3abe8c
* Version Independent ID: f53b30fb-3874-c03e-bb5e-ab194b15fc53
* Content: [Connect Azure Sphere to Ethernet](https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet)
* Content Source: [AzureSphere/articles/network/connect-ethernet.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/connect-ethernet.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@mehrdadhe Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding @pennyo and content author @Phka for further review and update the doc.

**Comment by pennyo** [comment]
@mehrdadh The board configuration does not count against the 1 MiB application package size limit nor against the 256KiB reserved for the high-level app. 

We're updating the documentation to include this information.
