### ISSUE TITLE
Device Twin

### ISSUE THREAD

**Issue by sylvaingirardbe** [MicrosoftDocs/azure-sphere-issues#226]
I can't seem to find any documentation on the concept 'Device twin'. I would at least expect a short explanation of it here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8695327d-543d-c26e-52e9-df2aa97cb35d
* Version Independent ID: 01e4182d-33ea-6843-c810-410b6113fdb5
* Content: [Terminology - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/product-overview/terminology)
* Content Source: [AzureSphere/articles/product-overview/terminology.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/product-overview/terminology.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by asergaz** [comment]
Hello @sylvaingirardbe , thank you for your suggestion. Device Twin relates with a terminology used on IoT Hub. See: [Understand and use device twins in IoT Hub](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins)

I would think that, the best place to add a reference to Device Twins is on the doc that we mention it itself. I see Device Twin mentioned here: [Set up an Azure IoT Hub for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub) .

I am assigning this issue to @pennyo to enhance the documentation accordingly.

Thank you so much!

**Comment by pennyo** [comment]
@sylvaingirardbe Thank you for your feedback. We'll consider this for a future release.

**Comment by ericawes** [comment]
assigned to v-lobe

**Comment by ericawes** [comment]
@sylvaingirardbe  Thank you for the suggestion; we added a couple links to [Understand and use device twins in IoT Hub](https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins), and added an entry for device twins on the [Azure Sphere terminology](https://docs.microsoft.com/azure-sphere/product-overview/terminology) page.
