### ISSUE TITLE
Contact information missing.

### ISSUE THREAD

**Issue by JuergenSchwertl** [MicrosoftDocs/azure-sphere-issues#227]
Page refers to "Microsoft supplies the RF Tools package upon request." but doesn't state **where** to request it from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c02b89c-3777-fbec-1e37-8f33b4a3283c
* Version Independent ID: 5cd5717c-f46c-be69-8c2b-3f805b8c8e54
* Content: [Radio frequency (RF) test tools - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/rf-tools#rf-settings-tool)
* Content Source: [AzureSphere/articles/hardware/rf-tools.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/rf-tools.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@JuergenSchwertl Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@JuergenSchwertl Doc has been updated. Please see below information.

![image](https://user-images.githubusercontent.com/44426435/92694671-076c3580-f365-11ea-9a2d-1073ec9e9a1f.png)


> Microsoft supplies the RF Tools package upon request to customers, partners, and security researchers. You can request them from your technical sales professional (TSP). If you don't have a TSP, please send an email to **azcommunity@microsoft.com** with the following information:
> 
> - Your name, organization, and contact information.
> - Contact information for your Microsoft account team or TSP, if you have one.
> - If you're building a module (rather than a device that uses MT3620 chips directly), your reason for requiring the RF tools.
> - The kinds of tests you plan to run using the tools.
> - Projected timeline for manufacturing (when do devices need to be manufactured/certified).
> - A Microsoft representative will work with you to determine the appropriate distribution channel.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
