### ISSUE TITLE
Image Not Downloading to Device

### ISSUE THREAD

**Issue by Asvaldrz** [MicrosoftDocs/azure-sphere-issues#228]
I have followed this tutorial multiple times and can't get the image to download, even after waiting for hours.

https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment

It appears the deployment worked as image can be seen with the ```azsphere device img list-targeted``` command, but when the ```azsphere device img list-installed``` command is run, nothing is installed.

Any help would be greatly appreciated. Below is from my terminal showing those commands, their output and what version of the sphere OS i am running.

```
C:\Users\mraadmin\Documents>azsphere device img list-installed
No installed images.

C:\Users\mraadmin\Documents>azsphere device img list-targeted
Successfully retrieved the images to be installed on device with ID 'B7EE096EAAE5FF7633E8B57AE5A6AE194A3C20C8E42CA16714C04186C33F86A0056457D71CD6722507787757AAC9E18643C8775727916A29A875928908EC4202' from the Azure Sphere Security Service:
 --> AzureSphereBlink
   --> Image type:   Application
   --> Component ID: 3450c44e-b1f4-4c2b-a43b-ea5124c50711
   --> Image ID:     d7c7b055-df55-4782-85e4-7699e0d691dc

C:\Users\mraadmin\Documents>azsphere device show-deployment-status
Your device is running Azure Sphere OS version 20.04 Update 2.
The Azure Sphere Security Service is targeting this device with Azure Sphere OS version 20.04 Update 2.
Your device has the expected version of the Azure Sphere OS: 20.04 Update 2.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f06ff328-8ce0-ed53-ec16-77557571701c
* Version Independent ID: 6f534143-977d-a964-f170-ee07f0a3e083
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment)
* Content Source: [AzureSphere/articles/install/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@Asvaldrz Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by Asvaldrz** [comment]
https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment

it was this document, sorry i did click to github from that documents page.

**Comment by Asvaldrz** [comment]
It turns out this may not have been working due to the sphere wifi. Although the wifi said it was ok and connected when i asked wifi status. When i tried to go back to development and run say the "AzureIoT" example.  The network interface would not pass the ready check.
Removing Wifi networks and re-adding didn't help; i had to run device restore.

Follow up question on application updates when we don't have access to the device.
Now i do get image updates if i push the reset button. But we're planning on using this for devices that need remote over the air updates. Is there a way i can force an update fro the cloud side?

**Comment by AshokPeddakotla-MSFT** [comment]
@Asvaldrz Please ensure that have met all the pre-requisites.
Have you tried [Recover the system software](https://docs.microsoft.com/en-us/azure-sphere/deployment/recover) using **azsphere device recover** ?

**Comment by Asvaldrz** [comment]
The device recover is what i had done and this allow the updates to start to work,
