### ISSUE TITLE
Can the Ethernet be used for all OTA Updates

### ISSUE THREAD

**Issue by Asvaldrz** [MicrosoftDocs/azure-sphere-issues#229]
Can the Ethernet setup this way be used by the sphere to do all applications and deployment updates etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3781077-8806-0de8-85c1-a0e08b3abe8c
* Version Independent ID: f53b30fb-3874-c03e-bb5e-ab194b15fc53
* Content: [Connect Azure Sphere to Ethernet](https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet)
* Content Source: [AzureSphere/articles/network/connect-ethernet.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/connect-ethernet.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@Asvaldrz Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
When a device is connected to internet all OTA updates will occur. 
@pennyo Could you please confirm on the above?

**Comment by AshokPeddakotla-MSFT** [comment]
@Asvaldrz Have you tried already updating applications and deployments and facing some issues with Ethernet? As I mentioned, OTA updates will occur if a device is conencted to internet.

**Comment by Asvaldrz** [comment]
I will try again. But for instance, to use Ethernet it has to be an image in the deployment. To be used for deployment, that image would already have to be installed.....

**Comment by bawilless** [comment]
@asvaldrz,

You can add the ethernet image to your OTA deployment.  Instructions are documented here:  https://docs.microsoft.com/en-us/azure-sphere/network/connect-ethernet#cloud-deploy-a-board-configuration-image-package.  

In the case where your device will only use the ethernet connection to the internet, then you are correct you must install the ethernet package to your device in the manufacturing step.  That way once deployed to the field it would be able to use the ethernet connection for future OTA updates.

**Comment by pennyo** [comment]
@Asvaldrz Yes, @bawilless is correct.

**Comment by AshokPeddakotla-MSFT** [comment]
Thanks for the suggestions @bawilless
@Asvaldrz As Penny mentioned, the documentation will be updated in the future release.
Hope the above suggestions addresses your question. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
