### ISSUE TITLE
Timezone offset in minutes or seconds

### ISSUE THREAD

**Issue by tcarter-caengineering** [MicrosoftDocs/azure-sphere-issues#230]
I found the the statement "You can't set the offset in minutes or seconds" confusing as I am able to modify my timezone by a minutes resolution if I use the following format while setting the "TZ" environment variable, the format I use is the following "IST-5:30EDT". Is the mentioned statement outdated above? It is important to be able modify the time zone UTC offset by minute increments so time zones like Indias can be supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87f01cd-eb60-c62c-9b48-9d0eb932e09f
* Version Independent ID: 2f57fec8-f7ce-4cb9-e078-70dc3dbac021
* Content: [Manage system time and the RTC in high-level applications - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/rtc#feedback)
* Content Source: [AzureSphere/articles/app-development/rtc.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/rtc.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@tcarter-caengineering Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding author @pennyo for further review and update the doc as appropriate.

**Comment by pennyo** [comment]
@tcarter-caengineering Thank you for your feedback. We have updated the documentation.
