### ISSUE TITLE
different in document

### ISSUE THREAD

**Issue by eltociear** [MicrosoftDocs/azure-sphere-issues#232]
英語と日本語のドキュメントで記号の食い違いが存在します
（日本語のtypo?）

ja-jp
```
Linux コマンド ラインの場合は "" を使用できますが
```
en-us
```
" \ " for the Linux command line can be used
```

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a2e947f1-9c3e-9840-a31e-ec3bfa289cc2
* Version Independent ID: 46e0fd4d-10bc-9d57-f10f-e6b5d46f0c7f
* Content: [CMake を使用してビルドを構成する](https://docs.microsoft.com/ja-jp/azure-sphere/app-development/using-cmake-functions)
* Content Source: [AzureSphere/articles/app-development/using-cmake-functions.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.ja-JP/blob/live-sxs/AzureSphere/articles/app-development/using-cmake-functions.md)
* Product: **azure-sphere**
* GitHub Login: @sethmcevoy
* Microsoft Alias: **azurespheredocs**

**Comment by AjayKumar-MSFT** [comment]
@eltociear, Thanks for leveraging Azure docs feedback channel to raise this question. 

We cannot completely understand your question as this is an English global support. After translating your question, the following is my understanding, please let us know if we are missing something while we check on this and get back.

[ There is a discrepancy between symbols in English   and Japanese documents   (Japanese typo?)
ja-jp
For Linux command line you can use "" ]

**Comment by AshokPeddakotla-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ishasahni1** [comment]
@CeciAc @DavidPrio can you kindly look into the Japanese feedback and help in addressing this feedback. This file is Human Translated.

**Comment by pennyo** [comment]
@eltociear Thank you for the feedback. We have published an update to the documentation.
