### ISSUE TITLE
Azure Sphere API: Networking_IsNetworkingReady shows false information.

### ISSUE THREAD

**Issue by ravipath** [MicrosoftDocs/azure-sphere-issues#233]
**API**: int Networking_IsNetworkingReady(bool *outIsNetworkingReady);
**header**: networking.h

**Problem Statement:** I need to check if the Internet connectivity is available and take an action accordingly.

**Issue**: Azure Sphere provides this API for the same purpose. However, this API reports false positive. I have checked by connecting the Azure Sphere device to AP and Hotspots having no Internet connectivity. Regardless, I get the Internet connectivity as available.

Link to the document: https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd167041-723d-8652-c852-d8114bbd3612
* Version Independent ID: 13412e33-7312-3b2e-0081-4a4303de8530
* Content: [Networking_IsNetworkingReady function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by ravipath** [comment]
@AshokPeddakotla-MSFT I have updated the issue with the requested information (microsoft doc link).

**Comment by chandran-Az** [comment]
Hi ravipath - can you please elaborate on the scenario? 

This function does not check for internet connectivity. It only checks if all the components on device are initialized and has an IP address.

We will get the document updated so that it's clear.

**Comment by AshokPeddakotla-MSFT** [comment]
Thanks for the confirmation @chandran-Az. Assigning this issue to the author to update the doc as appropriate.

**Comment by ravipath** [comment]
Thank you Ashok. May I also request to make the appropriate changes in the WiFi sample code as well?

**Function Name:**  static ExitCode CheckNetworkReady(void)
**Source:** https://github.com/Azure/azure-sphere-samples/blob/master/Samples/WiFi/WiFi_HighLevelApp/main.c
**Line#:** 700

This function call makes use of **_Networking_IsNetworkingReady_** and reports whether connectivity to Internet is available or not.

**Comment by pennyo** [comment]
@ravipath Thank you for your feedback. We'll investigate and make any necessary changes.

**Comment by pennyo** [comment]
@ravipal  We have updated the online documentation in AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready.md. We may have additional changes in the future.
