### ISSUE TITLE
CMakeLists.txt shall be instead of settings.json

### ISSUE THREAD

**Issue by korkikian** [MicrosoftDocs/azure-sphere-issues#235]
Hi,

I believe that the following description is a bit wrong:
Open .vscode/settings.json.
Call the azsphere_target_hardware_definition function to point to the directory that contains the target hardware definitions for your device. Microsoft provides target hardware definitions in the Hardware directory of the Azure Sphere Samples repo. For example: <path-to-cloned-samples>/Hardware/mt3620_rdb

The function azsphere_target_hardware_definition shall be declared in CMakeLists.txt instead of settings.json. The description on the site is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaa9c32b-68c1-e25d-8846-49d4b2927cd9
* Version Independent ID: 169a32ef-2e16-dd5a-03cb-9867288ea94f
* Content: [Azure Sphere high-level application Quickstart for Visual Studio Code](https://docs.microsoft.com/en-us/azure-sphere/install/qs-blink-vscode)
* Content Source: [AzureSphere/articles/install/qs-blink-vscode.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-blink-vscode.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
@korkikian , Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by pennyo** [comment]
@korkikian Good catch! Thank you for the feedback. We have corrected the documentation.
