### ISSUE TITLE
applibs/pwm.h, applibs/adc.h and others are almost empty

### ISSUE THREAD

**Issue by johnhatten2** [MicrosoftDocs/azure-sphere-issues#236]
I was trying to get used with basic peripherals on my seeed mini dev board, and I realized my pwm.h is almost empty, there's no functions, structs or defines to use, like it should according to the documentation.

I thought the problem was from the SDK, but it is up to date

``` /// \file pwm.h
/// \brief This header contains functionality for interacting with PWM hardware. Access to
/// individual PWMs is restricted based on the Pwm field of the application's manifest.
///
/// PWM functions are thread-safe.

#include <stdbool.h>
#include <stdint.h>

#pragma once

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif



---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5e8f623a-a8a5-ba80-acf3-77cb4f7bc5dc
* Version Independent ID: 949d5e86-d87d-99ac-fc13-6ec3a27049c8
* Content: [Informations de référence sur les bibliothèques d’applications Azure Sphere concernant pwm.h](https://docs.microsoft.com/fr-fr/azure-sphere/reference/applibs-reference/applibs-pwm/pwm-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-pwm/pwm-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.fr-FR/blob/live-sxs/AzureSphere/articles/reference/applibs-reference/applibs-pwm/pwm-overview.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by BharathNimmala-MSFT** [comment]
@johnhatten2  Please help with the link of document on which above document feedback request is created.
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by johnhatten2** [comment]
The file i'm refering to is under Microsoft Azure Sphere SDK\Sysroots\5\usr\include\applibs\pwm.h. I followed all the getting-started steps and I could get the blinky working on my seeed mini dev board. I tried to make a PWM peripheral to work, only to realize that pwm.h is emptier than it should (see code above vs this page : https://docs.microsoft.com/fr-fr/azure-sphere/reference/applibs-reference/applibs-pwm/pwm-overview )

I'm quite new in this field and I was looking for some kind of support so I ended up here. not sure if it is the right place.

**Comment by BharathNimmala-MSFT** [comment]
@johnhatten2  Thank you for sharing the document link, our team will further look into this thread and direct you accordingly.

**Comment by thalesx** [comment]
@johnhatten2 , all PWM APIs are still in Beta for ARV=5, so they won't show up in the production sysroot header. You need to target the Beta sysroot to get the header with the APIs. Basically you need to change your project to target 5+Beta2004.

**Comment by johnhatten2** [comment]
that works! thanks!
