### ISSUE TITLE
Cloud Deployment Question

### ISSUE THREAD

**Issue by mesgar** [MicrosoftDocs/azure-sphere-issues#237]
Hi,

What exactly happens when I create the deployment? 
My app goes to the cloud from my C derive and by pressing reset button sphere downloads the app from cloud?

`azsphere device-group deployment create --devicegroupname "Field Test" --productname "XXXXX" --filepath "C:/dev/Azure/Sphere/samples/Samples/AzureIoT/out/ARM-Release/AzureIoT.imagepackage"`

When I change something in my application and rebuild it in visual studio, the app running in Sphere updates automatically via cloud deployment? 
Or I should execute above command and press reset button again?

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f06ff328-8ce0-ed53-ec16-77557571701c
* Version Independent ID: 6f534143-977d-a964-f170-ee07f0a3e083
* Content: [Create a cloud deployment tutorial - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment)
* Content Source: [AzureSphere/articles/install/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@mesgar Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by mesgar** [comment]
I went ahead and redeployed my application and I had to press reset button to download the latest version of my app.
It's quiet understandable and acceptable, you can't just download and replace a running application.
On the other hand, in real world scenarios you can't tell your users across the country to press the reset button to get the latest version. 
Any suggestions?

 link of document:
https://docs.microsoft.com/en-us/azure-sphere/install/qs-first-deployment

**Comment by AshokPeddakotla-MSFT** [comment]
@mesgar Thanks for the link. I am checking on this issue and update you as earliest.

**Comment by bawilless** [comment]
@mesgar,

The Azure Sphere devices check to see if they are running the correct software application(s) every time they check-in with the Azure Sphere Security Service (AS3).  This check-in happens on device startup and then every 24 hours after that.  So when you deploy a new application form your PC using the command line, you're updating the device group managed by AS3. 

If it's important that your devices reset and download the application ASAP, then you would need to implement some kind of a reset mechanism controlled from the cloud.  This is easy to do with [direct method calls](https://www.element14.com/community/groups/azuresphere/blog/2019/09/12/implementing-direct-methods-in-azure-sphere).  If it's not time critical for your devices to get the update, then they will all get the new application within a 24 hour period, assuming they can connect to AS3.

**Comment by mesgar** [comment]
Checking and getting the latest version on a daily basis works for me.
Thanks
