### ISSUE TITLE
CMake Ninja

### ISSUE THREAD

**Issue by woutervanranst** [MicrosoftDocs/azure-sphere-issues#238]
I'm getting an error "CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool."

Can you caveat what the suggested solution is in the "getting started"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56bb629c-a1b1-a305-67c7-eaf46cfc3c8b
* Version Independent ID: ff97f9a2-cbd7-89bc-3837-f81952d15833
* Content: [Build your first Azure Sphere application tutorial](https://docs.microsoft.com/en-us/azure-sphere/install/qs-blink-application?tabs=windows&pivots=vs-code)
* Content Source: [AzureSphere/articles/install/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @Phka
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
@woutervanranst Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
@woutervanranst We are working on this, please let us know if you have further questions meanwhile we get back to you soon.

**Comment by chandran-Az** [comment]
@woutervanranst - Does the machine have CMake & Ninja installed and path for Ninja added to your environment variable?
Check link (https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=vs-code#install-cmake-and-ninja-on-windows)

**Comment by SatishBoddu-MSFT** [comment]
@woutervanranst 
Just checking back! Please let us know if you need further help.

**Comment by SatishBoddu-MSFT** [comment]
@woutervanranst 
Since we didn't received any response, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
