### ISSUE TITLE
create tenant per device

### ISSUE THREAD

**Issue by matsujirushi** [MicrosoftDocs/azure-sphere-issues#24]
I got this message.

![image](https://user-images.githubusercontent.com/8079404/46020043-630d6c00-c118-11e8-80e8-97f4ac24c85a.png)

```
Create a new Azure Sphere tenant. Caution: this operation can only be done once per Azure Sphere device.
```
What's mean 'this operation can only be done once per Azure Sphere device.'?

Do you recommend to create Azure Sphere tenant by Azure AD tenant? or by Azure Sphere device?

**Comment by sergaz-msft** [comment]
Thanks for the feedback @matsujirushi . This message means that a device can only be used once to create a tenant. We are working on making this message more clear.

Our recommendation is that a typical organization only requires one AS tenant. If a tenant already exists, do not create another one unless your company or organization requires more than one tenant.
If you are absolutely certain that you want to create another one, use the following command: 

`azsphere tenant create --force --name <my-tenant>`

You can find the instructions to create tenants [here](https://docs.microsoft.com/en-us/azure-sphere/quickstart/claim-device).

Thank you!

**Comment by matsujirushi** [comment]
Hi, @sergaz-msft 
I understood. Thanks.

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
