### ISSUE TITLE
Missing file extension on header file

### ISSUE THREAD

**Issue by andremuz** [MicrosoftDocs/azure-sphere-issues#240]
"applibs/sysevent" should be "applibs/sysevent.h"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9800cae8-dfe3-2903-0990-ae90b3fa38a1
* Version Independent ID: a79b06c0-38e8-6ab1-9c6b-27da5171db4a
* Content: [Azure Sphere Application Libraries reference](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/api-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/api-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/api-overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@andremuz Thanks for your contribution, I've addressed this issue in PR:[ https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/pull/193]( https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/pull/193)
The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@andremuz This has been fixed.

![image](https://user-images.githubusercontent.com/44426401/88254728-c005e900-ccd3-11ea-8c48-a3f3036ea171.png)

We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
