### ISSUE TITLE
pthreads minimal code sample

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/azure-sphere-issues#241]
This document mentions pthread library support which is a major boost for application developers. Given that not all standard C library features [[1](https://docs.microsoft.com/en-us/azure-sphere/app-development/baseapis#c-standard-library-features)] are not supporeted, is it possible to extend this document with a minimal code sample using pthreads? E.g code sample in watchdog timer documentation [[2](https://docs.microsoft.com/en-in/azure-sphere/app-development/watchdog-timer)].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1191ab-cda7-1fdd-a908-2a1b7d8b2fcb
* Version Independent ID: baeeae59-1faf-fcd7-3bea-af6e7d467573
* Content: [Asynchronous events, polling, threads, and concurrency - Azure Sphere](https://docs.microsoft.com/en-in/azure-sphere/app-development/threads-concurrency)
* Content Source: [AzureSphere/articles/app-development/threads-concurrency.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/threads-concurrency.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
@kiranpradeep Thank you for your feedback. We'll investigate the topic for inclusion in an update of the docs. Is there a particular scenario you're interested in?

**Comment by bawilless** [comment]
I would love to see a pthread example!

**Comment by SatishBoddu-MSFT** [comment]
Hello @kiranpradeep @bawilless Could you please let us know if there is a articular scenario you're interested in?

**Comment by kiranpradeep** [comment]
@SatishBoddu-MSFT @pennyo Thanks for the reply. But, I am not sure why this question is being asked.  A particular scenario request would have been appropriate if I had asked for a higher level library sample like libmodbus or libmosquitto. But pthreads does not fall into that league. It is a fundamental building block in a linux application. For e.g the watchdog-timer [[1](https://docs.microsoft.com/en-in/azure-sphere/app-development/watchdog-timer)] example is only a generic one and not catered to a particular scenario.

Anyway, if that helps, I was trying to port the PrivateNetworkServices [[2](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/PrivateNetworkServices)] using a thread per tcp client instead of the epoll loop. And I need pthreads for the same.

**Comment by pennyo** [comment]
@kiranpradeep Thank you for the additional information.

**Comment by pennyo** [comment]
@kiranpradeep We've added this topic to our backlog for future inclusion.
