### ISSUE TITLE
Broken link for tenant certificate page.

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#242]
Broken link for tenant certificate page.

https://docs.microsoft.com/en-us/azure-sphere/deployment/tenant-cert.md

should be

https://docs.microsoft.com/en-us/azure-sphere/deployment/tenant-cert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0893c5f5-fd90-8aae-f6ae-62917288b7c2
* Version Independent ID: 77422ee2-84c7-03d6-72e9-85491831347f
* Content: [What's new - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new)
* Content Source: [AzureSphere/articles/product-overview/whats-new.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/product-overview/whats-new.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 PR has been created to fix this issue. Changes will go live once it has been peer reviewed and merged. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pennyo** [comment]
Link text should be: https://docs.microsoft.com/azure-sphere/deployment/tenant-cert

**Comment by pennyo** [comment]
We are republishing today to fix a couple other things, will correct this there.
