### ISSUE TITLE
mutual authentication extension

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/azure-sphere-issues#243]
Can this document be extended to include mutual authentication case? The webservice documentation [[1](https://docs.microsoft.com/en-us/azure-sphere/app-development/curl#mutual-authentication)] covered mutual authentication. Without mutual tls authentication, we cannot take full advantage of sphere security.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc223e57-432c-6cd3-f5bf-de8a787a5e90
* Version Independent ID: f2c0b36f-5daf-cf52-e604-1ee837e97ea4
* Content: [Use wolfSSL for TLS connections - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/wolfssl-tls)
* Content Source: [AzureSphere/articles/app-development/wolfssl-tls.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/wolfssl-tls.md)
* Product: **azure-sphere**
* GitHub Login: @kagatlin
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@kiranpradeep Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
I have assigned this issue to author @pennyo for further review and update the doc as necessary.

**Comment by pennyo** [comment]
@kiranpradeep Support for server-side authentication with wolfSSL is currently planned for an upcoming OS release. We'll add this to the documentation when the product supports is.

**Comment by kiranpradeep** [comment]
@pennyo Thanks for the helpful reply. Kindly the Azure Sphere Faq [link](https://azure.microsoft.com/en-in/services/azure-sphere/#faqs) which I feel should be updated until server side authentication is complete.

> Question: Does my entire environment needs to be on Azure to use Azure Sphere?
> Answer: Azure Sphere is engineered to integrate with any cloud service, public or private. You can connect to other clouds for app data while running Azure Sphere or optimise efficiencies by using Azure Sphere alongside Visual Studio and Azure IoT.

Now, shouldn't that answer be updated: Currently, non HTTP cloud services from 3rd party (e.g. MQTT brokers) cannot verify device authentiation certificates provided by AS3. This feature is planned to be included in an upcoming OS release.
