### ISSUE TITLE
Inconsistent description and picture for 'Renew tenant CA certificate'

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#246]
In 'Renew tenant CA certificate' section, it seems like the picture is not consistent with the description. 

1) Certificate B is become active after 30 days it was issued. But in the picture, it is 60 days after it was issued (5/2 - 7/2). 
2) The validation period of certificate B should start from 5/2, but in the picture, it starts from 8/1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3234b388-2251-0513-55b1-f380f27f4285
* Version Independent ID: 5e5ab326-6fac-5429-64b6-af1e1b070529
* Content: [Manage tenant CA certificates- Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/tenant-cert)
* Content Source: [AzureSphere/articles/deployment/tenant-cert.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/tenant-cert.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo To provide more clarity,  As specified in the image, 

![image](https://user-images.githubusercontent.com/44426435/89058475-f818c600-d37c-11ea-9fc7-7ff359a2586a.png)


2. The renewal process starts approximately 90 days before Certificate A expires. There is an overlap period before Certificate A expires and the new tenant CA certificate (Certificate B) becomes the active certificate. During this period, the status of the Certificate B is marked as Inactive and the Certificate A continues as the Active certificate.

As specified, Renewal process will be started on **5/3/2020**  if you observe there is a 90 days gap between the Cert A and Cert B. i.e from **5/3/2020** to **8/1/2020**. 

3. Certificate B becomes the active certificate, approximately 30 days after it has been issued. At this stage, the Certificate A is marked as Inactive and Certificate B becomes the Active certificate.

As specified, Certificate issued on **7/2/2020** and will become active after 30 days that means on **8/1/2020**

Does that answer your question? Do let us know if you need further details.

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Did you get a chance to look at my response? Do let us know if you have further queries.

**Comment by prabhushyja** [comment]
Thank you for the feedback. We've reworked the image to explain the overlap period when the tenant CA certificate is switched over to using the new certificate.

**Comment by AshokPeddakotla-MSFT** [comment]
@prabhushyja Thanks for an update. 
@xiongyu0523 please check the doc and let us know if you have any further queries. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by xiongyu0523** [comment]
Sorry the new picture and descriptions are way more focusing for me.. I have to raise more questions to try to understand.

1) Date is removed on picture. Can we have those numbers back to be a more concrete example?
2) 'The renewal process starts approximately 90 days before Certificate A expires.', what is the action for this renewal? I remember previously we have description says certificate B is issued and marked as inactive state?
3) Does 30 days mean 3) to 4)? The same question as before, we said it becomes active 30days after it is issued. I can't figure out how this reflect.
4) What is the color change point means?
5) 'When Certificate A expires, Certificate B is used to sign device certificates.', is this description accurate? My understanding is before certificate A expire, the certificate B is already the active CA certificate and responsible for device certificate issue. 
6) In some other document, i saw the renewal process starts 60 days before certificate expire, and here is 90 days. which one is correct?

**Comment by xiongyu0523** [comment]
@AshokPeddakotla-MSFT can you reopen it?

**Comment by AshokPeddakotla-MSFT** [comment]
@prabhushyja Could you please look into this feedback?

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Doc has been updated as per the feedback. Could you please check and let us know if you have further queries.

![image](https://user-images.githubusercontent.com/44426435/90150137-f6022e80-dda2-11ea-97b5-b3bf6a41845d.png)

**Comment by xiongyu0523** [comment]
It is more clear. Just one point need to be clarified, certificate B is issued 5/3/2020, it will be expired by 5/3/2022. right? In the picture, the lifetime of certificate looks like start from 8/1/2020 and expires 8/1/2022, which is not correct?
