### ISSUE TITLE
Minor typo on page

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#247]
The first sentence on this page is:  

Hardware definitions **his** topic describes how to use hardware definitions in your high-level application.

It looks like one or two characters got accidently deleted.  Your documentation is so clean I figured you would want to fix this.

Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fe303-324f-149e-d664-95b3f335bbb0
* Version Independent ID: 98bfc861-2906-8225-455c-573035403312
* Content: [Use hardware definitions - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies)
* Content Source: [AzureSphere/articles/app-development/manage-hardware-dependencies.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/manage-hardware-dependencies.md)
* Product: **azure-sphere**
* GitHub Login: @richardtaylorrt
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Hello @bawilless 
Thanks for the feedback! We will fix it!

**Comment by SatishBoddu-MSFT** [comment]
Hello @bawilless The Fix is merged! Thanks for your contribution.

![image](https://user-images.githubusercontent.com/62923178/89353037-69e95c00-d66a-11ea-8995-5b7f179f8e47.png)
