### ISSUE TITLE
'Load the client certificate' should be 'Load the root CA certificate for Server'

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#248]
---

The title and description in this section should be corrected to root CA certificate, which is used to verify server identity

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc223e57-432c-6cd3-f5bf-de8a787a5e90
* Version Independent ID: f2c0b36f-5daf-cf52-e604-1ee837e97ea4
* Content: [Use wolfSSL for TLS connections - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/wolfssl-tls)
* Content Source: [AzureSphere/articles/app-development/wolfssl-tls.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/wolfssl-tls.md)
* Product: **azure-sphere**
* GitHub Login: @kangsu
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
@xiongyu0523 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by SatishBoddu-MSFT** [comment]
Hello @kangsu Thanks for your patience on this issue, 
We intend to update the documentation soon. Will provide more updates soon.

**Comment by pennyo** [comment]
@xiongyu0523 This document has been updated.
