### ISSUE TITLE
Is there a difference between registering and claiming a device?

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/azure-sphere-issues#249]
From Claim the chip section, 

>  The silicon manufacturer creates the device ID, stores it on the chip, and _registers_ it with Microsoft....You must also _claim_ the Azure Sphere chips in all your connected devices. _Claiming_ involves moving the Azure Sphere chip to your organization's cloud tenant. To claim one or more chips, use the following command. On Windows, you must use an Azure Sphere Developer Command Prompt.
> 
> azsphere device claim --deviceid GUID

1. This gives an impression that registering and claiming device are seperate operations. Are they? If yes, then, is the process to _register_ a device with Microsoft documented?
2. Is there anything that prevents a rogue entity from performing "azsphere device claim --deviceid <GUID>" with random GUIDs that might get generated in the future for valid silicon chips?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6089189-0c15-d287-ff98-3bb424e4c24f
* Version Independent ID: ece2a111-b6a4-483a-e571-8f347757e285
* Content: [Cloud configuration tasks - Azure Sphere](https://docs.microsoft.com/en-in/azure-sphere/hardware/cloud-configuration-tasks)
* Content Source: [AzureSphere/articles/hardware/cloud-configuration-tasks.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/cloud-configuration-tasks.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by mike-urnun-msft** [comment]
@kiranpradeep Thank you for your feedback! We will review and update as appropriate.

**Comment by chandran-Az** [comment]
@kiranpradeep - The device registration and claim process are 2 different tasks that the manufacturer needs to execute. During the device registration, manufacturer provides the generated device keys to Microsoft (internal documented process) and Microsoft uses this information to generate the device ids and 

Claim process is where the manufacturer associates the devices to their tenant along with other tasks to complete the claims process.

**Comment by kiranpradeep** [comment]
Thanks for the reply. The docs mentions that device ID is shared by manufacturer. But, the reply above mentions that device key is shared by the manufacturer. Are they the samet thing? If keys, is it remote-attestation public key? Is the key alone enough to uniquely identify the device. There are too many questions in the minds of the reader. So, is it possible to share the internal documented process? It really helps the reader with more clarity.

**Comment by chandran-Az** [comment]
Device registration is performed by Silicon manufacturer, while the claims process is performed by device manufacturer. The exact documentation is only applicable for manufacturing purposes and cannot be shared publicly. Hope this helps.

**Comment by kiranpradeep** [comment]
We are service integrators. We are expected to take the sphere device to customers. Imagine we trying to sell this exceptional security story sold to us.

**Customer:** What information is pre-shared about his future device to Microsoft?  
**Self:** Only device IDs are transferred as per documentation.
**Customer:** Without sharing public keys how will awesome remote attestation work?
**Self:** _Maybe_ public keys are also transferred. But that is not documented. 
**Customer:** Is anything  else also transferred by manufacturer to Microsoft?
**Self:** I am not sure and Microsoft is neither will to share the information.
**Customer:** Bye Bye.

**Comment by SatishBoddu-MSFT** [comment]
Hello @kiranpradeep Thanks for the feedback.

Please send an email to azcommunity@microsoft.com with the below details, so that we can work/discuss closely on this matter. 

**Thread URL:** https://github.com/MicrosoftDocs/azure-sphere-issues/issues/249
**Your Subscription ID:** 
**Email Subject :** Attn Satish Boddu 

Please let me know once you have done the same.

**Comment by SatishBoddu-MSFT** [comment]
Hello @kiranpradeep,
Just checking back! Please let us know if you need further help.

**Comment by SatishBoddu-MSFT** [comment]
Hello @kiranpradeep, Just checking back! 
Let us know if there are still any additional queries we can help you with or you can send us an email for further discussion.
Happy to help!

**Comment by bawilless** [comment]
@kiranpradeep,

These two articles will help you understand more about the remote attestation step and how the certificates are managed

- https://azure.microsoft.com/en-us/blog/anatomy-of-a-secured-mcu/

- https://azure.microsoft.com/en-us/resources/best-practices-for-implementing-seven-properties-in-azure-sphere/

This last article is long but packed with good information.  Specifically to help answer your questions look at these two best practices . . . 
Best practice #5: "Use silicon-based Measure Boot to attest Secure Boot"
Best practice #7 "Handle server certificate expiration gracefully"

Brian

**Comment by kiranpradeep** [comment]
Thanks @SatishBoddu-MSFT and @bawilless for the helpful document.
