### ISSUE TITLE
Need more detail

### ISSUE THREAD

**Issue by JakeSays** [MicrosoftDocs/azure-sphere-issues#250]
Would it be possible to get more detail on each of the output modes? The meaning of each type and their typical use cases would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367f1c69-1d0c-fc09-2569-ae13c4cd140e
* Version Independent ID: 8c1dffd9-3dd1-81c4-fb37-f4141d88cb45
* Content: [GPIO_OutputMode enumeration - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-gpio/enum-gpio-outputmode)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-gpio/enum-gpio-outputmode.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-gpio/enum-gpio-outputmode.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@JakeSays Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@JakeSays  Great question! We'll consider it as a documentation enhancement request for a future update.

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Thanks for acknowledging the feedback. 
@JakeSays As mentioned, the doc will be enhanced in the future update. Do you have further queries? 
If not are we good to close this issue?

**Comment by JakeSays** [comment]
I don't. Thanks for taking care of this!
