### ISSUE TITLE
Step3 is out of date due to IoT Central UI changes

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#251]
Step3 in this page is out of date since IoT Central was updated recently. It now support enrollment group and user need set authentication type in that page and click save to see Certificate (X509) session . Please review and update accordingly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79eb45a2-0b0c-6449-5acc-504fb16583e6
* Version Independent ID: fa9be175-df4d-a165-144f-8abe62ecb7ea
* Content: [Set up Azure IoT Central to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-central)
* Content Source: [AzureSphere/articles/app-development/setup-iot-central.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-central.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@xiongyu0523 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
@prabhushyja Could you please look into this issue?

**Comment by pennyo** [comment]
Assigned to @LouisBerner for update.

**Comment by LouisBerner** [comment]
@xiongyu0523  - Thank you for your feedback. Your suggestion has been incorporated into core docs.

The change will be be published in a future update. Have a great day!
