### ISSUE TITLE
Is it possible to use umqtt client directly

### ISSUE THREAD

**Issue by stefan-hudelmaier** [MicrosoftDocs/azure-sphere-issues#252]
Hi, 

when writing a high-level application for Azure Sphere, is it possible to use the umqtt MQTT client (that the IoT Hub client is based on) instead of the IoT Hub client, e.g. for connecting to other MQTT brokers?

**Comment by AshokPeddakotla-MSFT** [comment]
@stefan-hudelmaier Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by xiongyu0523** [comment]
Hi, Stefan.

Yes, after 20.07, you can use wolfSSL API to do this. 
I have a personal example adding a MQTT client to sphere. 
https://github.com/xiongyu0523/azure-sphere-mqtts

Please be aware currently the client certificate must be external injected, which is less secure (trustworthy) than using built Azure  IoT Hub C SDK

**Comment by stefan-hudelmaier** [comment]
Hi Guys,

> Please help with the link of document on which above document feedback request is created.
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

I'm afraid it's more of a product question. Could you direct me where such questions should ideally be asked?

Thanks for the link @xiongyu0523, much appreciated. I have been poking in the `azure-sphere-samples`'s `AzureIoT` project and saw that it appears to use a modified version of the IoT Hub Device Client library for using the DAA certificate of Azure Sphere. Is that indeed the case?

Is it planned to make it possible for programs to access the DAA certificate and key for MQTT connections (or any TLS connection)?

Is it planned to open source the provided libraries, e.g. Iot Hub client, Azure c shared utility (both appear to be a variation of what is available on GitHub).

**Comment by AshokPeddakotla-MSFT** [comment]
@stefan-hudelmaier 

For using IoT SDK MQTT library - this cannot be used to directly access the DAA certs. You can bring your own MQTT library

> Is it planned to make it possible for programs to access the DAA certificate and key for MQTT connections (or any TLS connection)?

Yes, this is a planned feature In the upcoming 20.10 release that will be provided soon (with some limitations)!

Kindly follow the  [Azure updates]( https://azure.microsoft.com/en-us/updates/) and [What's new in Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new) for more updates.

**Comment by stefan-hudelmaier** [comment]
Awesome, thanks!
