### ISSUE TITLE
No ErrorResponse is returned

### ISSUE THREAD

**Issue by matsujirushi** [MicrosoftDocs/azure-sphere-issues#253]
No ErrorResponse is returned when called delete for product [api](https://docs.microsoft.com/en-us/rest/api/azure-sphere/product/delete).

**Success:**
```
{"TenantId":"31908d60-fc8a-4403-b739-348ee8705d66","OperationId":"0a8a1023-1c61-4f6c-831e-dab66a4448e8","CreatedDateUTC":"2020-08-31T11:52:04.407902Z","StartedDateUTC":null,"CompletedDateUTC":null,"OperationType":10,"State":0,"ResourceLocation":"","Error":null}
```

**Error:** <- device group and device using product
```
{"TenantId":"31908d60-fc8a-4403-b739-348ee8705d66","OperationId":"d122cee1-bda3-4c72-93e9-1b91d18e0c94","CreatedDateUTC":"2020-08-31T11:50:01.5251166Z","StartedDateUTC":null,"CompletedDateUTC":null,"OperationType":10,"State":0,"ResourceLocation":"","Error":null}
```

Is there any way to know if the delete was successful or not?

> Related Issues:  
> [デバイスに割り当てられたデバイスグループが削除できない](https://github.com/matsujirushi/AzureSphereExplorer/issues/5)

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback . Can you please share the link of the document which you are referring to here ?

**Comment by SatishBoddu-MSFT** [comment]
Hello @matsujirushi Thanks for the feedback.

Please create a new post on **Microsoft Q&A**.

Please do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

We will now proceed to close this thread.

**Comment by matsujirushi** [comment]
Hi @himanshusinha-msft ,
> Thanks for the feedback . Can you please share the link of the document which you are referring to here ?

https://docs.microsoft.com/en-us/rest/api/azure-sphere/product/delete

**Comment by matsujirushi** [comment]
Hi @SatishBoddu-MSFT ,
[Posted.](https://docs.microsoft.com/en-us/answers/questions/83297/no-errorresponse-is-returned.html)

**Comment by SatishBoddu-MSFT** [comment]
Thank you @matsujirushi , We will continue this discussion on Microsoft Q&A.
