### ISSUE TITLE
Receive device update - Show wifi status command needs update

### ISSUE THREAD

**Issue by ravindrank** [MicrosoftDocs/azure-sphere-issues#254]
Under section : Receive device update
The command provided is : azsphere device show-deployment-status
with the latest SDK the command needs to be : azsphere device wifi show-status

Example output:
>azsphere device wifi show-deployment-status
'show-deployment-status' is not a valid value for the 'Operation' command line option.
  Possible argument values include: 'add', 'disable', 'enable', 'forget', 'list', 'reload-config', 'scan', 'show', 'show-status'.

>azsphere device wifi show-status
SSID                : aaaa
Configuration state : enabled
Connection state    : connected
Security state      : psk
Frequency           : 2457
Mode                : station
Key management      : WPA2-PSK
WPA State           : COMPLETED
IP Address          : <removed>
MAC Address         : <removed>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db907e3-85a6-ab65-837b-7e6a5dc12224
* Version Independent ID: dfd84d21-060c-1ba2-6341-54ed7248ae23
* Content: [Configure networking and update device OS - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi)
* Content Source: [AzureSphere/articles/install/configure-wifi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/configure-wifi.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by ravindrank** [comment]
Sorry I realized its my mistake. Please ignore

**Comment by AshokPeddakotla-MSFT** [comment]
No worries. if you have a product-related question, please post to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/) and we will happily continue the conversation.

If you have documentation-related feedback, please create a new issue linking the exact document that you would like to change.
