### ISSUE TITLE
WifiConfig_SetSecurityType Function: Wrong Error Code for one of the scenarios

### ISSUE THREAD

**Issue by miz060** [MicrosoftDocs/azure-sphere-issues#256]
[Enter feedback here]
Hi, my name is Mitch Zhu (mitchzhu@microsoft.com). I'm part of Azure Sphere OSP Networking Team.

The error code for "the networkId parameter doesn't match any of the IDs of the stored networks" should be ENODEV, not ENOENT.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a002a29-c9f1-7dac-9ed3-4ec0d5470c83
* Version Independent ID: 34d0bee5-f5ac-42da-64a5-d18decdf800c
* Content: [WifiConfig_SetSecurityType function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-setsecuritytype)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-setsecuritytype.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-setsecuritytype.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Related: https://github.com/MicrosoftDocs/azure-sphere-issues/issues/257

**Comment by SatishBoddu-MSFT** [comment]
Hello @miz060 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @miz060
We will now proceed to close this thread.
