### ISSUE TITLE
WifiConfig_SetTargetedScanEnabled Function: Wrong Error Code for one of the scenarios

### ISSUE THREAD

**Issue by miz060** [MicrosoftDocs/azure-sphere-issues#257]
Hi, my name is Mitch Zhu (mitchzhu@microsoft.com). I'm part of Azure Sphere OSP Networking Team.

The error code for "the networkId parameter doesn't match any of the IDs of the stored networks" should be ENODEV, not ENONET.

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92cccb51-a96d-636f-2aae-f1bda0f19bad
* Version Independent ID: 7e68994e-ab21-d40a-7ceb-2fad052c0e21
* Content: [WifiConfig_SetTargetedScanEnabled function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-settargetedscanenabled)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-settargetedscanenabled.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/function-wificonfig-settargetedscanenabled.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Hello @miz060 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @miz060 
We will now proceed to close this thread.
