### ISSUE TITLE
Bad link for Sample: External MCU update - reference solution

### ISSUE THREAD

**Issue by Omakas** [MicrosoftDocs/azure-sphere-issues#259]
[Enter feedback here]

The "Sample: External MCU update - reference solution" is a dead link.
Looking at the URL for the link, it looks like the repo was updated, but the link wasn't.
It looks like the new URL for the link should be https://github.com/Azure/azure-sphere-samples/tree/master/Samples/ExternalMcuUpdate instead of https://github.com/Azure/azure-sphere-samples/tree/master/Samples/ExternalMcuUpdateNrf52

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8d7748-ebda-bfb3-ab25-02d3943f2935
* Version Independent ID: 540f019e-429a-deb6-c7da-cc7a3626c2ab
* Content: [Azure Sphere Applibs uart.h reference](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-uart/uart-overview)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-uart/uart-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-uart/uart-overview.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Hello @Omakas 
Thanks for the feedback! We are currently investigating and will update you shortly.
