### ISSUE TITLE
claim your device - link broken? 

### ISSUE THREAD

**Issue by chavakiran** [MicrosoftDocs/azure-sphere-issues#26]
https://docs.microsoft.com/en-us/azure-sphere/quickstart/claim-device

**Comment by matsujirushi** [comment]
Some URLs are changed.
Claim process is here.
https://docs.microsoft.com/en-us/azure-sphere/install/claim-device

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
