### ISSUE TITLE
Revise Picture

### ISSUE THREAD

**Issue by azsphere** [MicrosoftDocs/azure-sphere-issues#260]
![AzureSphereTenantCARenewal](https://user-images.githubusercontent.com/53162885/96562770-1e0a9280-12fc-11eb-85af-b9293e03efdc.png)

Hello,

I think that the picture should be revised 1) to show 'Active' & 'Inactive' status 2) move ~60days bar as attached for better understanding.

Thanks,

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3234b388-2251-0513-55b1-f380f27f4285
* Version Independent ID: 5e5ab326-6fac-5429-64b6-af1e1b070529
* Content: [Manage tenant CA certificates- Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/tenant-cert#renew-tenant-ca-certificate)
* Content Source: [AzureSphere/articles/deployment/tenant-cert.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/tenant-cert.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by asergaz** [comment]
Thank you so much for the great feedback @azsphere . I am assigning this issues to the content author @prabhushyja to evaluate and enhance the doc. Thanks again!

**Comment by ericawes** [comment]
Thank you for the feedback! We published a revised image yesterday that corrects the issue: [Configure tenant CA certificates for cloud services](https://docs.microsoft.com/azure-sphere/deployment/tenant-cert)

**Comment by azsphere** [comment]
Great thank you! @asergaz  @ericawes . I have read updates and clear for me now. 👍 Thanks again!
