### ISSUE TITLE
Link for "Next Step" is broken/missing

### ISSUE THREAD

**Issue by wickste** [MicrosoftDocs/azure-sphere-issues#261]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by YutongTie-MSFT** [comment]
@wickste 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YutongTie-MSFT** [comment]
@pennyo HI Penny, could you please update the document? I don't have the access for changing it. Thanks.
