### ISSUE TITLE
Issue with AzureSphereBlink1 Sample

### ISSUE THREAD

**Issue by egionet** [MicrosoftDocs/azure-sphere-issues#263]
[Enter feedback here]
I just received my Seeed MDB, updated the device OS (20.09) and Visual Studio is running 20.09 as well, the device was claimed and connected over WiFi.  When I uploaded the sample AzureSphereBlink1 program the LED didn't blink until the code was modified:

while (true) {
        GPIO_SetValue(fd, GPIO_Value_Low);
        nanosleep(&sleepTime, NULL);
        GPIO_SetValue(fd, GPIO_Value_High);
        Log_Debug("\nGPIO->GPIO_Value_High.\n");
        nanosleep(&sleepTime, NULL);
    }

If the "Log_Debug" line is removed the LED stops blinking.  I am trialling other sample code before starting my project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56bb629c-a1b1-a305-67c7-eaf46cfc3c8b
* Version Independent ID: ff97f9a2-cbd7-89bc-3837-f81952d15833
* Content: [Build your first Azure Sphere application tutorial](https://docs.microsoft.com/en-us/azure-sphere/install/qs-blink-application?tabs=windows&pivots=visual-studio)
* Content Source: [AzureSphere/articles/install/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Hello @egionet 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @egionet Just checking back on this. While we check with our team. Please confirm if you still see the same issue?

Please let us know if you need further help in this matter.

**Comment by egionet** [comment]
Thanks for following up.  I had the wrong board referenced (i.e. seeed_mt3620_mdb instead of mt3620_rdb).  Once the change was made the original code worked.  I discovered this by attempting to communicate with an SHT31 over I2C.  I reused the "I2C_LSM6DS3_HighLevelApp" and updated the code for a basic temperature and humidity request but not having any luck.  The SHT31 was confirmed to be operational by interfacing it with an Arduino board I have kicking around.  Is there a recommended forum for the mt3620_rdb?

**Comment by SatishBoddu-MSFT** [comment]
Hello @egionet Thanks for confirmation on issue resolution from your side.

*  Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft to ask your further technical questions.
* We do have lot of interesting projects posted on [Hackster.io](https://www.hackster.io/search?i=projects&q=azure%20sphere)

Please do let us know if you have any feedbacks or concerns, we are always happy to help you.
