### ISSUE TITLE
Document is not clear about how to manually install appdevelopment capability and remove it later

### ISSUE THREAD

**Issue by xiongyu0523** [MicrosoftDocs/azure-sphere-issues#264]
We have no description to guide a customer how to do this. Not all customer want install gdb and other configuration in 'azsphere dev edv' command

1. No description for update command, people don't know they should use 'select' or 'update' command to apply to a device.
2. No description for none capability, which is used for removing capability..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e115a46-a0f3-7791-5202-ed3b66fc7a4b
* Version Independent ID: 21027aca-4cfa-efdb-e292-d53c0ada9ee7
* Content: [Device capabilities and servicing sessions - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/device-capabilities)
* Content Source: [AzureSphere/articles/app-development/device-capabilities.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/device-capabilities.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by BharathNimmala-MSFT** [comment]
@xiongyu0523 Thanks a lot for your feedback, our team will review and get back to you at the earliest.

**Comment by SatishBoddu-MSFT** [comment]
Hello @xiongyu0523 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @xiongyu0523 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by pennyo** [comment]
@xiongyu0523 Hi Neo-- 
Our general guidance for customers is to use the combined commands (enable-development and enable-cloud-test), as described in [Device capabilities and communication](https://docs.microsoft.com/azure-sphere/app-development/device-capabilities).  

We'll more clearly link this to the [azsphere device capability](https://docs.microsoft.com/azure-sphere/reference/azsphere-device#capability-cap) reference for those who want to use the individual commands. The reference describes how to use all the individual commands, what --none does, etc.

**Comment by xiongyu0523** [comment]
OK, the first thing come to my mind is to find in 'capability' section of our document, not the reference page. The page you share do have more information. 

The 'capability' concept in azure sphere is totally new and nobody know what does it mean for the first time. I'm appreciate you can review this part thoughtfully. The most confuse thing is I never recall which command can be executed or not with certain capability, it's better to have a map table, column is different capability, row is each command.

**Comment by pennyo** [comment]
@xiongyu0523 Thank you for the clarification. We've added links in the updated 20.11 docs and will look at expanding this further for a future release.

**Comment by xiongyu0523** [comment]
Thanks @pennyo. We can close this.
