### ISSUE TITLE
Direct connection authentication instructions should call out lower-case device id clearer

### ISSUE THREAD

**Issue by markscott-slalom** [MicrosoftDocs/azure-sphere-issues#265]
[In Step 5, [here](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub?branch=release#authenticate-using-a-direct-connection) it's very easy to miss the fact that the device id must be in lower case. Can you please bold or underline or call that out better? When asking the device for its id with the command 'azsphere device list-attached', it is produced in upper case. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faedf864-4477-e53a-f711-0e5deaf3197b
* Version Independent ID: 416a2b64-8c07-f6bc-8393-307639bd9b3a
* Content: [Set up an Azure IoT Hub to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub?branch=release#authenticate-using-a-direct-connection)
* Content Source: [AzureSphere/articles/app-development/setup-iot-hub.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-hub.md)
* Product: **azure-sphere**
* GitHub Login: @LouisBerner
* Microsoft Alias: **azurespheredocs**

**Comment by LouisBerner** [comment]
Thank you for your feedback.

Created https://dev.azure.com/msazuresphere/4x4/_queries/edit/103252/?triage=true to track this issue.

**Comment by pennyo** [comment]
We've updated the docs today.
Closing this issue.
