### ISSUE TITLE
Misplaced sentence on configuring networking quick start page.

### ISSUE THREAD

**Issue by dtarditi** [MicrosoftDocs/azure-sphere-issues#266]
[Enter feedback here]
The following sentence appears to be in the wrong place on this page.  It is in the "Receive Device Update" section and should be in the "Set up Wifi" section:
```
The azsphere device wifi command supports several additional options. Type azsphere device wifi for a complete list, or azsphere device wifi option --help for help on an individual option.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db907e3-85a6-ab65-837b-7e6a5dc12224
* Version Independent ID: dfd84d21-060c-1ba2-6341-54ed7248ae23
* Content: [Configure networking and update device OS - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi)
* Content Source: [AzureSphere/articles/install/configure-wifi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/configure-wifi.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for the feedback, David. We'll check the text and modify if necessary.
