### ISSUE TITLE
ADC -> PWM

### ISSUE THREAD

**Issue by atKeitaroTakahashi** [MicrosoftDocs/azure-sphere-issues#268]
The pulse-width modulator (PWM) that is used by the application.
In a high-level application, specify the peripheral name that is declared in the hardware definition header file.
In an RTApp, specify the AppManifestValue that is declared in the hardware definition JSON file.
Hardware definition example: "Pwm": [ "$MT3620_RDB_LED_PWM_CONTROLLER2" ]
Raw value example: "Pwm": [ "PWM-CONTROLLER-0" ]
API reference: Applibs pwm.h
Conceptual: Using ADCs on Azure Sphere **←This**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb08dc5-0c1b-142f-c6cb-b8bba1d608c6
* Version Independent ID: 65cd99d0-6826-35ed-1bea-4842f35ab2f3
* Content: [Azure Sphere application manifest](https://docs.microsoft.com/en-us/azure-sphere/app-development/app-manifest)
* Content Source: [AzureSphere/articles/app-development/app-manifest.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/app-manifest.md)
* Product: **azure-sphere**
* GitHub Login: @DonnaHill007
* Microsoft Alias: **azurespheredocs**

**Comment by NavtejSaini-MSFT** [comment]
@atKeitaroTakahashi We are checking this and will get back to you.

**Comment by pennyo** [comment]
@atKeitaroTakahashi Thank you for the feedback. We'll fix this link in an upcoming docs release.

**Comment by pennyo** [comment]
We've updated the documentation. Closing this issue.
