### ISSUE TITLE
Can't connect using "direct connection" 

### ISSUE THREAD

**Issue by ericmitt** [MicrosoftDocs/azure-sphere-issues#269]
I followed the steps in the article but impossible to connect my devices via direct connection.
I gote the message:
  Azure IoT connection status: IOTHUB_CLIENT_CONNECTION_NO_NETWORK
    Azure IoT connection status: IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
    Azure IoT connection status: IOTHUB_CLIENT_CONNECTION_NO_NETWORK
    Azure IoT connection status: IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL

I redo all the steps twice but same result :-(

So I changed gears and  tried to follow the steps with DPS, **worked fine.**

Perhaps we need to revisit and validate the steps for "direct connection"

To reproduce, follow the steps in the article for "direct connection"

**Comment by ericmitt** [comment]
In the DPS approach, can I control the name of the device (it appear with a very long Unique ID) ?

**Comment by ericmitt** [comment]
To be able to see telemetry in iotexploer or from Azure CLI, I have to create a new consumergroup.... Why ?

**Comment by HarshitaSingh-MSFT** [comment]
Hello @ericmitt , thank you for reaching out to us! Could you please share the link of the MS Doc you are referring to here?

**Comment by HarshitaSingh-MSFT** [comment]
Just checking in to see if you could provide an associated doc link for this issue.

**Comment by HarshitaSingh-MSFT** [comment]
Just checking in to see if you could provide an associated doc link for this issue.

**Comment by HarshitaSingh-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
