### ISSUE TITLE
How to add a hotel WiFi network to Azure Sphere device for on-the-road Azure Sphere development? 

### ISSUE THREAD

**Issue by baatkarlo** [MicrosoftDocs/azure-sphere-issues#27]
I'm working on the road with Azure Sphere Dev kit, and have run into an issue in configuring Azure Sphere wifi: Hotel networks typically require a web browser to fill in hotel wifi related info. How to enable this for Azure Sphere so I can receive OTA OS updates? I travel a lot and need to be able to continue my dev efforts while on the road. Having a WiFi config approach that allows this would be tremendously valuable, given that IoT solutions involve a lot of on-the-road efforts in device placement and trials. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8b72a7-de1a-9d94-acc9-e1e3936ee587
* Version Independent ID: 21dae1e6-308a-4c55-dfe5-7f380dc86f47
* Content: [Azure Sphere CLI device (dev) command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device#wifi)
* Content Source: [AzureSphere/articles/reference/azsphere-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@baatkarlo I apologize for the super late response. For Future Reference if you come across this issue via internet search. There is a request in User Voice for a solution to this problem https://feedback.azure.com/forums/915433-azure-sphere/suggestions/36123595-setup-wifi-in-field-using-wifi-access-point-instea please upvote so it gets prioritized or create a new entry with your idea.

**Comment by Alberto-Vega-MSFT** [comment]
@baatkarlo We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
