### ISSUE TITLE
Incorrect section title "XBOX Video Application Development"

### ISSUE THREAD

**Issue by sha1painkiller** [MicrosoftDocs/azure-sphere-issues#270]
[請在此輸入您的意見]
https://docs.microsoft.com/zh-tw/azure-sphere/
In the left pane, the "**XBOX Video** Application Development" should be "Application Development".

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: a0be310e-4cea-4cb7-3fad-578140c35e0a
* Version Independent ID: a61988d8-f1c9-e283-b071-5cc024c42ca1
* Content: [Azure Sphere 應用程式概觀](https://docs.microsoft.com/zh-tw/azure-sphere/app-development/applications-overview)
![azs-errata](https://user-images.githubusercontent.com/5663953/102715425-47ea3080-4310-11eb-82ef-9b66a2cf88ef.PNG)

* Content Source: [AzureSphere/articles/app-development/applications-overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.zh-TW/blob/live/AzureSphere/articles/app-development/applications-overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @sha1painkiller , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by AshokPeddakotla-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by pennyo** [comment]
@sha1painkiller Thank you for the feedback! This is a translation error; I've forwarded it to the localization team to address.

**Comment by ericawes** [comment]
Closing this issue since pennyo created a new issue in the zh-TW repo.
