### ISSUE TITLE
Section links not present on the "Quickstart: Install the AzureSphere SDK for Windows" page

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#271]
This is major nitpicking here, so take it with a grain of salt.  On the "Quickstart: Install the AzureSphere SDK for Windows" page the last two major headers don't provide links.  

To reproduce the issue . . . 

1. Open the page: [Link](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=vs-code)
2. Hove the mouse cursor over the major sections titles "Prerequisites", "Set up your dev kit on a Windows PC" or "Install the Azure Sphere SDK"
3. Notice that when the mouse hovers over these sections a clickable link icon appears to the left of the text, I use these links a lot in my Azure Sphere documentation and blogs, I like them!
4. Now hover the mouse over the last two major sections "Install CMake and Ninja on Windows" and "Install the Azure Sphere extension for Visual Studio Code"
5. The dynamic link icon does not appear

Again, I apologize for documenting such a minor issue.  My own best practice with issues is to document everything, then decide what to actually fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3859174a-d1d6-d10e-5fbf-8d83f8e0f150
* Version Independent ID: 93000ca6-7a4d-11da-27d0-ba7430e83d6a
* Content: [Set up a dev kit and install the Azure Sphere SDK for Windows](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk)
* Content Source: [AzureSphere/articles/install/install-sdk.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-sdk.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by SatishBoddu-MSFT** [comment]
Hello @bawilless 
Thanks for the feedback! We are currently investigating and will update you shortly

I see as below, Got it!
The Dynamic link is displayed! 
![image](https://user-images.githubusercontent.com/62923178/106333015-b1792b00-623c-11eb-8757-85985054ed49.png)

**No Dynamic link is displayed! we are looking into the last 2 sections!!!**
![image](https://user-images.githubusercontent.com/62923178/106333070-cd7ccc80-623c-11eb-8019-554eb2236076.png)

**Comment by SatishBoddu-MSFT** [comment]
Hello @bawilless 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by ericawes** [comment]
Hello, @bawilless 
Thanks for the feedback, Brian. Unfortunately there's no fix for this at present; it's a bug in the **Choose your development environment** toggle at the top of the page. You _can_ still right click and copy the links for those headings from the mini-TOC on the right rail.

Closing this issue, but we do appreciate the feedback!
