### ISSUE TITLE
Certificate download command has changed

### ISSUE THREAD

**Issue by OrrinEdenfield** [MicrosoftDocs/azure-sphere-issues#272]
Documentation lists this command to use to download certificate:
`azsphere ca-certificate download --output CAcertificate.cer`

This is the command that worked with the latest version of Azure Sphere:
`azsphere ca-certificate download --destination-file CAcertificate.cer`

Please update. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79eb45a2-0b0c-6449-5acc-504fb16583e6
* Version Independent ID: fa9be175-df4d-a165-144f-8abe62ecb7ea
* Content: [Set up Azure IoT Central to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-central?source=docs#step-2-download-the-tenant-authentication-ca-certificate)
* Content Source: [AzureSphere/articles/app-development/setup-iot-central.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-central.md)
* Product: **azure-sphere**
* GitHub Login: @LouisBerner
* Microsoft Alias: **azurespheredocs**

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @OrrinEdenfield, 
Thank you for your feedback! We will review and update as appropriate.

**Comment by asergaz** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by prabhushyja** [comment]
Thank you for your feedback! The [azsphere reference documentation](https://docs.microsoft.com/en-us/azure-sphere/reference/overview) has been updated to include details of available parameters and examples for both versions. Examples elsewhere in the documentation still reflect the original CLI v1. 

We will update the examples in a future release. Our general guidance for customers using CLI v2 is documented in [Azure Sphere CLI v2 Beta](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-cli-v2?tabs=cliv1).

**Comment by prabhushyja** [comment]
We've updated the documentation to include the correct information. Thanks for your feedback!

Please consider closing this issue.
