### ISSUE TITLE
Additional items for this page related to VPNs and their interference with the Azure Sphere TAP driver

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#273]
We have run into multiple issues with our corporate VPN and the VPN settings that prevent communications with Azure Sphere devices on Windows 10 development computers.  These would be good topics to add to this troubleshooting page. 

1. The customers VPN does not allow "split tunneling."  If split tunneling is disabled by the VPN configuration and the development computer is connected to the corporate VPN, then communications to the Azure Sphere device is broken.

There are two ways to resolve this issue . . .

- Disconnect from the VPN and try the connection to the Azure Sphere device again (if split tunneling is turned off, this resolves the issue)
- Change the VPN configuration to allow split tunneling 

2. The TAP driver may install with default settings (VPN related) that prevent communications to the Azure Sphere device.  See the detailed instructions below to resolve this issue.

- Make sure you have Admin Rights on your computer
- Open your Windows 10 “Settings” and select the “Network and Internet” group
- Under “Change your network settings” select “Change adapter options”
- On the “Azure Sphere TAP-Windows Adapter V9” adapter, right-click and select “Properties”
- On the “Networking” tab locate the “Cisco AnyConnect Network Access Manager Filter Driver” entry, unselect the check box
- Click on “OK” to save and exit
- At the Azure Sphere SDK command-prompt, check that communication with your Azure Sphere device is now working by entering azsphere device show-attached 

![image](https://user-images.githubusercontent.com/41625691/108894996-02ccce00-75e1-11eb-9dc4-030e3cd227f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Troubleshoot for Azure Sphere installation and setup](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @v-annene
* Microsoft Alias: **azurespheredocs**

**Comment by v-annene** [comment]
Thank you for your feedback. We will fix this in an upcoming release of the documentation.

**Comment by AshokPeddakotla-MSFT** [comment]
@v-annene Closing this as you have mentioned, it is planned for next release.
