### ISSUE TITLE
VS Code CMake ToolChain Error for Azure Sphere

### ISSUE THREAD

**Issue by nishithvpoojary** [MicrosoftDocs/azure-sphere-issues#274]
**Hello. I have been trying to use VS Code for programming Azure sphere Board. But I have an error while I build it.**

[main] Configuring folder: HelloWorld_HighLevelApp 
[driver] Removing c:/Azure Work/azure-sphere-samples/Samples/HelloWorld/HelloWorld_HighLevelApp/out/ARM-Debug/CMakeCache.txt
[driver] Removing c:\Azure Work\azure-sphere-samples\Samples\HelloWorld\HelloWorld_HighLevelApp\out\ARM-Debug\CMakeFiles
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli "-DCMAKE_TOOLCHAIN_FILE:STRING=C:\Program Files (x86)\Microsoft Azure Sphere SDK\/CMakeFiles/AzureSphereToolchain.cmake" -DAZURE_SPHERE_TARGET_API_SET:STRING=latest-lts -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug "-Hc:/Azure Work/azure-sphere-samples/Samples/HelloWorld/HelloWorld_HighLevelApp" "-Bc:/Azure Work/azure-sphere-samples/Samples/HelloWorld/HelloWorld_HighLevelApp/out/ARM-Debug" -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Auto-selected latest LTS API set "8"
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Azure Work/azure-sphere-samples/Samples/HelloWorld/HelloWorld_HighLevelApp/out/ARM-Debug/CMakeFiles/CMakeOutput.log".

**This is my path in Environmental Variables**

![image](https://user-images.githubusercontent.com/45986919/111941278-b3ea5980-8af6-11eb-988b-908abcbb3be4.png)

**Below pic is my System Variable with Variable Name "Path"**

![image](https://user-images.githubusercontent.com/45986919/111941387-f57b0480-8af6-11eb-9a01-73cd973c7fd8.png)
 

**This is my Ninja path in PC**
![image](https://user-images.githubusercontent.com/45986919/111941577-573b6e80-8af7-11eb-8d21-920bd115d1e7.png)

**This is my CMake path in PC**
![image](https://user-images.githubusercontent.com/45986919/111941624-70dcb600-8af7-11eb-9c40-3f775810af8a.png)

**My CMakeLists.txt**

cmake_minimum_required(VERSION 3.10)

project(HelloWorld_HighLevelApp C)

azsphere_configure_tools(TOOLS_REVISION "21.01")
azsphere_configure_api(TARGET_API_SET "8")

add_executable(${PROJECT_NAME} main.c)
target_link_libraries(${PROJECT_NAME} applibs gcc_s c)

set(TARGET_HARDWARE "mt3620_rdb")
set(TARGET_DEFINITION "sample_appliance.json")

find_path(
    TARGET_DIRECTORY
    NAMES ${TARGET_DEFINITION}
    PATHS "HardwareDefinitions/${TARGET_HARDWARE}" "../../../HardwareDefinitions/${TARGET_HARDWARE}"
    NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)

azsphere_target_hardware_definition(${PROJECT_NAME} TARGET_DIRECTORY "${TARGET_DIRECTORY}" TARGET_DEFINITION "${TARGET_DEFINITION}")

azsphere_target_add_image_package(${PROJECT_NAME})

**My CMakeSettings.json**

{
  "environments": [
    {
      "environment": "AzureSphere"
    }
  ],
  "configurations": [
    {
      "name": "ARM-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "AzureSphere"
      ],
      "buildRoot": "${projectDir}\\out\\${name}",
      "installRoot": "${projectDir}\\install\\${name}",
      "cmakeToolchain": "${env.AzureSphereDefaultSDKDir}CMakeFiles\\AzureSphereToolchain.cmake",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "AZURE_SPHERE_TARGET_API_SET",
          "value": "latest-lts"
        }
      ]
    },
    {
      "name": "ARM-Release",
      "generator": "Ninja",
      "configurationType": "Release",
      "inheritEnvironments": [
        "AzureSphere"
      ],
      "buildRoot": "${projectDir}\\out\\${name}",
      "installRoot": "${projectDir}\\install\\${name}",
      "cmakeToolchain": "${env.AzureSphereDefaultSDKDir}CMakeFiles\\AzureSphereToolchain.cmake",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "AZURE_SPHERE_TARGET_API_SET",
          "value": "latest-lts"
        }
      ]
    }
  ]
}

**How can I remove this error?  Thank you.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3859174a-d1d6-d10e-5fbf-8d83f8e0f150
* Version Independent ID: 93000ca6-7a4d-11da-27d0-ba7430e83d6a
* Content: [Set up a dev kit and install the Azure Sphere SDK for Windows](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=vs-code)
* Content Source: [AzureSphere/articles/install/install-sdk.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-sdk.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by nishithvpoojary** [comment]
[https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=vs-code](url)
I was using this above link to install Azure SDK , CMake and Ninja.

**Comment by AshokPeddakotla-MSFT** [comment]
@nishithvpoojary Did you check the [troubleshooting guide](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#cannot-compile-or-debug-rtapps)? 

![image](https://user-images.githubusercontent.com/44426435/112255539-69004b80-8c88-11eb-9933-bed97da0d81c.png)

**Comment by chandran-Az** [comment]
@nishithvpoojary - In the PATH screenshot, I do not see Ninja's path added to the environment variables. Can you add the path and try reloading the VS Code application again?
Link - 
![image](https://user-images.githubusercontent.com/64656870/112396582-a03d1f80-8cbd-11eb-911c-9495bb3350c2.png)


![image](https://user-images.githubusercontent.com/64656870/112396536-8ac7f580-8cbd-11eb-83c8-44d5e11a515b.png)

**Comment by nishithvpoojary** [comment]
> @nishithvpoojary Did you check the [troubleshooting guide](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#cannot-compile-or-debug-rtapps)?
> 
> ![image](https://user-images.githubusercontent.com/44426435/112255539-69004b80-8c88-11eb-9933-bed97da0d81c.png)

I used High Level Application.

**Comment by nishithvpoojary** [comment]
> @nishithvpoojary - In the PATH screenshot, I do not see Ninja's path added to the environment variables. Can you add the path and try reloading the VS Code application again?
> Link - https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=vs-code#install-cmake-and-ninja-on-windows
> 
> ![image](https://user-images.githubusercontent.com/64656870/112396536-8ac7f580-8cbd-11eb-83c8-44d5e11a515b.png)

I had added it. Check the first image. In System variables with variable name "Ninja".

**Comment by AshokPeddakotla-MSFT** [comment]
@nishithvpoojary There are no issues with the documentation. I can confirm that it works as expected. 

> CMake Error: CMake was unable to find a build program corresponding to "Ninja". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool

As per the error CMAKE_MAKE_PROGRAM is not set. I suggest you, kindly remove the existing paths and do a fresh install again.

Also, if you face issues again, please post your query on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-sphere.html) and we will happily continue the conversation. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
