### ISSUE TITLE
Azure Device Update Service to update Azure Sphere Device

### ISSUE THREAD

**Issue by jeevannagvekar** [MicrosoftDocs/azure-sphere-issues#276]
Hi there,
Is Azure Sphere device/firmware update possible using Azure Device Update Service (ADU) at Azure IoT Hub. Or the firmware and device update has to be happened only via Azure Sphere Security Service?
If possible via ADU, what is the procedure? An ADU example for Simulated device/Raspberry Pi is available. But not for Azure Sphere.
If no, please explain reasons in detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13b5723-67c1-ebd8-5ae1-3c76f94cd5d3
* Version Independent ID: 14bd3533-ecd2-c30c-9132-d78bd8ca7ea1
* Content: [Deployment basics - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/deployment-concepts)
* Content Source: [AzureSphere/articles/deployment/deployment-concepts.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/deployment-concepts.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by SwathiDhanwada-MSFT** [comment]
@jeevannagvekar Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@jeevannagvekar At this time, Azure Sphere uses different update control and update delivery mechanisms to ADU, though we are looking at the value a more unified experience would bring for our customers and we welcome your input on this.  Azure Sphere has some unique product qualities which lead to a difference in design:

-	Microsoft provides periodic and automatic OS updates (no action required by OEM) while enabling OEMs to update their own apps.
-	While most Azure Sphere customers use Azure IoT Hub and device twins, this is not a prerequisite for using Azure Sphere.
We are exploring how we can provide a single management experience to monitor Sphere and other IoT devices, even though the channels to update them remain separate. If there are specific experiences or gaps you would like to see addressed, please let us know so we can factor them in our design.

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
