### ISSUE TITLE
Device claim process in production for customer

### ISSUE THREAD

**Issue by jeevannagvekar** [MicrosoftDocs/azure-sphere-issues#277]
Hello,
Azure sphere documentation discusses about all procedures like claiming a device, retrieving certificates etc in development environment where VS(code), Azure SPhere SDK etc is setup. 
Lets assume a scenario where a sphere device is shipped to a customer. The customer is not techno savvy and doesn't understand setup process or don't want to do technical stuff. In that case, what are the ways available which can make life easier for end customer in order to do device claim, provisioning etc? Something like, device being configured (claimed, wifi settings etc) via a mobile app connected to device or any other means).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device?tabs=cliv2beta)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @LouisBerner
* Microsoft Alias: **azurespheredocs**

**Comment by BryanTrach-MSFT** [comment]
@jeevannagvekar Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @jeevannagvekar Thanks for the query on "How-To" on this page.

Could you please post this "How-To"  question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-sphere.html) with tag called **azure-sphere** Technical forum, where there is a community that can help (plus the engineering team).

Please let me know if we are good to close this issue over here.

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
