### ISSUE TITLE
Highlight note regarding using lowercase Device Id when adding Device in IoT Hub

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/azure-sphere-issues#278]
For Step 5. bullet item 3.
https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub?tabs=cliv2beta#step-5-create-an-x509-device-for-your-iot-hub 

The _azsphere device show-attached_ command outputs the Device Id in UPPERCASE. The IoT Hub expects the Device Id in lowercase 🙄

The "Note" in this step is extremely easy to miss and a lot of wasted hours can be saved by either highlighting the text in bold or adding this in a Note section below the step. 

Or someone from the Product team should fix either the Sphere SDK or the portal. For some inexplicable reason this caveat is not available as a tooltip in the IoT Hub Device add page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faedf864-4477-e53a-f711-0e5deaf3197b
* Version Independent ID: 416a2b64-8c07-f6bc-8393-307639bd9b3a
* Content: [Set up an Azure IoT Hub to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub?tabs=cliv2beta#authenticate-using-a-direct-connection)
* Content Source: [AzureSphere/articles/app-development/setup-iot-hub.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-hub.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@laughingman42 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@laughingman42 PR has been created to highlight the text. Changes will go live once it has been peer reviewed and merged.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by ericawes** [comment]
This change is now live: https://docs.microsoft.com/azure-sphere/app-development/setup-iot-hub
