### ISSUE TITLE
typo in function name

### ISSUE THREAD

**Issue by Omakas** [MicrosoftDocs/azure-sphere-issues#279]
There seems to be a typo in the function  prototype.
On the page it is listed as 
`int Networking_TimeSync_EnableCustomNTP(const char *primaryNtpServer, const char *secondaryNtpServer, Networking_NtpOption option);`

But it should be 
`int Networking_TimeSync_EnableCustomNtp(const char *primaryNtpServer, const char *secondaryNtpServer,                                  
 Networking_NtpOption option);`

This is not a major issue, but the "NTP" should be "Ntp"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 252e20d6-5fd7-bc7d-dacd-ed100234a649
* Version Independent ID: 1ee3e341-1220-dfd0-bf31-16c73555fdee
* Content: [Networking_TimeSync_GetCustomNTP function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-networking/function-networking-timesync-enablecustomntp)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-timesync-enablecustomntp.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-timesync-enablecustomntp.md)
* Product: **azure-sphere**
* GitHub Login: @DonnaHill007
* Microsoft Alias: **azurespheredocs**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Omakas  Thanks for your contribution, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/pull/266](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/pull/266) 
The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.

@DonnaHill007 Could you please review and approve the pull request?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Omakas This has been fixed.

![image](https://user-images.githubusercontent.com/79183421/116970547-d2d33280-acd5-11eb-950d-bdaefaeba235.png)
