### ISSUE TITLE
Missing Features for MT3620, 2 x ARM Cortex-M4 with FPU

### ISSUE THREAD

**Issue by residentx10** [MicrosoftDocs/azure-sphere-issues#28]
When will this be supported on the device, US version (SKU:102991012)?

**Comment by sergaz-msft** [comment]
@residentx10 sorry the delay answering your question. Please see [here](https://social.msdn.microsoft.com/Forums/en-US/001edc81-7236-4035-b7da-bcd0d910adca/mt3620-arm-cortexm4f-support-when?forum=azuresphere) a related question on MSDN. We will follow-up on that thread when we have more details. You can also reach us by email so we can update you.

Thanks!
