### ISSUE TITLE
High Level code UART timer

### ISSUE THREAD

**Issue by nishithvpoojary** [MicrosoftDocs/azure-sphere-issues#280]
Hi, 
I use Avnet Starter kit Rev 2 board.
This is the code I used to receive UART data,
![image](https://user-images.githubusercontent.com/45986919/116790210-be721880-aad0-11eb-9250-963b4068a535.png)

Here the UART is continuously checked to get the data from it. 
Is it possible to set the time to check the UART port [ Lets say, I have to check the UART port every 10 seconds ] without using the timer. What is the easiest way to do that?
Thank you.

**Comment by SaurabhSharma-MSFT** [comment]
@nishithvpoojary To assist you better on your query could you provide us with the link to the document you are referring to ?
In case your query in not related to document content, open a new forum thread either Microsoft Q&A or StackOverflow as it could be better place to get help on your scenario where the community members could provide their expert guidance to you based on their experience.

**Comment by nishithvpoojary** [comment]
Hello @SaurabhSharma-MSFT  Thank you for your response.
I used the HLApp sample code from this link [https://github.com/Azure/azure-sphere-samples/tree/master/Samples/UART/UART_HighLevelApp](url)

and also used the UART functions provided in this link to receive more data [https://github.com/MicrosoftDocs/azure-sphere-issues/issues/36](url)
I use Avnet starter kit rev 2 board.
Thank you

**Comment by nishithvpoojary** [comment]
What would be the best method to receive all the incoming data from the UART without buffer limitation (without setting the receiving buffer size ).  With the current UART sample implementation of event loop, I can receive only 12 bytes of data. I want to stream all the incoming data to hub without any breaking of data. Can you please suggest

**Comment by SatishBoddu-MSFT** [comment]
Hello @nishithvpoojary May we know the Github Document which you have followed ? the previous links which you have provided are not the right ones. Thanks for the understanding!

**Comment by nishithvpoojary** [comment]
These are the links,
[https://github.com/Azure/azure-sphere-samples/tree/master/Samples/UART/UART_HighLevelApp](url)
[https://github.com/MicrosoftDocs/azure-sphere-issues/issues/36](url)

**Comment by SatishBoddu-MSFT** [comment]
Hello @nishithvpoojary Sorry the links are not the expected ones's I believe.

Please repost your Technical query on the Microsoft Q&A forum with the tag '**azure-sphere**' and we will help you over there.

![image](https://user-images.githubusercontent.com/62923178/116972386-c87e4d80-ac6f-11eb-9f81-80183fd7c8bd.png)

As we are unable to link with any Github-related document or tutorial meta-data, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

**Comment by nishithvpoojary** [comment]
I dont understand why it's happening. I googled search the sample and copied the link.

**Comment by SatishBoddu-MSFT** [comment]
No worries, please post your query on Microsoft Q&A, we will make sure your query is addressed!
