### ISSUE TITLE
Queries - OTA Update

### ISSUE THREAD

**Issue by jeevannagvekar** [MicrosoftDocs/azure-sphere-issues#283]
Hello team,

Some questions about OTA:

1. Update check is at regular interval of 24 hours - Does this interval start after the azure sphere device boots?
2. I understand that if at next interval the sphere device finds new update, the system events reach the application as well (if the application is subscribed to these events). The current application should have chance to finish its current tasks.
3. Is the 24 hour interval configurable? Who controls this interval?
4. Any plan to notify azure sphere device about new updates as soon as they are uploaded to AS3, instead of waiting for next turn? 
5. Are there any APIs which can poll to check if new updates are available? If devices finds about updates, it may complete what it is currently doing and may be do a reboot using PowerManagement_ForceSystemReboot()
 

Regards,
Jeevan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27eb2d58-255d-c025-f2dc-e3f17a5cc077
* Version Independent ID: 93a49d69-59b4-35e6-b44f-7590e75610a5
* Content: [Over-the-air updates - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/device-updates)
* Content Source: [AzureSphere/articles/deployment/device-updates.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/device-updates.md)
* Product: **azure-sphere**
* GitHub Login: @richcalaway
* Microsoft Alias: **azurespheredocs**

**Comment by AjayKumar-MSFT** [comment]
@jeevannagvekar, Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by bawilless** [comment]
@jeevannagvekar,

This morning I published a blog that address' some of your questions: 
 https://www.element14.com/community/groups/azuresphere/blog/2021/06/14/azure-sphere-example-application-to-defer-ota-updates-until-a-specific-time-of-day

Brian

**Comment by AshokPeddakotla-MSFT** [comment]
@bawilless Thanks for sharing the blogpost. 
@jeevannagvekar We hope that address your queries. Do let us know if you have any other queries. 

Also, if you have a product-related question, please post to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/) and we will happily continue the conversation.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
