### ISSUE TITLE
Error on SDK installation

### ISSUE THREAD

**Issue by any-sliv** [MicrosoftDocs/azure-sphere-issues#284]
Installing SDK on Linux Ubuntu 20.04 LTS running on Raspberry Pi 3B+ stops with an error:

> ERROR: There was an error extracting the toolchain from '/opt/azurespheresdk/Sysroots/7/tools/exp23-appsdk-linux-blanca.sh'.

Issue was mentioned [here](https://github.com/MicrosoftDocs/azure-sphere-issues/issues/196) with a similar case, but author was running older version of Linux (probably Raspbian).
Details about my OS:
Distributor ID: Ubuntu
Descriptor: Ubuntu 20.04.2 LTS
Release: 20.04
Architecture: x64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d74497-55b9-cf91-47a3-13126cd0e79f
* Version Independent ID: 3ecce7c5-23ab-ff8a-dc4c-35b3044f0d96
* Content: [Install the Azure Sphere SDK for Linux](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux?pivots=vs-code-linux)
* Content Source: [AzureSphere/articles/install/install-sdk-linux.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install-sdk-linux.md)
* Product: **azure-sphere**
* GitHub Login: @richcalaway
* Microsoft Alias: **azurespheredocs**

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by AshokPeddakotla-MSFT** [comment]
@any-sliv Apologies for the delay in response. We have further verified with our team and below is an update.

> Currently, only **intel** architectures are supported and raspberry is based on **ARM** architecture. Installing on raspberry devices or other architectures is not tested and unsupported. 

Also, we will update our documentation with more clarity to clear any confusion around SDK installations. 

Thanks for your understanding. Please let us know if you have any other queries.

**Comment by any-sliv** [comment]
Much thanks for a reply, clarifying that on docs page will save others time.
