### ISSUE TITLE
Token generated with this method seems invalid

### ISSUE THREAD

**Issue by sw-ms-imranbhadelia** [MicrosoftDocs/azure-sphere-issues#285]
We follow same steps to get token. and after fixing some issue mentioned in this page we got token. But its not valid. We used https://jwt.ms/ to verify token but it gives InvalidTokenError

Moreover if we use same token to call API given at https://docs.microsoft.com/en-us/rest/api/azure-sphere/, it keep giving 400 bad request. So seems like Token is not valid

Also **azsphere register-user --new-user** doesnt work; we got it working with **azsphere register-user --newuser**

Any resolution on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58c8ccd-a024-de57-fcd1-44ab8be98b65
* Version Independent ID: 1c9257b5-0694-9a08-7130-72029bdd6a78
* Content: [Authentication Method - service principal](https://docs.microsoft.com/en-us/azure-sphere/deployment/authenticate-service-principal)
* Content Source: [AzureSphere/articles/deployment/authenticate-service-principal.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/authenticate-service-principal.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@sw-ms-imranbhadelia Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@sw-ms-imranbhadelia Which authentication method are you using? client secret or client cert method?
Looks like you are using old CLI. Please use the [latest version](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-register-user?tabs=cliv2beta) and try again.

**Comment by bawilless** [comment]
@sw-ms-imranbhadelia to get the latest CLI, you need to download and install the latest Azure  Sphere SDK, you can download the installer here:  https://aka.ms/AzureSphereSDKDownload/Windows

**Comment by AshokPeddakotla-MSFT** [comment]
@sw-ms-imranbhadelia As suggested please use the latest CLI and update. Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
