### ISSUE TITLE
SDK Installation Problem

### ISSUE THREAD

**Issue by Dmilner1** [MicrosoftDocs/azure-sphere-issues#287]
The SDK will not install and rolls after around 50% progress. I have tried all of the troubleshooting advice to no avail. The Powershell solution is not viable as the "%ProgramData%\Microsoft\Azure Sphere\TapDriverInstaller\TapDriverInstaller.ps1" file is not present at this location. 

I now have 8x Sphere's that I cannot use and my company are now growing impatient of my IoT progress - if you cannot support I will be forced to change platform as there does not appear any help/support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Troubleshoot for Azure Sphere installation and setup](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#windows-specific-problems)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by chandran-Az** [comment]
Hi Dmilner1 - Sorry to hear that you are having issues with Azure Sphere SDK installation. Could you please follow the below steps and share an update.
1. Follow the SDK installation troubleshooting guide - https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation#windows-specific-problems
2. If the issue still persists, run the following commands as an administrator.

- - _Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, Size, InstallDate | Export-csv -path c:\ShellOut64.csv_
- - _Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | sort-object -property DisplayName | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Export-csv -path c:\shellout32.csv_

3. Copy the *_TapDriverInstaller.Log files from c:\users\<<Username>>\AppData\Local\Temp. Replace the Username with your alias/username. Please send the above logs to chandran@microsoft.com.

Looking forward to hearing from you. Thanks!

**Comment by SatishBoddu-MSFT** [comment]
Hello @Dmilner1 
I have assigned the issue to the content author for further review.

**Comment by SatishBoddu-MSFT** [comment]
Hello @Dmilner1 As we have not received any response, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

**Comment by SatishBoddu-MSFT** [comment]
Hello @chandran-Az Could you please respond on this issue, so that we keep the community updated!
