### ISSUE TITLE
VS Code changing how proposed api is used

### ISSUE THREAD

**Issue by isidorn** [MicrosoftDocs/azure-sphere-issues#289]
Hi VS Code PM here 👋 

We are changing how proposed API in VS Code can be used. The gist is that `enableProposedApi` has been replaced with `enabledApiProposals: […]` and that `vscode.proposed.d.ts` has been replaced with a `dts`-file per proposal. This enables fine grained control and allows to scope proposals to selected extensions. You can read up on all the details here: https://github.com/microsoft/vscode/issues/131165

**Action required**: Follow the migration guide at https://github.com/microsoft/vscode/issues/136964 and update your extension timely. Find a sample adoption [here](https://github.com/microsoft/vscode-anycode/commit/cf73d4de8b0d6efca9da9212833be298568fc3ea) or [here](https://github.com/microsoft/vscode-github-issue-notebooks/commit/ad4ca50a61a7af0e5142c21865e876123906824b). Your extension should be updated in time for our Jan 2022 release (shipping early Feb 22), it is safe to make the changes immediately, also know that your extension stays backwards compatible.

Also note that for future use of different proposals you need to reach out to us. There is no more wildcard access to all proposals, instead proposals must be spelled out in our `product.json`-file. 

Let us know if you have any questions.

If the sphere extensions are no longer using proposed API just let me know and that is the best outcome actually

Thanks.

**Comment by shashishailaj** [comment]
@isidorn Thank you for your feedback .  This seems more like a product update request on our side due to a breaking change on your side . We will try to engage with the relevant team offline and will update .

**Comment by isidorn** [comment]
@shashishailaj thank you. I am also in an email thread with @robotdad

**Comment by AshokPeddakotla-MSFT** [comment]
@isidorn Thanks for letting us know that you are in contact with Marc.
Since this is not related to any specific doc and is more of a product update, we will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

Thank you
