### ISSUE TITLE
Missing Features for MT3620, Support for ADC, I2C, I2S, PWM and SPI peripheral interfaces

### ISSUE THREAD

**Issue by residentx10** [MicrosoftDocs/azure-sphere-issues#29]
When will this be supported on the device, US version (SKU:102991012)?

**Comment by AshokPeddakotla-MSFT** [comment]
@residentx10  Sorry for the delay. We have released new updates. Please check the [New features and changes](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1902#new-features-and-changes-in-the-1902-release) and let us know if you need further help on this one. You can also create a feedback item on the [UserVoice](https://feedback.azure.com/forums/915433-azure-sphere) and upvote.
