### ISSUE TITLE
Suggestion: add information about configuring proxy server to the page on what endpoints Sphere communicates with

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/azure-sphere-issues#290]
Suggestion:  add a pointer to documentation on configuring a proxy server [(here)](https://docs.microsoft.com/en-us/azure-sphere/network/connect-through-a-proxy) to this page, so network admins know of the alternate way to gate/grant access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02995860-63e0-47fa-91f8-35e7898116d1
* Version Independent ID: 39939a47-0efc-5632-11ad-05d1e91b4bde
* Content: [Azure Sphere OS networking requirements](https://review.docs.microsoft.com/en-us/azure-sphere/network/ports-protocols-domains?branch=CEV)
* Content Source: [AzureSphere/articles/network/ports-protocols-domains.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/CEV/AzureSphere/articles/network/ports-protocols-domains.md)
* Product: **azure-sphere**
* GitHub Login: @philkane
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@BarryBo Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ericawes** [comment]
Thanks for the feedback, @BarryBo. We'll update the documentation.
