### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by aholler2** [MicrosoftDocs/azure-sphere-issues#291]
Why does this page mention Azure Sphere doesn't support HTTP but then this other documentation page at, https://docs.microsoft.com/en-us/azure-sphere/app-development/curl, explicitly mentions support for HTTP/HTTPS requests to web services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0424ef6-7af2-6f41-8cd0-0532874529f4
* Version Independent ID: e0add64d-2983-3136-e8af-3f18653df1d8
* Content: [Azure Sphere IoT C SDK Library](https://docs.microsoft.com/en-us/azure-sphere/reference/iot-c-library)
* Content Source: [AzureSphere/articles/reference/iot-c-library.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/iot-c-library.md)
* Product: **azure-sphere**
* GitHub Login: @LouisBerner
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@aholler2 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
Adding author @LouisBerner to add more clarity on the doc. As it required validation before to update the doc.

**Comment by AshokPeddakotla-MSFT** [comment]
@chandran-Az Could you please help update the doc? Unable to assign to author.

**Comment by chandran-Az** [comment]
@aholler2 - Azure Sphere SDK only includes a subset of the IoT C SDK and this does not include HTTP support. MQTT is the preferred protocol here. For non IoT related functions, Azure Sphere SDK includes libcurl library which supports HTTP/HTTPS. HTH.

**Comment by AshokPeddakotla-MSFT** [comment]
@aholler2 We hope that address your question. Please let us know if you have any further queries.
