### ISSUE TITLE
Azure Sphere explorer, no tenant data

### ISSUE THREAD

**Issue by any-sliv** [MicrosoftDocs/azure-sphere-issues#292]
Hello,

I am using Visual Studio Code on a Linux machine to develop software for Azure Sphere devices. Since I manage many devices in tenant I belong to, some neat way to display devices and device-groups in tenant is necessary. That is what VSC extension - Azure Sphere and its UI should provide.
Unfortunately each attempt to load tenant data result in VSC prompt:
`The "file" argument must be of type string. Received undefined`

Devices section loads attached devices data correctly.

Can I get help here to fix it?

SDK: tried on 21.10 and updated to 22.02 - issue persists
OS: Ubuntu 20.04 LTS

**Comment by MonikaReddy-MSFT** [comment]
@any-sliv  - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update accordingly.

**Comment by any-sliv** [comment]
Just wanted to mention that issue is still valid. 
Some errors caught in VSC logs: 
`[2022-03-08 12:45:57.082] [renderer2] [critical] Extension 'ms-vscode.azure-sphere-tools-ui CANNOT USE these API proposals 'resolvers'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
` 
`[2022-03-08 12:45:59.185] [renderer2] [error] [Extension Host] (node:38478) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use code --trace-deprecation ... to show where the warning was created)
`
