### ISSUE TITLE
Hard to find conceptual documentation on device groups

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/azure-sphere-issues#294]
The link for "device groups" inside the sentence "The steps in this topic assume that you are familiar with the concepts of Azure Sphere [tenants](https://docs.microsoft.com/en-us/azure-sphere/deployment/manage-tenants), [products](https://docs.microsoft.com/en-us/azure-sphere/deployment/manage-products), and [device groups](https://docs.microsoft.com/en-us/azure-sphere/deployment/manage-device-groups)." takes me to a how-to page about how to manage device groups.  I expected it to take me to conceptual material about what a device group actually is.  The CLI docs at https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device-group?tabs=cliv2beta are better, at telling me what configuration options are available for a device group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3852d5e3-85a2-2f35-35c0-1f68315e44d4
* Version Independent ID: aeff4fde-94ea-e00e-b257-a8bfe755946f
* Content: [Manage Azure Sphere device groups](https://docs.microsoft.com/en-us/azure-sphere/deployment/manage-device-groups?tabs=cliv2beta&pivots=visual-studio)
* Content Source: [AzureSphere/articles/deployment/manage-device-groups.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/manage-device-groups.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@BarryBo Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by AshokPeddakotla-MSFT** [comment]
Doc has been updated with correct links.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
