### ISSUE TITLE
Broken link to Service principal authentication methods

### ISSUE THREAD

**Issue by esqew** [MicrosoftDocs/azure-sphere-issues#295]
Under the **Step 1: Register Service Principal** header, the third list item ("*Select authentication type*") is a broken link.

Clicking this link causes navigation to `https://docs.microsoft.com/en-us/azure-sphere/deployment/%5Cazure/active-directory/develop/howto-create-service-principal-portal#authentication-two-options`, which (as of this writing) results in `404 Not Found`.

It seems the link has been inadvertently created relative to the current page, when it should point instead on an *absolute* basis to `https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#authentication-two-options`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58c8ccd-a024-de57-fcd1-44ab8be98b65
* Version Independent ID: 1c9257b5-0694-9a08-7130-72029bdd6a78
* Content: [Authentication Method - service principal](https://docs.microsoft.com/en-us/azure-sphere/deployment/authenticate-service-principal)
* Content Source: [AzureSphere/articles/deployment/authenticate-service-principal.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/authenticate-service-principal.md)
* Product: **azure-sphere**
* GitHub Login: @prabhushyja
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@esqew Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@esqew PR has been created to fix the broken link. Fix will be deployed once it has been peer reviewed. 
Thanks again for pointing to the broken link and sharing the correct link.
