### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by any-sliv** [MicrosoftDocs/azure-sphere-issues#296]
End of the page link to 'delete mutable storage' redirects to function of 'opening mutable storage'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6e5e32a-18fa-2084-519c-66b31cefcbba
* Version Independent ID: 594664c5-a625-119d-4e7e-22c1df8eac3f
* Content: [Azure Sphere storage](https://docs.microsoft.com/en-us/azure-sphere/app-development/storage)
* Content Source: [AzureSphere/articles/app-development/storage.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/storage.md)
* Product: **azure-sphere**
* GitHub Login: @v-annene
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@any-sliv Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment]
@any-sliv The doc has been updated with correct link. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
