### ISSUE TITLE
AzureSphere with RS-485 in VSCode the RS-485 Demo.  trip.exe: Unable to recognise the format of the input file  build] ninja: build stopped: subcommand failed. [build] Build finished with exit code 1

### ISSUE THREAD

**Issue by mcousine** [MicrosoftDocs/azure-sphere-issues#299]
Trying to buid all project AzureSphere with RS-485 in VSCode the RS-485 Demo.  [https://github.com/Azure/azure-sphere-gallery/tree/main/RS485Driver](https://github.com/Azure/azure-sphere-gallery/tree/main/RS485Driver)

Install VSCode
Install Azure Sphere Extension
Install Azure SDK 
Install ninja 
Install cmake as describe here[https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=cli]( 
https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=cli)
Install ARM Toolchain  [Install Install the GNU Arm Embedded Toolchain] (https://docs.microsoft.com/en-us/azure-sphere/install/qs-real-time-application?tabs=windows%2Ccliv2beta&pivots=cli#install-the-gnu-arm-embedded-toolchain)

azsphere --version
22.07
cmake --version
cmake version 3.24.0-rc3
 gcc --version
gcc.exe (Rev3, Built by MSYS2 project) 12.1.0

Debug/approotRS-485_Driver_RealTimeApp/bin/app"
[build] D:\Applfich\MSYS2\mingw64\bin**\strip.exe: Unable to recognise the format of the input file** 

[main] Building folder: HLApp 
[build] Starting build
[proc] Executing command: D:\Applfich\cmake\bin\cmake.EXE --build d:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug --config Debug --target all -- -v
[build] [3/6  16% :: 0.215] C:\PROGRA~2\MI3C21~1\Sysroots\13\tools\gcc\ARFCD8~1.EXE -D_POSIX_C_SOURCE -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/usr/include" -B "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/tools/gcc" -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot="C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13" -g -std=c11 -Wstrict-prototypes -Wno-pointer-sign -ggdb -O0 -fPIC -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-omit-frame-pointer -fno-exceptions -Wall -Wswitch -Wempty-body -Wconversion -Wreturn-type -Wparentheses -Wno-format -Wuninitialized -Wunreachable-code -Wunused-function -Wunused-value -Wunused-variable -Werror=implicit-function-declaration -fstack-protector-strong -MD -MT CMakeFiles/RS_485_HighLevelApp.dir/eventloop_timer_utilities.c.obj -MF CMakeFiles\RS_485_HighLevelApp.dir\eventloop_timer_utilities.c.obj.d -o CMakeFiles/RS_485_HighLevelApp.dir/eventloop_timer_utilities.c.obj -c D:/Applfich/SOAP/training/RS485Driver/HLApp/eventloop_timer_utilities.c
[build] [3/6  33% :: 0.216] C:\PROGRA~2\MI3C21~1\Sysroots\13\tools\gcc\ARFCD8~1.EXE -D_POSIX_C_SOURCE -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/usr/include" -B "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/tools/gcc" -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot="C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13" -g -std=c11 -Wstrict-prototypes -Wno-pointer-sign -ggdb -O0 -fPIC -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-omit-frame-pointer -fno-exceptions -Wall -Wswitch -Wempty-body -Wconversion -Wreturn-type -Wparentheses -Wno-format -Wuninitialized -Wunreachable-code -Wunused-function -Wunused-value -Wunused-variable -Werror=implicit-function-declaration -fstack-protector-strong -MD -MT CMakeFiles/RS_485_HighLevelApp.dir/main.c.obj -MF CMakeFiles\RS_485_HighLevelApp.dir\main.c.obj.d -o CMakeFiles/RS_485_HighLevelApp.dir/main.c.obj -c D:/Applfich/SOAP/training/RS485Driver/HLApp/main.c
[build] [3/6  50% :: 0.217] C:\PROGRA~2\MI3C21~1\Sysroots\13\tools\gcc\ARFCD8~1.EXE -D_POSIX_C_SOURCE -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/usr/include" -B "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/tools/gcc" -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot="C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13" -g -std=c11 -Wstrict-prototypes -Wno-pointer-sign -ggdb -O0 -fPIC -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-omit-frame-pointer -fno-exceptions -Wall -Wswitch -Wempty-body -Wconversion -Wreturn-type -Wparentheses -Wno-format -Wuninitialized -Wunreachable-code -Wunused-function -Wunused-value -Wunused-variable -Werror=implicit-function-declaration -fstack-protector-strong -MD -MT CMakeFiles/RS_485_HighLevelApp.dir/rs485_hl_driver.c.obj -MF CMakeFiles\RS_485_HighLevelApp.dir\rs485_hl_driver.c.obj.d -o CMakeFiles/RS_485_HighLevelApp.dir/rs485_hl_driver.c.obj -c D:/Applfich/SOAP/training/RS485Driver/HLApp/rs485_hl_driver.c
[build] [4/6  66% :: 0.357] cmd.exe /C "cd . && C:\PROGRA~2\MI3C21~1\Sysroots\13\tools\gcc\ARFCD8~1.EXE -B "C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13/tools/gcc" -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot="C:/Program Files (x86)/Microsoft Azure Sphere SDK/Sysroots/13" -g -nodefaultlibs -pie -Wl,--no-undefined -Wl,--gc-sections CMakeFiles/RS_485_HighLevelApp.dir/main.c.obj CMakeFiles/RS_485_HighLevelApp.dir/eventloop_timer_utilities.c.obj CMakeFiles/RS_485_HighLevelApp.dir/rs485_hl_driver.c.obj -o RS_485_HighLevelApp.out  -lapplibs  -lgcc_s  -lc && cd ."
[build] [5/6  83% :: 0.455] cmd.exe /C "cd /D D:\Applfich\SOAP\training\RS485Driver\HLApp\out\ARM-Debug && C:\LOCAL\Applfich\cmake\bin\cmake.exe -E make_directory D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/approotRS_485_HighLevelApp/bin && C:\LOCAL\Applfich\cmake\bin\cmake.exe -E copy D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/RS_485_HighLevelApp.out D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/approotRS_485_HighLevelApp/bin/app && "C:\Program Files (x86)\Microsoft Azure Sphere SDK\Sysroots\13\tools\gcc\arm-poky-linux-musleabi-strip.exe" --strip-unneeded D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/approotRS_485_HighLevelApp/bin/app"
[build] [6/6 100% :: 2.213] cmd.exe /C "cd /D D:\Applfich\SOAP\training\RS485Driver\HLApp\out\ARM-Debug && "C:\Program Files (x86)\Microsoft Azure Sphere SDK\Tools_v2\wbin\azsphere.cmd" image-package pack-application --verbose --application-manifest D:/Applfich/SOAP/training/RS485Driver/HLApp/app_manifest.json --package-directory D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/approotRS_485_HighLevelApp --destination D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/RS_485_HighLevelApp.imagepackage --target-api-set "13" --hardware-definitions "D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit,C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/" --target-definition-filename q200_devkit.json"
[build] INFO: Azure Sphere Utility version 22.7.4.18756
[build] INFO: Copyright (C) Microsoft Corporation. All rights reserved.
[build] INFO: 
[build] INFO: Start time (UTC): Wednesday, 17 August 2022 12:18:17
[build] INFO: Creating image package.
[build] INFO: Azure Sphere application image package written.
[build] INFO: Appending metadata.
[build] INFO: Wrote metadata:
[build] INFO:   Section: Identity
[build] INFO:     Image Type:           Application
[build] INFO:     Component ID:         **********************************************
[build] INFO:     Image ID:             ***************************************************
[build] INFO:   Section: Signature
[build] INFO:     Signing Type:         ECDsa256
[build] INFO:     Cert:                 ******************************************************
[build] INFO:   Section: Debug
[build] INFO:     Image Name:           RS-485 HighLevelApp
[build] INFO:     Built On (UTC):       2022-08-17 12:18:18
[build] INFO:     Built On (Local):     2022-08-17 08:18:18
[build] INFO:   Section: Temporary Image
[build] INFO:     Remove image at boot: False
[build] INFO:     Under development:    True
[build] INFO:   Section: ABI Depends
[build] INFO:     Depends on:           ApplicationRuntime, version 13
[build] INFO: 
[build] INFO: Packaging completed successfully.
[build] INFO: Output file is at: D:/Applfich/SOAP/training/RS485Driver/HLApp/out/ARM-Debug/RS_485_HighLevelApp.imagepackage
[build] INFO: Command completed in 00:00:00.5390391.
[build] INFO: Command ran in 0.710 seconds (init: 0.008, invoke: 0.702)
[build] Build finished with exit code 0
[main] Building folder: RTApp 
[build] Starting build
[proc] Executing command: D:\Applfich\cmake\bin\cmake.EXE --build d:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug --config Debug --target all -- -v
[build] [10/13   7% :: 0.889] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/ringBuffer.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\ringBuffer.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/ringBuffer.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/ringBuffer.c
[build] [10/13  15% :: 0.913] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/VectorTable.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\lib\VectorTable.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/VectorTable.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/lib/VectorTable.c
[build] [10/13  23% :: 0.921] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/rs485_driver.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\rs485_driver.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/rs485_driver.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/rs485_driver.c
[build] [10/13  30% :: 0.923] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/Print.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\lib\Print.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/Print.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/lib/Print.c
[build] [10/13  38% :: 0.925] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/Socket.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\Socket.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/Socket.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/Socket.c
[build] [10/13  46% :: 0.951] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/UART.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\lib\UART.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/UART.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/lib/UART.c
[build] [10/13  53% :: 0.954] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/MBox.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\lib\MBox.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/MBox.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/lib/MBox.c
[build] [10/13  61% :: 0.960] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/GPT.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\lib\GPT.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/GPT.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/lib/GPT.c
[build] [10/13  69% :: 0.988] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/main.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\main.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/main.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/main.c
[build] [10/13  76% :: 1.003] D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe  -isystem D:/Applfich/SOAP/training/RS485Driver/HardwareDefinitions/qiio_q200_devkit/inc -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc" -isystem "C:/Program Files (x86)/Microsoft Azure Sphere SDK/HardwareDefinitions/inc/hw" -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/arm-none-eabi/11.3.1/include -isystem D:/Applfich/arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi/arm-none-eabi/include -mcpu=cortex-m4 -g -std=c11 -Wall -g2 -gdwarf-2 -O0 -MD -MT CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/GPIO.c.obj -MF CMakeFiles\RS-485_Driver_RealTimeApp.dir\lib\GPIO.c.obj.d -o CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/GPIO.c.obj -c D:/Applfich/SOAP/training/RS485Driver/RTApp/lib/GPIO.c
[build] [11/13  84% :: 1.216] cmd.exe /C "cd . && D:\Applfich\arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-gcc.exe -mcpu=cortex-m4 -g -nostartfiles -Wl,--no-undefined -Wl,-n -T "D:/Applfich/SOAP/training/RS485Driver/RTApp/linker.ld" CMakeFiles/RS-485_Driver_RealTimeApp.dir/main.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/Socket.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/ringBuffer.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/rs485_driver.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/VectorTable.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/GPT.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/GPIO.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/UART.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/Print.c.obj CMakeFiles/RS-485_Driver_RealTimeApp.dir/lib/MBox.c.obj -o RS-485_Driver_RealTimeApp.out  -L"D:/Applfich/SOAP/training/RS485Driver/RTApp" && cd ."
[build] [12/13  92% :: 1.342] cmd.exe /C "cd /D D:\Applfich\SOAP\training\RS485Driver\RTApp\out\ARM-Debug && C:\LOCAL\Applfich\cmake\bin\cmake.exe -E make_directory D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin && C:\LOCAL\Applfich\cmake\bin\cmake.exe -E copy D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/RS-485_Driver_RealTimeApp.out D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin/app && D:\Applfich\MSYS2\mingw64\bin\strip.exe --strip-unneeded D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin/app"
[build] FAILED: approotRS-485_Driver_RealTimeApp/bin/app D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin/app 
[build] cmd.exe /C "cd /D D:\Applfich\SOAP\training\RS485Driver\RTApp\out\ARM-Debug && C:\LOCAL\Applfich\cmake\bin\cmake.exe -E make_directory D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin && C:\LOCAL\Applfich\cmake\bin\cmake.exe -E copy D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/RS-485_Driver_RealTimeApp.out D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin/app && D:\Applfich\MSYS2\mingw64\bin\strip.exe --strip-unneeded D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin/app"
**[build] D:\Applfich\MSYS2\mingw64\bin\strip.exe: Unable to recognise the format of the input file `D:/Applfich/SOAP/training/RS485Driver/RTApp/out/ARM-Debug/approotRS-485_Driver_RealTimeApp/bin/app'
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1**

**Comment by himanshusinha-msft** [comment]
Hello @mcousine 
Thanks for reaching out to us , but at this time it does not look like you are referring to a document but to a specific scenario . If that's the case we request you to please post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html) and other forums , we have our engineers and others who are monitoring them and will be happy to help .
If you have a document which you are following and if you think it needs  an update , please let us know about that here .

**Comment by mcousine** [comment]
Just trying to build this project that does not build in vscode ? https://github.com/Azure/azure-sphere-gallery/tree/main/RS485Driver
