### ISSUE TITLE
Missing Feature for MT3620, Wi-Fi 802.11a

### ISSUE THREAD

**Issue by residentx10** [MicrosoftDocs/azure-sphere-issues#30]
When will this be supported on the device, US version (SKU:102991012)?

**Comment by Alberto-Vega-MSFT** [comment]
@residentx10 I apologize for the super late response.  Can you post this as a feedback @ https://feedback.azure.com/forums/915433-azure-sphere?query=wifi . This will allow the community to upvote and for the product team to include into their plans. 
We also have the "Give Product Feedback" button in our documents now to take you directly to the appropriate feedback page.

**Comment by Alberto-Vega-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
