### ISSUE TITLE
Invalid page description

### ISSUE THREAD

**Issue by SuperElectron** [MicrosoftDocs/azure-sphere-issues#305]
[Enter feedback here]

This isn't showing how to convert.  This page is saying "I know you need to convert your project, so I'll tell you that you should look at a sample repo and then do it."  This isn't a how-to-convert page, this is a sample-cmake-project.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbcb7c84-bd49-1b2a-ae81-a2a2cc0e1fa4
* Version Independent ID: f70e4f72-6868-095f-9183-1a46409b1d48
* Content: [Convert a Visual Studio project to CMake - Azure Sphere](https://learn.microsoft.com/en-us/azure-sphere/resources/convert-vcxproj-cmake)
* Content Source: [AzureSphere/articles/resources/convert-vcxproj-cmake.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/convert-vcxproj-cmake.md)
* Service: **azure-sphere**
* GitHub Login: @richcalaway
* Microsoft Alias: **azurespheredocs**

**Comment by bawilless** [comment]
Hi Matthew,

I wrote this up in 2020. It may help you.

https://community.element14.com/products/devtools/avnetboardscommunity/azure-sphere-starter-kits/b/blog/posts/porting-azure-sphere-visual-studio-projects-to-cmake

Brian
________________________________
From: Matthew McCann ***@***.***>
Sent: Friday, July 21, 2023 11:23:32 AM
To: MicrosoftDocs/azure-sphere-issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External][MicrosoftDocs/azure-sphere-issues] Invalid page description (Issue #305)


[Enter feedback here]

This isn't showing how to convert. This page is saying "I know you need to convert your project, so I'll tell you that you should look at a sample repo and then do it." This isn't a how-to-convert page, this is a sample-cmake-project.
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: bbcb7c84-bd49-1b2a-ae81-a2a2cc0e1fa4
  *   Version Independent ID: f70e4f72-6868-095f-9183-1a46409b1d48
  *   Content: Convert a Visual Studio project to CMake - Azure Sphere<https://learn.microsoft.com/en-us/azure-sphere/resources/convert-vcxproj-cmake>
  *   Content Source: AzureSphere/articles/resources/convert-vcxproj-cmake.md<https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/convert-vcxproj-cmake.md>
  *   Service: azure-sphere
  *   GitHub Login: @richcalaway<https://github.com/richcalaway>
  *   Microsoft Alias: azurespheredocs

**Comment by SaibabaBalapur-MSFT** [comment]
@SuperElectron 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-thepet** [comment]
@SaibabaBalapur-MSFT Sorry, I am not the author of this topic. My only contribution to this topic was a bulk metadata update to remove one metadata attribute done as part of a Quality & Maintenance vendor pass. It looks like the author richcalaway doesn't exist anymore in GitHub or Microsoft so I suggest assigning this to @prabhushyja as owner of this content set.

**Comment by SaibabaBalapur-MSFT** [comment]
@prabhushyja
please review it.

**Comment by prabhushyja** [comment]
@SuperElectron - Can you provide specific feedback about the information you are looking for on this page?

We do not automatically convert Visual Studio projects. If you have Visual Studio project files, you have to manually follow the steps listed in [Convert a Visual Studio project to CMake]( https://learn.microsoft.com/azure-sphere/resources/convert-vcxproj-cmake?view=azure-sphere-legacy).

**Comment by SuperElectron** [comment]
Can close, it was a while ago and I don't have the code on me. Have a great day 😊
