### ISSUE TITLE
Typo "a Azure DevOps"→"an Azure DevOps"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-sphere-issues#307]
https://learn.microsoft.com/en-us/azure-sphere/app-development/continuous-integration?view=azure-sphere-legacy
![image](https://github.com/MicrosoftDocs/azure-sphere-issues/assets/40815708/785dccf3-78c4-477a-b7cd-4dbbe2332abb)
#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2eac9-a1f2-58fc-dbcf-08802f0598e8
* Version Independent ID: b51cdcac-cf1e-38cd-c720-877edfde3eea
* Content: [Add Continuous Integration to your container builds - Azure Sphere](https://learn.microsoft.com/en-us/azure-sphere/app-development/continuous-integration?view=azure-sphere-legacy)
* Content Source: [AzureSphere/PAPI/app-development/continuous-integration.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/PAPI/app-development/continuous-integration.md)
* Service: **azure-sphere**
* GitHub Login: @richcalaway
* Microsoft Alias: **azurespheredocs**

**Comment by RamanathanChinnappan-MSFT** [comment]
@hyoshioka0128 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by LeelaRajesh-Sayana** [comment]
Hi @hyoshioka0128 Thank you for your feedback. We have made the changes to the document through a change request. The modifications will be reflected on the document once the document is merged. 

We will now proceed to closing this issue. Thank you for contributing towards improving the document experience. 

Best regards,
Leela Rajesh.
