### ISSUE TITLE
Device claimed on expired account

### ISSUE THREAD

**Issue by klinki** [MicrosoftDocs/azure-sphere-issues#309]
Hello,

I have my Azure starter kit claimed on expired account. I claimed it long time ago and it forced me to create a new Azure account (it didn't allow to claim on personal accounts back then) with `.onmicrosoft.com` domain. That account was trial and unfortunately it expired.

I haven't been using the device for a while but now I'd like to use it. Unfortunately it seems impossible. I tried to search for solutions and I came across this: https://learn.microsoft.com/en-us/answers/questions/27036/azure-sphere-claim-to-a-tenant-in-expired-active-d?source=docs

but `azsphere tenant migrate ` command is not in azsphere SDK anymore and it is not possible to use it. I couldn't find any download link for older SDKs either.

Is there any way how to unclaim/reclaim the device or get access to expired and probably deleted account? Or is it all lost and the device  is bricked and I can throw it away (that would be a shame, it is really nice device :( )

**Comment by TPavanBalaji** [comment]
@klinki 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@klinki 
 Thanks for sharing the feedback. Since this channel is for driving improvements towards Docs, could you please provide the URL of the specific documentation that your feedback is applicable to? That way, we can make sure your feedback is addressed by the right team.

**Comment by klinki** [comment]
Sure. For example following links give error 404:

https://learn.microsoft.com/en-us/azure-sphere/resources/migrate-individual
https://learn.microsoft.com/en-us/azure-sphere/resources/rbac-device-migration

**Comment by TPavanBalaji** [comment]
@klinki 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@klinki 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
