### ISSUE TITLE
Missing Features for MT3620, RTC with clock selection and battery backup

### ISSUE THREAD

**Issue by residentx10** [MicrosoftDocs/azure-sphere-issues#31]
When will this be supported on the device, US version (SKU:102991012)?

**Comment by richardtaylorrt** [comment]
Hi - please see [Using the real-time clock with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/rtc), added as part of our [18.11 release](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1811).
