### ISSUE TITLE
Failed to build the azure sphere linux distribution

### ISSUE THREAD

**Issue by crushonme** [MicrosoftDocs/azure-sphere-issues#33]
Compile version: gcc-arm-none-eabi 4.8.2
OS; Windows 1803
Linux Version: Ubuntu on Windows

When I build the azure sphere linux distribution in [Third party disclosures and source code](https://3rdpartysource.microsoft.com/), I get below error:

`xxx#xxx:/mnt/d/linux-azure-sphere$ make ARCH=arm -j 4 xipImage
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make: *** [prepare-compiler-check] Error 1
make: *** Waiting for unfinished jobs....
  UPD     include/config/kernel.release
make: *** wait: No child processes.  Stop.`

**Comment by spatdsg** [comment]
Did you install the GNU ARM embedded toolchain ?
Have you tried to run the following:

make ARCH=arm defconfig KBUILD_DEFCONFIG=mt3620_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-eabi- -j 4 xipImage

**Comment by crushonme** [comment]
> Have you tried to run the following:
> 
> make ARCH=arm defconfig KBUILD_DEFCONFIG=mt3620_defconfig
> make ARCH=arm CROSS_COMPILE=arm-none-eabi- -j 4 xipImage

Of course. Before build xipImage, I have build the default config.

**Comment by crushonme** [comment]
In README-AZURE-SPHERE.md, it told that "Any version of this tool chain 4.0 or higher will work for building the kernel.  Testing has been done with both versions 4.9.3 and 6.3.0."

And [-fstack-protector-strong](https://outflux.net/blog/archives/2014/01/27/fstack-protector-strong/) told that fstack-protector-strong is a new option in gcc 4.9. So maybe I should compile the kernel with gcc version above 4.9.

**Comment by crushonme** [comment]
I have successfully build azure sphere Linux distribution with gcc-arm-none-eabi version 6.3.1 on Ubuntu 18.04 on windows 10.
