### ISSUE TITLE
What format strings are supported?

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/azure-sphere-issues#34]
Is it all of the GNU C library printf() formats, or a subset, or something different?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6ea9588-a545-f42f-71e9-963835e8362b
* Version Independent ID: c8ea8118-9431-ac66-d0b3-70893657845f
* Content: [Log_Debug function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-log/function-log-debug)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-log/function-log-debug.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-log/function-log-debug.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Thanks for your feedback @BarryBo.

@pennyo can you please validate what are the strings format supported and enhance the doc with that info?

Thank you!

**Comment by pennyo** [comment]
Thanks, Barry. This item is on our backlog.
