### ISSUE TITLE
What is the run-time overhead of this API?

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/azure-sphere-issues#35]
I expect it'll be fast/non-blocking, but I'd like to be sure it won't cause my application to hang for long periods of time.  Could you add documentation about whether it never blocks, may block, etc., and guidance about how long it could take to run?  Same with other APIs that will be called from the main loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd167041-723d-8652-c852-d8114bbd3612
* Version Independent ID: 13412e33-7312-3b2e-0081-4a4303de8530
* Content: [Networking_IsNetworkingReady function - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-networking/function-networking-isnetworkingready.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@BarryBo Thanks for the feedback and reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by pennyo** [comment]
Thanks, Barry. This item is on our backlog.
