### ISSUE TITLE
UART Bytes Send/Receive

### ISSUE THREAD

**Issue by EHUbels** [MicrosoftDocs/azure-sphere-issues#36]
Based on the UART examples as well as Kevin Saye's BLOG on RS-485 I'm trying to read 32 bytes, one frame from a sensor through the UART. I'm reading the bytes but get an unwanted termination into two frames of each 12 bytes and one of 8 bytes. I have a similar issue when sending HEX over the UART, as soon as it includes 0x00 it terminates. Any suggestions, Kevin's RS-485 seem to be able to read larger frames.

    if (bytesRead > 0) {
        // Null terminate the buffer to make it a valid string, and print it
        receiveBuffer[bytesRead] = 0;
        // Log_Debug("UART received %d bytes: '%s'\n", bytesRead, (char *)receiveBuffer);
		Log_Debug("UART received %d bytes: ", bytesRead);
		for (int counter = 0; counter < bytesRead; counter++) {
			Log_Debug(" [%d] ", receiveBuffer[counter]);
		}

Erik

**Comment by EHUbels** [comment]
Dear Antonio, Richard,

Thank you so much for your response, really appreciate it. UART always seem to cause a lot of frustration, I'm sorry my request was not completely clear. It's not the sending that is the issue. Whatever I receive, also based on the example and your response the UART or code seems to truncate at 12 bytes.

My sensor transmits exactly 32 bytes and no \0 or anything like it are in the frame. I took a shot from the protocol analyzer, details tell me the exact data I should get comes in. The UART (or better the UART handler code ) or the example cuts it into pieces. Even with the example code from Kevin Saye, while he clearly get's longer frames based on the pictures, cuts of at 12 bytes. The sensor does do I2C as well, but as this is not supported yet we fall back to using the UART. Any suggesting to get this resolved is highly appreciated.


Protocol Analyzer, 32 bytes come in nicely (9600 baud)
![image](https://user-images.githubusercontent.com/13225124/46890830-4e470d00-ce68-11e8-84b4-9fec45d40250.png)

UART or code truncates the 32 byte frame at 12 bytes
![image](https://user-images.githubusercontent.com/13225124/46890903-851d2300-ce68-11e8-9d1e-1d776661929b.png)
Code is altered according the Kevin Saye's Azure Sphere RS-485 example

![image](https://user-images.githubusercontent.com/13225124/46890938-a54ce200-ce68-11e8-9bd8-cadb25e94cd6.png)
This image from the RS-485 example clearly receives more bytes without the truncating at 12 bytes.
![image](https://user-images.githubusercontent.com/13225124/46891029-ef35c800-ce68-11e8-8255-26721e706528.png)

Looking forward for any suggestions.

Erik

**Comment by richardtaylorrt** [comment]
Hi Erik, as @sergaz-msft says "when reading from UART, you may receive any number of bytes up to the maximum you requested.  This means you need to build up a receive buffer and keep track of how many bytes you have received so far.  Then you can act when you have received a full frame."

The rough code below shows a possible approach to this. 

```
uint8_t receiveBuffer[32];
size_t receivedSoFar = 0;

static void UartEventHandler(int uartFd)
{
       ssize_t bytesRead = read(uartFd, receiveBuffer + receivedSoFar, 32 - receivedSoFar);

       if (bytesRead > 0) {
              receivedSoFar += (size_t)bytesRead;

              if (receivedSoFar == 32) {
                     //Process the frame.  E.g. for now, Log_Debug the 32 bytes in the buffer.
                     receivedSoFar = 0;
              }
       }
}
```

Note this code is just to illustrate the point, and you’d need to test and adapt it.  In particular, it doesn’t consider any issues of frame alignment (you might start receiving in the middle of a frame).

**Comment by EHUbels** [comment]
The example code worked perfect, I do now receive the full frame of the PMS7003 Air Particle Sensor. Next issue I run into, yet again UART is sending command to the UART.

I've modified both the ButtonTimerEventHandler and the SendUartMessage to be able to send the following command, it only does send the first 4 bytes! Any suggestions?
    if (newButtonState != buttonState) {
        if (newButtonState == GPIO_Value_Low) {
            // const char *messageToSend = "Hello world!\n";
			// const char *messageToSend = "\x4D\x42\x0Hello world!\n"; //This will only send two bytes, terminates at \x0 ??
			// Need to send: { 0x42, 0x4D, 0xE4, 0x00, 0x00, 0x01, 0x73 }
			uint16_t command[7] = { 0x42, 0x4D, 0xE4, 0x00, 0x00, 0x01, 0x73 };
            SendUartMessage(uartFd, command);

static void SendUartMessage(int uartFd, uint16_t *dataToSend)
{
    size_t totalBytesSent = 0;
    size_t totalBytesToSend = sizeof(dataToSend);
    size_t sendIterations = 0;
    while (totalBytesSent < totalBytesToSend) {
        sendIterations++;

        // Send as much of the remaining data as possible
        size_t bytesLeftToSend = totalBytesToSend - totalBytesSent;
        uint16_t *remainingMessageToSend = dataToSend + totalBytesSent;
        int bytesSent = write(uartFd, remainingMessageToSend, bytesLeftToSend);


Erik

**Comment by richardtaylorrt** [comment]
Hi - to send all 7 bytes, you should try:
`size_t totalBytesToSend = 7;`

sizeof(dataToSend) is just the size of the dataToSend pointer variable itself: which is 4 bytes on this 32-bit processor.

Also, I haven't tested, but if you are sending bytes, you should probably use char or uint8_t, and not uint16_t.

**Comment by EHUbels** [comment]
Richard,

Thanks, this works like a charm, perfect. I can now read the complete data from the PMS7003 particle sensor and send a command to make it sleep. Wake-up will be similar but I'll have to create a second button instance and everything. Tomorrow I'll expect the CO2 sensors come in and they also use the UART in a similar way.

Thanks a lot.

Erik

**Comment by Prathik-Bhundary** [comment]
> Hi Erik, as @sergaz-msft says:
> 
> > When reading from UART, you may receive any number of bytes up to the maximum you requested.  This means you need to build up a receive buffer and keep track of how many bytes you have received so far.  Then you can act when you have received a full frame.
> 
> The rough code below shows a possible approach to this.
> 
> ```
> uint8_t receiveBuffer[32];
> size_t receivedSoFar = 0;
> 
> static void UartEventHandler(int uartFd)
> {
>        ssize_t bytesRead = read(uartFd, receiveBuffer + receivedSoFar, 32 - receivedSoFar);
> 
>        if (bytesRead > 0) {
>               receivedSoFar += (size_t)bytesRead;
> 
>               if (receivedSoFar == 32) {
>                      //Process the frame.  E.g. for now, Log_Debug the 32 bytes in the buffer.
>                      receivedSoFar = 0;
>               }
>        }
> }
> ```
> 
> Note this code is just to illustrate the point, and you’d need to test and adapt it. In particular, it doesn’t consider any issues of frame alignment (you might start receiving in the middle of a frame).

Thank you. This worked. But what if the receiving data varies every time. At that time I cant set the receiving buffer. What should I do? Thank you.

**Comment by asergaz** [comment]
@Prathik-Bhundary can you predicr rhw maximum possible receive size and use that instead of '32'?
