### ISSUE TITLE
COM Ports?

### ISSUE THREAD

**Issue by jwargo** [MicrosoftDocs/azure-sphere-issues#37]
Why does the device expose three COM ports? That's not described in the docs. What's the purpose of each COM Port?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de08ad95-5a5b-7d0d-860c-f9eb2e20c25e
* Version Independent ID: 496bd01d-da35-136d-cfec-c5b4c5479bab
* Content: [Azure Sphere installation and device setup](https://docs.microsoft.com/en-us/azure-sphere/install/install)
* Content Source: [AzureSphere/articles/install/install.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by matsujirushi** [comment]
Look [here](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-mcu-program-debug-interface#overview-of-components).

**Comment by sergaz-msft** [comment]
More info here: https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-hardware-designers 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
