### ISSUE TITLE
claiming a device

### ISSUE THREAD

**Issue by jwargo** [MicrosoftDocs/azure-sphere-issues#38]
I'm assuming you want to connect the device to power before claiming it. How does the CLI know which device to claim?  I'm assuming it's looking for the device connected via USB cable to the system running the CLI? shouldn't all those topics be covered in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
@jwargo sorry the late on this. Let us know if your feedback has been addressed now with the different versions on the documentation since you opened the issue?

Thank you!

**Comment by sergaz-msft** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
