### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by jwargo** [MicrosoftDocs/azure-sphere-issues#39]
The content in the page isn't rendering properly - you have a big code block in what should be a series of blocks separated by text:

4. Add your Wi-Fi network to the device by using the azsphere device wifi add command as follows:

```shell
azsphere device wifi add --ssid &lt;yourSSID&gt; --key &lt;yourNetworkKey&gt;
```
Replace `&lt;yourSSID&gt;` with the name of your network and `&lt;yourNetworkKey&gt;` with your WPA/WPA2 key. Azure Sphere devices do not support WEP. Network SSIDs are case-sensitive. For example:

```shell
azsphere device wifi add --ssid My5GNetwork --key secretnetworkkey
```

To add an open network, omit the `--key` flag.

If your network SSID or key has embedded spaces, enclose the SSID or key in quotation marks. If the SSID or key includes a quotation mark, use a backslash to escape the quotation mark. Backslashes do not require escape if they are part of a value. For example:

```shell
azsphere device wifi add --ssid "New SSID" --key "key \"value\" with quotes"
```  

It typically takes several seconds for networking to be ready on the board, but might take longer, depending on your network environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db907e3-85a6-ab65-837b-7e6a5dc12224
* Version Independent ID: dfd84d21-060c-1ba2-6341-54ed7248ae23
* Content: [Configure Wi-Fi and update your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi)
* Content Source: [AzureSphere/articles/install/configure-wifi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/configure-wifi.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for the feedback. We will correct this error.

**Comment by viktor-morin** [comment]
Hi!
How does Microsoft think about how this would work in reality? How should the end-user first time connect the device? Or change password if the router is replaced? We assume that all devices wont have an input display or similar? Any best practice regarding this? Cheers

**Comment by sergaz-msft** [comment]
@jwargo , @viktor-morin thank you for your feedback and sorry for the delay on the follow-up.

I am requesting @pennyo to review if the feedback was addressed and weather we can close this issue as resolved now.

Thank you!

**Comment by pennyo** [comment]
The original formatting error has been fixed. 

As for questions about how to change passwords and other input devices, Azure Sphere now supports additional connectivity options, which are described [here](https://docs.microsoft.com/azure-sphere/network/connect-private-network) and [here](https://docs.microsoft.com/en-us/azure-sphere/network/wifi-including-ble). We also provide connectivity samples and reference solutions in the [Azure Sphere Samples repo](https://github.com/Azure/azure-sphere-samples) on GitHub. 

Please let us know if this answers your questions.
Thank you!

**Comment by sergaz-msft** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
