### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by HowardEdidin** [MicrosoftDocs/azure-sphere-issues#40]
No Content 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback. We've fixed the problem.
