### ISSUE TITLE
azure_iot_utilities.h

### ISSUE THREAD

**Issue by HowardEdidin** [MicrosoftDocs/azure-sphere-issues#42]
The file is not added to the sample project.

**Comment by peterfoot** [comment]
This only gets added after you right-click References and select Add Connected Service and then choose your IoT Hub or Device Provisioning Service.

**Comment by AshokPeddakotla-MSFT** [comment]
@HowardEdidin  We hope your issue has been addressed. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
