### ISSUE TITLE
Command Prompt correction

### ISSUE THREAD

**Issue by TimGitHub** [MicrosoftDocs/azure-sphere-issues#44]
Hi all, 
A tiny 'correction'. If you claim a device, the documentation suggests you should replace text inside the &lt;&gt;, however the &lt;&gt; themselves should also be replaced. Referring to:
"Replace my-tenant with a name that others in your organization".. 
I would recommend to change this to:
"Replace '&lt;my-tenant&gt;' with a name that others in your organization will recognize, such as "Contoso Ltd", including the " " at the beginning and the end. 

Would have saved me some searching. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a777684-ac8f-25df-600d-4b8aafada22a
* Version Independent ID: 8889f26b-3adf-1b14-f523-2f9844b82a2c
* Content: [Claim your device - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device#feedback)
* Content Source: [AzureSphere/articles/install/claim-device.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/claim-device.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thanks for the feedback. We'll fix this.

**Comment by pennyo** [comment]
Fixed and live.
