### ISSUE TITLE
Tutorial Feedback

### ISSUE THREAD

**Issue by fmokren** [MicrosoftDocs/azure-sphere-issues#47]
Excellent tutorial. Everything worked without me having to figure out missing instructions or variations between my experience and the original author's.

This tutorial also covers a lot of information. It's going to take me awhile to process it all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@fmokren Thank you very much for the excellent feedback. Please let us know if you have any additional questions.

**Comment by pennyo** [comment]
Thanks for the feedback!
