### ISSUE TITLE
Consider adding a link to "Recover" the device in the Install section of this documentation

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#48]
We're receiving new Seeed MT3620 development kits.  Sometimes, students are encountering a roadblock when they try to claim their Sphere device because the OS that shipped with the device is not compatible with the current Sphere SDK.  It's easy to get past this roadblock, all the user needs to do is recover the OS.  Recovering the OS is well documented on this site (https://docs.microsoft.com/en-us/azure-sphere/deployment/recover), but it's not obvious that when users hit this error that they need to execute a recover command.  I suggest adding an additional section under the  Install section to capture this possibility and how to get past it.  It would fit nicely between the "Set up and account" and "Claim your device" or add a note in the "Claim your device" page instructing the user what to do if they encounter this issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce2e7e5-f81c-2d1e-d98d-42b783ec5344
* Version Independent ID: d8575c34-508a-7f0d-f94b-396a93269967
* Content: [Install Azure Sphere software and set up the board](https://docs.microsoft.com/en-us/azure-sphere/install/overview)
* Content Source: [AzureSphere/articles/install/overview.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/overview.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless Thank you very much for the detailed feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by Mike-Ubezzi-MSFT** [comment]
@bawilless All Azure Sphere kits sold by Seeed are to be sold with the latest version. If you are finding kits that are not out-of-the-box with the latest version, can you please detail this. If all kits require updates, please detail this as well. Yes, adding this step to the documentation is a great suggestion but, the documentation was written with the intent that the device would be at the latest version. We are interested in figuring out the discrepancy. Thank you, Mike

**Comment by Mike-Ubezzi-MSFT** [comment]
In instances where the device requires the recovery steps to prepare the board, we would like the output of each command:

azsphere device show-ota-status -v
azsphere device show-attached -v

Please email the output of both commands for each device to: AzCommunity at Microsoft dotcom.

**Comment by bawilless** [comment]
Hi Mike,

Sorry for the delayed response, I was on vacation.  So far all the boards we have were sourced from Microsoft.  Be aware that new customers are also getting boards from Microsoft so they will encounter the same issue.  

I'm looking at the documentation from the point of view of a new user.  If a new user encounters this error, how will they know how to resolve the issue?  Including a note seems to cover that case and would help the user make forward progress.  Without that information, they need to do some research to find the recover feature.  

I can also see a scenario where users buy the development boards, but don't use them for a period of time.  If one of the quarterly OS updates is rolled out will they encounter this same issue?

I do have another unopened development board.  I'll run the commands mentioned in the previous post and send them off this morning.

**Comment by bawilless** [comment]
The requested output was sent via email.  I’ve also attached it here.

Brian



Brian Willess

brian.willess@avnet.com<mailto:%20brian.willess@avnet.com>

Technical Solutions Engineer

Engineering & Technology



[http://digital.avnet.com/signature/images/Avnet_logo_tagline_rgb.png]



1672 W. Flintlock Way

Chandler AZ, 85286

O 480.534.6041

avnet.com<http://www.avnet.com/>

**Comment by sergaz-msft** [comment]
Hi @bawilless I know a long time as passed (sorry for that) - I am checking back with you if your feedback was addressed with the new versions of the SDK and the changes done to the documentation since you opened the issue?

Thank you!

**Comment by bawilless** [comment]
Hi Sergio,

I just looked at the “claim your device” documentation again, and there’s not any mention of how to recover, or update the OS if your device has an older OS.  Maybe the SDK outputs that detail now?  There is a link to troubleshooting, but there’s no mention in that section either on how to recover your device.

I’m just looking out for a first time user who gets a board with an older OS, and gets stuck.

You can close this is you want, it’s not a show stopper, just thought we could do better.

Brian

Brian Willess

brian.willess@avnet.com<mailto:%20brian.willess@avnet.com>

Technical Solutions Engineer

Engineering & Technology



[http://digital.avnet.com/signature/images/Avnet_logo_tagline_rgb.png]



1672 W. Flintlock Way

Chandler AZ, 85286

O 480.534.6041

avnet.com<http://www.avnet.com/>

**Comment by sergaz-msft** [comment]
Thanks for revisiting this @bawilless . You are right we don't reference [here ](https://docs.microsoft.com/en-us/azure-sphere/install/claim-device) how to update the OS though we are trusting that a first-time user would follow the steps in order from [here](https://docs.microsoft.com/en-us/azure-sphere/install/overview). Meaning that they would need to Install the Azure Sphere SDK and set up the development board; **Update the OS**; Set up an account to authenticate with Microsoft Azure and just then Claim the device.

Let us know your thoughs?
We appreciate your feedback and will consider it for sure :)!

**Comment by pennyo** [comment]
@bawilless As @sergaz-msft  says, we assume that someone with a new board follows the instructions in order, and that someone with a board that is already in use will start with the [Release Notes](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1902) for the current release, as  linked in the release announcement. We welcome your feedback on how to make this clearer to our audience.

Thank you!

**Comment by bawilless** [comment]
Looks like you have it covered.  Thanks,

Brian

Brian Willess

brian.willess@avnet.com<mailto:%20brian.willess@avnet.com>

Technical Solutions Engineer

Engineering & Technology



[http://digital.avnet.com/signature/images/Avnet_logo_tagline_rgb.png]



1672 W. Flintlock Way

Chandler AZ, 85286

O 480.534.6041

avnet.com<http://www.avnet.com/>

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
