### ISSUE TITLE
A couple of typos

### ISSUE THREAD

**Issue by SitecoreDave** [MicrosoftDocs/azure-sphere-issues#49]
"Azure Sphere is a secured" should be: "Azure Sphere is a secure"
"through which applications can securely connected to the cloud and web." should be: "through which applications can securely connect to the cloud and web." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95a9f97-1fb1-b876-c4f5-878311a7db28
* Version Independent ID: 4b1a01aa-2f48-08b7-8f00-763bd3fa39cf
* Content: [Introduction to Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/#feedback)
* Content Source: [AzureSphere/articles/index.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/index.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback. We'll make the necessary changes.

**Comment by pennyo** [comment]
The use of "secured" is intentional. Other problem is fixed. Thanks for catching.
