### ISSUE TITLE
Component

### ISSUE THREAD

**Issue by viktor-morin** [MicrosoftDocs/azure-sphere-issues#50]
Hi! Could you describe the "component" in more detail and what the purpose is of the term.
We are building an image and then creating a imageset which we add to the feed for OTA.
But when creating a feed we need to attach a component, what's the purpose of adding that information?
What's the difference between an image set and a component?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13b5723-67c1-ebd8-5ae1-3c76f94cd5d3
* Version Independent ID: 14bd3533-ecd2-c30c-9132-d78bd8ca7ea1
* Content: [Deployment basics - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/deployment-concepts)
* Content Source: [AzureSphere/articles/deployment/deployment-concepts.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/deployment-concepts.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
HI Viktor-
Thanks for your feedback. These are good questions. We'll clarify this in a future update of the documentation.

**Comment by viktor-morin** [comment]
@pennyo 
Would it be possible for you to describe component now? Thing is we are giving a talk regarding Azure Sphere and would be good to know the concept Component and what it's used for.
Cheers

**Comment by matsujirushi** [comment]
Hi @viktor-morin ,
I trying to make Diagam Chart.

Component like 'Application'. It is without version number.

See my chart: (But it is draft :-) )
![image](https://user-images.githubusercontent.com/8079404/47566483-dcda8480-d966-11e8-882e-48bddd091eaa.png)

**Comment by viktor-morin** [comment]
Thanks

**Comment by sergaz-msft** [comment]
@viktor-morin I know a long time has passed since you opened the issue. Confirming before closing the issue if your feedback was addressed with the new versions of the documentation?

Thank you.

**Comment by pennyo** [comment]
@viktor-morin My apologies as well for failure to respond sooner. The diagram answered the question well. We are planning changes to the component/image/image set documentation for a future release.

**Comment by viktor-morin** [comment]
> @viktor-morin My apologies as well for failure to respond sooner. The diagram answered the question well. We are planning changes to the component/image/image set documentation for a future release.

Thanks, I was happy with the answer at that time! :)

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
