### ISSUE TITLE
UART Parity 

### ISSUE THREAD

**Issue by chuckrichards** [MicrosoftDocs/azure-sphere-issues#51]
the current library only support uartConfig.parity = UART_Parity_None

what about Even or Odd...  I need Odd for my testing

while on the topic what about uartConfig.dataBits = UART_DataBits_Seven

**Comment by sergaz-msft** [comment]
Thanks for the feedback @chuckrichards . I have passed that feedback to the product team. Can you as well please ask that feature here?: https://feedback.azure.com/forums/915433-azure-sphere

All Best
