### ISSUE TITLE
The command ""C:\Program Files (x86)\Microsoft Azure Sphere SDK\SysRoot\tools\gcc\strip.exe" --strip-unneeded 

### ISSUE THREAD

**Issue by theciscokid** [MicrosoftDocs/azure-sphere-issues#52]
I've just taken delivery of my Azure Sphere and am trying to run this example. When I try and deploy it from VS2017 I get the following error: - The command ""C:\Program Files (x86)\Microsoft Azure Sphere SDK\SysRoot\tools\gcc\strip.exe" --strip-unneeded &lt;path to app bin&gt;. I have tried repairing the sdk install and i've successfully setup the device with the azsphere commands as per this tutorial. Please advise.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d6e378-a8c1-6984-2a5c-30f2d2ae9971
* Version Independent ID: de2f147d-3f19-2f80-0427-b25c8061b51b
* Content: [Blink sample application Quickstart - Azure Sphere](https://docs.microsoft.com/en-gb/azure-sphere/quickstarts/qs-blink-application)
* Content Source: [AzureSphere/articles/quickstarts/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Hello @theciscokid thanks for your feedback!
Can you share more details (full error message in 'Build' pane of VS) and any relevant screenshots?

Thanks!

**Comment by sergaz-msft** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by bespinfw** [comment]
Hi, I have the same error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Program Files (x86)\Microsoft Azure Sphere SDK\Sysroots\1\tools\gcc\strip.exe" 
--strip-unneeded "C:\Users\\source\repos\\\\\bin\ARM\Debug\\bin\app"" 
exited with code 1.	AzureSphereVirtualCoffeeMachine	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\AzureSphere.targets	251	
![image](https://user-images.githubusercontent.com/36467271/54174726-4947c180-44cb-11e9-84d6-57bb66e2482f.png)
![image](https://user-images.githubusercontent.com/36467271/54174729-4fd63900-44cb-11e9-920a-7b6a0c6a3501.png)
![image](https://user-images.githubusercontent.com/36467271/54174739-59f83780-44cb-11e9-8ac6-0704336780a9.png)
![image](https://user-images.githubusercontent.com/36467271/54174755-71cfbb80-44cb-11e9-9bc3-cc24b4a84323.png)
![image](https://user-images.githubusercontent.com/36467271/54174775-8449f500-44cb-11e9-9322-dfef85e51d0c.png)
![image](https://user-images.githubusercontent.com/36467271/54174798-9af04c00-44cb-11e9-862a-e59f5e9c063e.png)

As you can see in some of the screenshots. My Windows installation is Korean with Unicode and my user path contains some Hangeul.

**Comment by bespinfw** [comment]
@sergaz-msft please have a look with me. 

I just updated my VS 2017 and also checked that it has nothing with the Hangeul in the path. I tried to create a new Azure Sphere blink Application and get the same error when trying to build the solution.

Please also check my post above for further information, where I missed to mention you.

Microsoft Visual Studio Professional 2017 
Version 15.9.8
VisualStudio.15.Release/15.9.8+28307.481
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA071
Microsoft Visual Studio Tools for Applications 2017

Visual C++ 2017   00369-60000-00001-AA071
Microsoft Visual C++ 2017

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

AWS Toolkit for Visual Studio 2017   1.14.5.0
AWS Toolkit for Visual Studio 2017.
Copyright 2011-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws-vs-toolkit.s3.amazonaws.com/versioninfo.html

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSON Checker for JSON validation
  [http://www.raboof.com/projects/jsonchecker/]
- Newtonsoft Json.NET
  [http://www.newtonsoft.com/json] 
- YamlDotNet
  [http://aaubry.net/pages/yamldotnet.html] 
    

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.7000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.7000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

AzureIoTHubConnectedService Extension   1.0
AzureIoTHubConnectedService Visual Studio Extension Detailed Info

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.7.1.6591
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure HDInsight Azure Node   2.3.7000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.7000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.4
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.7000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

R Tools for Visual Studio   1.3.40517.1016
Provides project system, R Interactive window, plotting, and more for the R programming language.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61902.21100
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.28218
Visual C++ for Linux Development

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Extension for Azure Sphere Preview   19.2.4.2762
Visual Studio Extension for Azure Sphere Preview

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.421
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by theciscokid** [comment]
I was using an organisational account. I switched to a normal windows account and that resolved the issue. My organisational account was showing as <username>(<part of organisation> and I believe it was the bracket in the path causing the issue. 
I'm now running a later version of the SDK and have not seen the issue again.

**Comment by bespinfw** [comment]
@theciscokid thanks for the hint and workaround

@sergaz-msft 
I can confirm following situations, independent of the solution path:
- The solutions are building without that error with a local user called 'user'
- The solutions are failing to build with a local user called 'user(something)' and my AAD user 'user(some)'

like thecosokid described it seems to have something to do with the users path which includes brackets () in the usernames. The Azure Sphere solution itself can be in a path with brackets and just building fine if the username does not contain it.

**Comment by sergaz-msft** [comment]
@bespinfw your windows installation is Korean. If you try a user name with brackets () on an English Windows Installation the issue is still there? I am not sure how to try and repro it - should I just create a username with brackets and try to install the SDK + follow the blink sample?

@theciscokid can you elaborate more? You don't see the issue even when using brackets in the path or username with brackets?

Thanks

**Comment by bespinfw** [comment]
> @bespinfw your windows installation is Korean. If you try a user name with brackets () on an English Windows Installation the issue is still there? I am not sure how to try and repro it - should I just create a username with brackets and try to install the SDK + follow the blink sample?

Yes please try that. For cross checking I also created an additional local user with brackets () in the name and tried to build the blink example. Build error occured immediatly.

**Comment by sergaz-msft** [comment]
Sorry the late @bespinfw . I was also able to reproduce the issue and will now raise this up internally. Thanks for your patience!

**Comment by pennyo** [comment]
We have updated the online documentation to add this information.
