### ISSUE TITLE
Find devices in devicegroup

### ISSUE THREAD

**Issue by viktor-morin** [MicrosoftDocs/azure-sphere-issues#53]
Is it possible to list all devices in a devicegroup? Or what's the idea about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7752135-2de8-7f0a-b7c4-9ad363311cf3
* Version Independent ID: af53a10a-6f57-fdca-f46d-3517f322d2e9
* Content: [Azure Sphere CLI device-group (dg) command](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device-group)
* Content Source: [AzureSphere/articles/reference/azsphere-device-group.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/azsphere-device-group.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Hello @viktor-morin . The command to list all devices in a device group is as follows:

`azsphere device-group list`
See [here](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device-group#list).

Thank you.

**Comment by sergaz-msft** [comment]
Hello @viktor-morin you are correct! Sorry about the misunderstanding. I am checking with product group if we support listing all devices in a device group.

Thank you!

**Comment by sergaz-msft** [comment]
I have passed this feedback to the product team. We don't have a command to list all devices on a devicegroup. Please can you also ask that feature here?: https://feedback.azure.com/forums/915433-azure-sphere

Thank you!

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
