### ISSUE TITLE
Azure Sphere Linux OS Github

### ISSUE THREAD

**Issue by viktor-morin** [MicrosoftDocs/azure-sphere-issues#54]
I was wondering if the Linux OS/Kernel is up on Github?
I saw a presentation where Microsoft stated it is open source and they count on contribution.
I can however not find it?

**Comment by richardtaylorrt** [comment]
Hi - please take a look at [Third party disclosures and source code](https://3rdpartysource.microsoft.com/), and filter on 'Azure Sphere'.

**Comment by mifurm** [comment]
There is no Azure Sphere repo there:(

**Comment by richardtaylorrt** [comment]
Hi @mifurm - the source isn't currently available directly here on GitHub, but it is available for download at the link above. Please let us know if you have any trouble accessing it. Thanks.

**Comment by AshokPeddakotla-MSFT** [comment]
@viktor-morin We hope your issue has been addressed.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
