### ISSUE TITLE
RDB design files

### ISSUE THREAD

**Issue by starbuckscoffee** [MicrosoftDocs/azure-sphere-issues#55]
Need description how we can download/get RDB design files(P-MT3620RDB-1-0xxxxx)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2245c14d-0ab2-05de-25ba-bdb7ed861aca
* Version Independent ID: a7f33bcd-3d29-e02e-983f-d939d57020d5
* Content: [MT3620 reference board design - Azure Sphere](https://docs.microsoft.com/ja-jp/azure-sphere/hardware/mt3620-hardware-designers)
* Content Source: [AzureSphere/articles/hardware/mt3620-hardware-designers.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-hardware-designers.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Hello @starbuckscoffee that description is not publicly available. Please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can validate if you have a NDA so that we can share that documentation with you.

Thank you!

**Comment by starbuckscoffee** [comment]
Thank you for answering to my questions.

**Comment by residentx10** [comment]
@starbuckscoffee
https://github.com/Azure/azure-sphere-hardware-designs/tree/master/P-MT3620RDB-1-0

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
