### ISSUE TITLE
Real-time processor

### ISSUE THREAD

**Issue by viktor-morin** [MicrosoftDocs/azure-sphere-issues#58]
We had a demo last week with Azure Sphere where we showed the application processor and alot of people where interested in what Azure Sphere can bring to the table.
Some people where specific asking about the real-time processor since they are looking to solve a current issue (big scale), where Azure Sphere could be the solution.

We where wondering if it's possible to get a preview, or ETA when its possible to test the real-time processor even if everthing (security) isn't completed? Would that be possible?

Best regards!

**Comment by vvvishnu1** [comment]
Hello Viktor, thank you for your patience and sending us this question. We cannot share the ETA for testing real time processor yet. Azure Sphere team is listening to the the feedback from the customers and using it to prioritize the feature development. We will let you know as soon as we have an ETA.

**Comment by Alberto-Vega-MSFT** [comment]
@viktor-morin For future reference this MSDN thread is asking people to reach out and we will provide an update as soon as we can. https://social.msdn.microsoft.com/Forums/en-US/001edc81-7236-4035-b7da-bcd0d910adca/mt3620-arm-cortexm4f-support-when?forum=azuresphere
