### ISSUE TITLE
Issues of update from 4.2.1 to 18.11

### ISSUE THREAD

**Issue by shijiong** [MicrosoftDocs/azure-sphere-issues#59]
Hello, my friends

Today I update my MT3620 from TP 4.2.1 to the latest 18.11, and find something interesting.

First of all, after update, I open the project that created for TP 4.2.1, while, a huge number of errors appear. Maybe it is caused by some including head files. Then, I have to create new projects, do some copy and paste work. Finally, everything works as before. Maybe we should write about this in the release notes of 18.11.

Secondly, I find that the source code of the sample project is different from TP 4.2.1. Maybe the new version is better than before, as it abandons some redundancy work. Maybe we should explain some key code snap in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f3ad79-95a2-25af-f8ee-99065e0e234c
* Version Independent ID: 22f057cd-e7ae-7488-dfd7-cfb227a70a2c
* Content: [Release notes for Azure Sphere 18.11 release](https://docs.microsoft.com/en-us/azure-sphere/resources/release-notes-1811)
* Content Source: [AzureSphere/articles/resources/release-notes-1811.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/resources/release-notes-1811.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by vvvishnu1** [comment]
The issue and its resolution are documented in the Release Notes now.

Attempts to rebuild existing TP 4.2.1 applications with the 18.11 Azure Sphere SDK Preview for Visual Studio will initially fail with the following error:
'Target API Set' project property is not set. Open the Project Properties and set this field using the drop-down menu. Ensure that the Configuration selected on that page includes the active build configuration (e.g. Debug, Release, All Configurations).

To correct this error:
1.	Open the Azure Sphere project in Visual Studio.
2.	On the Project menu, select project-name Properties.
3.	Ensure that the Configuration is set to either All Configurations or Active (configuration name).
4.	Select Target API Set. On the drop-down menu, choose 1 to use production APIs or 1+Beta1811 to use production and Beta APIs.
 5.	Click OK.

You can then rebuild the project.

**Comment by shijiong** [comment]
Hi Vishnu,

The problem is resolved. Thanks!

**Comment by Alberto-Vega-MSFT** [comment]
Going over unclosed issues @shijiong  Thanks for your valuable feedback!
