### ISSUE TITLE
manifest formatting broken

### ISSUE THREAD

**Issue by mmoskal** [MicrosoftDocs/azure-sphere-issues#6]
I guess some problem with triple backtick. The subsequent section appears as code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0db551c-2484-3af9-ac08-d9978e82b445
* Version Independent ID: dea4dddf-46d1-cb41-2dcf-b77dece8c581
* Content: [How to manually build and load an Azure Sphere application](https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build)
* Content Source: [AzureSphere/articles/app-development/manual-build.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/manual-build.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for the feedback. We'll fix this as soon as we can.

**Comment by pennyo** [comment]
Fixed 8/9 and pushed to Live.
