### ISSUE TITLE
Azure portal 에 있는 용어와 맞추었으면 합니다.

### ISSUE THREAD

**Issue by iz4blue** [MicrosoftDocs/azure-sphere-issues#60]
"가운데 패널에서 역할 및 관리자 아래에 있는 엔터프라이즈 애플리케이션을 선택합니다."
이 문구에서 "엔터프라이즈 애플리케이션" 이라는 단어는 portal 에서 "엔터프라이즈 응용 프로그램" 으로 되어 있습니다.
번역이 되면서 2가지의 용어 차이가 있어 혼선이 있습니다.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7e0886-3299-17a1-ea10-257c68e550bf
* Version Independent ID: dae4abba-a2fc-b58f-f18d-947d0a768003
* Content: [Limit access to your Azure Sphere tenant](https://docs.microsoft.com/en-us/azure-sphere/install/limit-tenant-access)
* Content Source: [AzureSphere/articles/install/limit-tenant-access.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/limit-tenant-access.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by kursatgol** [comment]
Hi All,

I can not see my tenant and my claimed device to this tenant on Azure Sphere Portal on my account. I did the whole limited access procedures and i added related users to the Azure Sphere utility application but nothing changed. Could you please help me?

regards.

**Comment by sergaz-msft** [comment]
@iz4blue @kursatgol thank you for your feedback. Sorry for the delay answering it. Can you please confirm if you are still seeing this issue?

Thanks

**Comment by sergaz-msft** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
