### ISSUE TITLE
There seems to be a typo in azure_iot_hub.c line 134

### ISSUE THREAD

**Issue by jrchinchilla** [MicrosoftDocs/azure-sphere-issues#61]
Variable defined as directMethodCallbackh(...) should be directMethodCallback(...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by jrchinchilla** [comment]
Not an issue after I uninstallde the Connected Service for IoT Hub extension in VS 2017.

**Comment by Alberto-Vega-MSFT** [comment]
@jrchinchilla Sorry for the delay. I am closing old issues. Closing this one since you were able to resolve it yourself. Thanks for reaching out!
