### ISSUE TITLE
Errors when compiling Azure IoT Hub Sample for MT3620 RDB (Azure Sphere)

### ISSUE THREAD

**Issue by jrchinchilla** [MicrosoftDocs/azure-sphere-issues#62]
Getting the folllowing errors:
1&gt;arm-poky-linux-musleabi-gcc.exe : error : crypt32.lib: No such file or directory
1&gt;arm-poky-linux-musleabi-gcc.exe : error : winhttp.lib: No such file or directory
1&gt;arm-poky-linux-musleabi-gcc.exe : error : Secur32.lib: No such file or directory
1&gt;arm-poky-linux-musleabi-gcc.exe : error : Ws2_32.lib: No such file or directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by jrchinchilla** [comment]
It seems like this issue happens when you have the Connected Service for IoT Hub extension installed in VS 2017. I uninstalled this extension and created a new "Azure IoT Hub Sample for MT3620 RDB (Azure Sphere)" project and was able to build and debug successfully.

**Comment by pennyo** [comment]
Yes, that is correct. For now, the solution is to uninstall the Connected Service for IoT Hub extension and use only the extension that is installed with the Azure Sphere SDK.

**Comment by JayaKumarBalan** [comment]
Still it did not work for me.

**Comment by JayaKumarBalan** [comment]
It worked now ,  A restart did the trick .

**Comment by piercalderan** [comment]
When compiling, in the output pane it shows:
MSB3073	uscita dal comando "%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File "C:\Users\pier\Desktop\azure-sphere-samples-master\Samples\AzureIoT\AzureIoT\script\validate_manifest.ps1
:VCEnd" with code 1.	AzureIoT	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	128

**Comment by sergaz-msft** [comment]
@piercalderan we are following-up with you here: https://github.com/Azure/azure-sphere-samples/issues/32 

Thanks!

**Comment by dippas123** [comment]
I'm still getting this:

Tried all the steps bar removing windows defender....

1>------ Build started: Project: AzureIoT, Configuration: Debug ARM ------
1>In file included from sample_hardware.h:13,
1>                 from main.c:36:
1>mt3620_rdb.h:10:10: fatal error: ..\..\..\mt3620\inc\hw\mt3620.h: No such file or directory
1> #include "..\..\..\mt3620\inc\hw\mt3620.h"
1>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1>compilation terminated.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\AzureSphere.targets(105,5): error MSB6006: "arm-poky-linux-musleabi-gcc.exe" exited with code 1.
1>Done building project "AzureIoT.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by richardtaylorrt** [comment]
Hi @dippas123 - this thread is closed, and was about an issue with different symptoms to yours.  So, to ensure a response, it might be best for you to create a new issue or raise the question on our [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azuresphere).  Thanks.
