### ISSUE TITLE
Is the dependant feed on this page still valid with the 18.11 release?

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#64]
Is this statement true for the 18.11 release?

"In the current release, Azure Sphere OS feed is named "Preview MT3620" and the feed ID is 3369f0e1-dedf-49ec-a602-2aa98669fd61."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16395218-fa75-bd42-ee22-d48eb25f61b2
* Version Independent ID: 161af554-9e3c-550c-4b0f-792446b9decc
* Content: [Link the device to a feed - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/link-to-feed)
* Content Source: [AzureSphere/articles/deployment/link-to-feed.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/link-to-feed.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Yes, that is correct. You can always verify by using  **azsphere feed list** on the command line:

>azsphere feed list
Listing all feeds.
Retrieved feeds:
--> [3369f0e1-dedf-49ec-a602-2aa98669fd61] 'Preview MT3620'
--> [a48bb8cf-bee5-439c-a3fa-889c5f1c9807] '1811UartTestFeed'
Command completed successfully in 00:00:05.4542688.
