### ISSUE TITLE
when instructed by Microsoft  is not clear 

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/azure-sphere-issues#66]
"when instructed by Microsoft" is not clear on who at Microsoft and when.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab9ea38-0619-6245-da46-33c535a7f92f
* Version Independent ID: 8e7168b8-055f-408a-aaad-0cefc6880d61
* Content: [MCU Programming and Debugging Interface Guide - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-mcu-program-debug-interface#ftdi-ft_prog-programming-tool)
* Content Source: [AzureSphere/articles/hardware/mt3620-mcu-program-debug-interface.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/mt3620-mcu-program-debug-interface.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
@aguptadel thank you for your feedback and we are sorry for the delay on our answer.

I believe your feedback was addressed on the new documentation. Can you please confirm before we close the issue?

Thank you!

**Comment by sergaz-msft** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
