### ISSUE TITLE
Issue withvCreate a new account 

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/azure-sphere-issues#67]
Create a new account and directory that are not associated with any other account did not worked for me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5cac582-108f-ed21-5ebd-02d35aaf6c3d
* Version Independent ID: 47d7bf64-ece8-a0c1-b2b7-3b6b447f9a03
* Content: [Account requirements for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/azure-directory-account)
* Content Source: [AzureSphere/articles/install/azure-directory-account.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/azure-directory-account.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@aguptadel I apologize for the delayed response. I just tested the part of the doc you are pointing out and it worked for me. Were you able to resolve this?

**Comment by Alberto-Vega-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
