### ISSUE TITLE
Great content !!!

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/azure-sphere-issues#68]
Ran with out issues 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d6e378-a8c1-6984-2a5c-30f2d2ae9971
* Version Independent ID: de2f147d-3f19-2f80-0427-b25c8061b51b
* Content: [Blink sample application Quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-blink-application)
* Content Source: [AzureSphere/articles/quickstarts/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Good to hear! Thank you!
