### ISSUE TITLE
Is there recommend store for the Azure Sphere Development Kit in China?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/azure-sphere-issues#69]
Hi all,
Is there recommend store for the Azure Sphere Development Kit in China?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de08ad95-5a5b-7d0d-860c-f9eb2e20c25e
* Version Independent ID: 496bd01d-da35-136d-cfec-c5b4c5479bab
* Content: [Azure Sphere installation and device setup](https://docs.microsoft.com/en-us/azure-sphere/install/install)
* Content Source: [AzureSphere/articles/install/install.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/install.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@moyanming Sorry for the delayed response.  I don't find any suggestions. Please use [this](https://azure.microsoft.com/en-in/services/azure-sphere/) link to get the development kit. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
