### ISSUE TITLE
Graphic in step #2 needs an update as the portal content has changed

### ISSUE THREAD

**Issue by bawilless** [MicrosoftDocs/azure-sphere-issues#70]
The "Add Enrollment Group" page has changed.  The "Save" button at the bottom of the page, now shows "Enable"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faedf864-4477-e53a-f711-0e5deaf3197b
* Version Independent ID: 416a2b64-8c07-f6bc-8393-307639bd9b3a
* Content: [Set up an Azure IoT Hub to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub)
* Content Source: [AzureSphere/articles/app-development/setup-iot-hub.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-hub.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by bawilless** [comment]
Step #3 also needs to be edited "save" becomes "Enable."

**Comment by bawilless** [comment]
Well I really need to finish the document before commenting.  The Save button is now at the top of the page.  Disregard my last comment.  : )

**Comment by pennyo** [comment]
A couple of things have changed here. We're updating for the next major release. 
Thank you for your feedback.

**Comment by mbryantII** [comment]
I am unable to find the enrollment section on the IoT Hub portal.  I suspect that there has been a UX change that removed or moved this functionality elsewhere
