### ISSUE TITLE
documentation error using the "azsphere device image list-installed" command

### ISSUE THREAD

**Issue by ewconnell** [MicrosoftDocs/azure-sphere-issues#72]
the "azsphere device image list-installed" command does not output JSON info as shown on this page. It outputs information like this:

Installed images:
 --&gt; Mt3620Blink1
   --&gt; Image type:   Application
   --&gt; Component ID: 9419cc28-79dc-4366-a066-590659dd0fbd
   --&gt; Image ID:     358fd27a-22f6-46c3-8ea8-42a8ac8f90be
Command completed successfully in 00:00:01.4284699

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e04f52b-e1a2-44ae-1102-efb2e2096731
* Version Independent ID: 004091d7-2e9e-9074-98b9-b1c364f8603a
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment)
* Content Source: [AzureSphere/articles/quickstarts/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback. We'll fix this in an upcoming update.
