### ISSUE TITLE
Update/OTA does not occur

### ISSUE THREAD

**Issue by mscbpi** [MicrosoftDocs/azure-sphere-issues#75]
azsphere device image list-targeted lists my application (blink)

azsphere device wifi show-status reports connected (unrestricted wifi)

azsphere device image list-installed shows no install even after reset.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6089189-0c15-d287-ff98-3bb424e4c24f
* Version Independent ID: ece2a111-b6a4-483a-e571-8f347757e285
* Content: [Cloud configuration tasks - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/hardware/cloud-configuration-tasks)
* Content Source: [AzureSphere/articles/hardware/cloud-configuration-tasks.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/hardware/cloud-configuration-tasks.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
If you've run prep-debug but haven't run prep-field the device will be in system software group only. Please run these two commands and make sure that the device group that your device is in supports both application and OS update. 
azsphere device show-ota-config
azsphere device-group show --devicegroupid <device group GUID from the ota config>

Thank you!



Thanks!

**Comment by pennyo** [comment]
A further suggestion:
If the verbose (-v) output of azsphere device image list-targeted, azsphere device image list-installed, and azsphere device show-ota-status (and the device group ones) shows that the image is indeed targeted at your device and that your device group enables OTA application update, the problem could be that your network has port/filter restrictions that aren't letting the update happen. Check [Azure Sphere networking requirements](https://docs.microsoft.com/en-us/azure-sphere/network/ports-protocols-domains) for a list.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @mscbpi was your issue resolved?

**Comment by Alberto-Vega-MSFT** [comment]
@mscbpi We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
