### ISSUE TITLE
Ports in wrong column

### ISSUE THREAD

**Issue by jmandel** [MicrosoftDocs/azure-sphere-issues#77]
In rows 1-2 of the table, ports appear (correctly) in the "Port" column, but in rows 3-6, they appear incorrectly in the "URL or IP Address" column.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02995860-63e0-47fa-91f8-35e7898116d1
* Version Independent ID: 39939a47-0efc-5632-11ad-05d1e91b4bde
* Content: [Azure Sphere OS networking requirements](https://docs.microsoft.com/en-us/azure-sphere/network/ports-protocols-domains#feedback)
* Content Source: [AzureSphere/articles/network/ports-protocols-domains.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/network/ports-protocols-domains.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you the feedback. We’ll fix this.

**Comment by pennyo** [comment]
Fixed in 19.02 release.
