### ISSUE TITLE
Device ID could not be found

### ISSUE THREAD

**Issue by Imacutekayx** [MicrosoftDocs/azure-sphere-issues#78]
Hello,

I try to claim a device with an existing id on my hub.
The code I write on the Developer Command Prompt is : "azsphere device claim --deviceid <idOfMyDevice>" but it returns the error : "Device Id <idOfMyDevice> could not be found, or was already claimed to a different Azure Sphere tenant.".

I login with the only tenant of my AD who has all rights on my hub and I verified my id to be sure but I can't find the solution.

Does someone have an idea?

**Comment by sergaz-msft** [comment]
Thank you for your feedback @Imacutekayx . Can you confirm that you are following the steps from [this doc](https://docs.microsoft.com/en-us/azure-sphere/install/overview) in the correct order?

PS ([see here](https://docs.microsoft.com/en-us/azure-sphere/install/create-tenant)): 
"
If a tenant already exists, do not create another one unless your company or organization requires more than one tenant. We recommend that each company or organization create only one Azure Sphere tenant. If you are absolutely certain that you want to create another one, use the following command:
`azsphere tenant create --force --name <my-tenant>`
"

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
