### ISSUE TITLE
Azure Sphere SDK: VSIX installation setup failed

### ISSUE THREAD

**Issue by pgmolloy** [MicrosoftDocs/azure-sphere-issues#79]
Tried to update Azure Sphere SDK to [19.02] that I downloaded from https://aka.ms/AzureSphereSDKDownload and received this error screen
![2019-02-16_13-45-58](https://user-images.githubusercontent.com/8608419/52905050-7e753280-31f1-11e9-97ca-a8d2728713ff.png).
=====================================================
The log file is attached. 
[dd_VC_AzureSphere_20190216134840.log](https://github.com/MicrosoftDocs/azure-sphere-issues/files/2872371/dd_VC_AzureSphere_20190216134840.log)
======================================================
I now cannot connect to my device using any of the azsphere commands and receive the following

>azsphere device recover
Starting device recovery. Please note that this may take up to 10 minutes.
Board found. Sending recovery bootloader.
Erasing flash.
Sending images.
Sending image 1 of 16.
Sending image 2 of 16.
Sending image 3 of 16.
Sending image 4 of 16.
Sending image 5 of 16.
Sending image 6 of 16.
Sending image 7 of 16.
Sending image 8 of 16.
Sending image 9 of 16.
Sending image 10 of 16.
Sending image 11 of 16.
Sending image 12 of 16.
Sending image 13 of 16.
Sending image 14 of 16.
Sending image 15 of 16.
Sending image 16 of 16.
Finished writing images; rebooting board.
error: Failed to establish communication with device after recovery. Try unplugging the device and plugging it back in, and verifying communication using 'azsphere device show-attached'. If that fails, try recovering the device again.
error: Failed to establish communication with device after recovery.
error: Command failed in 00:04:25.8889993.

>azsphere device show-attached
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support.
error: Command failed in 00:00:21.7298288.

C:\Users\pmoll\OneDrive\Documents>azsphere device recover
Starting device recovery. Please note that this may take up to 10 minutes.
Board found. Sending recovery bootloader.
Erasing flash.
Sending images.
Sending image 1 of 16.
Sending image 2 of 16.
Sending image 3 of 16.
Sending image 4 of 16.
Sending image 5 of 16.
Sending image 6 of 16.
Sending image 7 of 16.
Sending image 8 of 16.
Sending image 9 of 16.
Sending image 10 of 16.
Sending image 11 of 16.
Sending image 12 of 16.
Sending image 13 of 16.
Sending image 14 of 16.
Sending image 15 of 16.
Sending image 16 of 16.
Finished writing images; rebooting board.
error: Failed to establish communication with device after recovery. Try unplugging the device and plugging it back in, and verifying communication using 'azsphere device show-attached'. If that fails, try recovering the device again.
error: Failed to establish communication with device after recovery.
error: Command failed in 00:04:25.3038558.

Azure Sphere Utility version 18.11.3.23758
Copyright (C) Microsoft Corporation. All rights reserved.

    Azure Sphere command line tool: azsphere.exe

Required Parameters:
    <Operation>
        com, component   - Manage components and images in your Azure Sphere tenant.
        dev, device      - Manage devices.
        dg, device-group - Manage device groups in your Azure Sphere tenant.
        feed             - Manage feeds in your Azure Sphere tenant.
        img, image       - Manage image packages.
        ims, image-set   - Manage image sets in your Azure Sphere tenant.
        login            - Log in to the Azure Sphere Security Service.
        logout           - Log out from the Azure Sphere Security Service.
        show-version     - Show the version of the Azure Sphere tools.
        sku              - Manage SKUs in your Azure Sphere tenant.
        tenant           - Manage Azure Sphere tenants.

Optional Parameters:
    -?, --help    - Show help information.
    -v, --verbose - Show additional information.

>azsphere show-version
18.11.1
Command completed successfully in 00:00:00.2901525.

C:\Users\pmoll\OneDrive\Documents>azsphere dev show-attached
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support.
error: Command failed in 00:00:21.4924191.

>azsphere dev prep-field
error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support.
error: Command failed in 00:00:21.5620952.

>azsphere get-support-data -o c:\temp\spherelog.txt --verbose
Azure Sphere Utility version 18.11.3.23758
Copyright (C) Microsoft Corporation. All rights reserved.

Start time (UTC): Saturday, 16 February 2019 20:30:05
verbose: Created packaging folder: 'C:\Users\pmoll\AppData\Local\Temp\Azure_Sphere_Logs'.
Gathering the device data.
verbose:  -> Getting attached device's details.
error: Could not connect to the device. Check if your device is connected to the PC. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes. If this issue persists, try uninstalling and reinstalling the Azure Sphere SDK.
warn: Could not access the device. Check it is plugged in and try again.
Gathering Azure Sphere Security Service data.
verbose: Reading settings file 'C:\Users\pmoll\AppData\Local\Azure Sphere Tools\settings.json'.
verbose: ==> Using Azure Active Directory tenant ID: '51053ee5-c432-4107-8e9f-64c6f3788a10'.
verbose: ==> Using environment: 'prod'.
verbose: ==> Using Azure Sphere tenant ID: '315b98fa-91a0-4e5a-bcb7-e3e5f1c8b131'.

warn: Could not gather details from the Azure Sphere Security Service: Could not connect to the device. Check if your device is connected to the PC. The device may be unresponsive if it is applying an Azure Sphere operating system update; please retry in a few minutes. If this issue persists, try uninstalling and reinstalling the Azure Sphere SDK.
Gathering the computer setup data.
verbose:  -> Getting the azsphere.exe configuration.
verbose:  -> Getting the local network adapter addresses.
verbose:  -> Getting the Azure Sphere network adapter setup.
verbose:  -> Getting the Azure Sphere SLIP service status.
verbose:  -> Getting the Azure Sphere SLIP service logs.
verbose:  -> Getting the Azure Sphere installer logs.
verbose:  -> Getting the Visual Studio 2017 installer logs.
verbose:  -> Getting the VSIX plugin installer logs.
verbose: Created the archive file: 'c:\temp\spherelog.txt'.
Created the support log archive at 'c:\temp\spherelog.txt'.
Note: these logs contain information about your system including Wi-Fi scans, installation logs, Azure Sphere CLI and services configurations, and logs of attached USB devices.
Command completed successfully in 00:01:33.2562390.

**Comment by yuehuang010** [comment]
Hello, Thank you for trying Azure Sphere.  This is an issue is with 18.11 unintentionally affecting VS2019 Preview.  
To workaround the problem: Uninstall VS2019, then install it again.  Then install 19.02.  
Thanks.

**Comment by Alberto-Vega-MSFT** [comment]
@pgmolloy Just checking if you were able to overcome the issue.

**Comment by Alberto-Vega-MSFT** [comment]
@pgmolloy Closing this thread since we haven't heard back from you. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
