### ISSUE TITLE
Is there a update command that can be run?

### ISSUE THREAD

**Issue by crpietschmann** [MicrosoftDocs/azure-sphere-issues#8]
Is there a CLI command with azsphere that can be run to check if there's an update available and to tell the device to update? Something like "azsphere device ota-status" and "azsphere device ota-update" perhaps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed206f02-3d0c-fe46-6023-724aca70e885
* Version Independent ID: d7edffff-638a-58ec-990b-9281cd589bd8
* Content: [When do updates occur - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/deployment-updates)
* Content Source: [AzureSphere/articles/deployment/deployment-updates.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/deployment-updates.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback! Good question. 

Currently, azsphere does not have an update command. The device checks for update upon reboot, so you can trigger an update by pressing the Reset button on the development board. If an Azure Sphere OS update is available, Reset will download and install it. If an OTA application update is available, it will be installed if the current device group enables application update.

**Comment by viktor-morin** [comment]
Hi Pennyo!
So today, there is now way to remotly make the Azure Sphere to update the application? I need to physically restart it by pressing the reset button? How will this be handled in the future?

**Comment by pennyo** [comment]
Viktor,
Updating an application is different from updating the OS. To update an application, you upload a new imageset to the feed and then publish it, as described here: 

https://docs.microsoft.com/en-us/azure-sphere/deployment/redeploy

Your device must be in a device group that allows application updates. Typically this means you've run the prep-field command on it:
https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-device#prep-field

Hope this helps.

**Comment by viktor-morin** [comment]
Thanks for the input.
I have done those steps, so just to clarify. When will the application be loaded to the device after that? Can it happens anytime in the next 24 hours? Is there any state or similar I need to change to enable this, or how do you handle if the current application is doing something critical and you would like to wait before update the application?

The only way we got it to work now is to physically restart it, but that's not possible if we have the chip at a remote location.

**Comment by tokenstar** [comment]
Hi Viktor,
Assuming your device is connected to the Internet, it will update the application within 24 hours automatically.  There is nothing further you need to do to enable this.  

Your application will receive a [termination signal from the OS](https://docs.microsoft.com/en-us/azure-sphere/app-development/initialization-termination) just before the update occurs.  There is currently no way for the application to request a delay if it is doing something critical.  While this feature is already on the backlog, if you want to indicate support for it please file and upvote a feature request  https://feedback.azure.com/forums/915433-azure-sphere 

Thanks, James

**Comment by viktor-morin** [comment]
Thanks for information!
It's now clear!
