### ISSUE TITLE
In Azure portal, I could not find the same Device Explorer under my IoT Hub as the one described in this tutorial

### ISSUE THREAD

**Issue by max90727** [MicrosoftDocs/azure-sphere-issues#80]
Under my IoT hub, I found the IoT devices. In the Device details, I found the tab message to device, but I did not find the Data Tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Did you install the Device Explorer from [SetupDeviceExplorer.msi](https://github.com/Azure/azure-iot-sdk-csharp/releases/download/2018-3-13/SetupDeviceExplorer.msi) as referenced in the documentation? This is a separate tool that is not part of Azure Portal. Using Device Explorer, you see the Data tab when you open it, as in the following screenshot:
![image](https://user-images.githubusercontent.com/28548037/53443844-d407c700-39c9-11e9-9883-3419cef68a4b.png)

**Comment by jianyuanMa** [comment]
Thank you. That solves my question.
