### ISSUE TITLE
Some changes in the sample program output window

### ISSUE THREAD

**Issue by GlennMiller** [MicrosoftDocs/azure-sphere-issues#81]
Just a note to say the output window might be different for Device Output as described in (4)

INFO: Received desired value 1 for LedBlinkRateProperty, setting it to 1.
[Azure IoT] INFO: Set reported property 'LedBlinkRateProperty' to value 1.
[Azure IoT Hub client] INFO: AzureIoT_DoPeriodicTasks calls in progress...
[Azure IoT Hub client] INFO: AzureIoT_DoPeriodicTasks calls in progress...
[Azure IoT] INFO: Device Twin reported properties update result: HTTP status code 204

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback. We'll update the docs as required.

**Comment by AshokPeddakotla-MSFT** [comment]
@GlennMiller The document will be updated as per the suggestions after review. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
