### ISSUE TITLE
Step 5 doesn't work

### ISSUE THREAD

**Issue by sha1painkiller** [MicrosoftDocs/azure-sphere-issues#82]
In Step 5, can't find "Add enrollment group" in Azure portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faedf864-4477-e53a-f711-0e5deaf3197b
* Version Independent ID: 416a2b64-8c07-f6bc-8393-307639bd9b3a
* Content: [Set up an Azure IoT Hub to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub)
* Content Source: [AzureSphere/articles/app-development/setup-iot-hub.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-hub.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by xtreampb** [comment]
to find "Add enrollment group" open your device provisioning service.  Select "Manage enrollments" on the left hand side of the blade/window that appeared.  "Add enrollment group" will be near the top of the new view.
![Add enrollment group](https://user-images.githubusercontent.com/1777628/54156599-f8798f80-441c-11e9-8f96-32a7d363e493.jpg)
