### ISSUE TITLE
cartificate can not be uploaded to iot center

### ISSUE THREAD

**Issue by joeyjoey1984** [MicrosoftDocs/azure-sphere-issues#83]
after verify the certificate with IOT hub, the same certificate can not be uploaded to IOT center because it is grey in the selection icon. tried a new certificate, still can not be uploaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79eb45a2-0b0c-6449-5acc-504fb16583e6
* Version Independent ID: fa9be175-df4d-a165-144f-8abe62ecb7ea
* Content: [Set up Azure IoT Central to work with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-central)
* Content Source: [AzureSphere/articles/app-development/setup-iot-central.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/setup-iot-central.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
Hi @joeyjoey1984 I apologize for the delay. Just wanted to touch base and check if you were able to resolve this issue?

**Comment by Alberto-Vega-MSFT** [comment]
@joeyjoey1984 Thank you for reaching out. I am so sorry we did not get back to you on time. We will proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
