### ISSUE TITLE
which baudrates are valid values?

### ISSUE THREAD

**Issue by muesliman** [MicrosoftDocs/azure-sphere-issues#84]
which baudrates are valid values? maybe some defines or an additional enum might be quiet helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6456a5db-dfa5-9719-c1ec-090fcdc1b824
* Version Independent ID: cecf132c-31cf-0a74-c6ba-58ef71464b1d
* Content: [UART_BaudRate_Type typedef - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-uart/typedef-uart-baudrate-type#feedback)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-uart/typedef-uart-baudrate-type.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-uart/typedef-uart-baudrate-type.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by muesliman** [comment]
It seems that all common baud rates between 1.200 and 921.600 are allowed (so file descriptor is valid than)

**Comment by Alberto-Vega-MSFT** [comment]
@muesliman It seems like you resolved your issue?

**Comment by Alberto-Vega-MSFT** [comment]
@muesliman Just touching base to make sure you resolved your issue?

**Comment by muesliman** [comment]
At least it was more a try and error. 
But: what I expect, ist that there should be a documentation which baud-rates are really supported.

**Comment by pennyo** [comment]
@muesliman We will add this information in a future release of the documentation.

**Comment by Alberto-Vega-MSFT** [comment]
@muesliman Thanks for your feedback! We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pennyo** [comment]
This information is available in the documentation here:
[Use UART](https://docs.microsoft.com/en-us/azure-sphere/app-development/uart)
