### ISSUE TITLE
Sphere SDK plans with Linux (Ubuntu) support

### ISSUE THREAD

**Issue by jflynn129** [MicrosoftDocs/azure-sphere-issues#85]
Curious if there are any plans to support Ubuntu with the Sphere SDK?

**Comment by jflynn129** [comment]
I guess no response means:
1) No, there are no plans to support a Linux development environment thus not worthy of an answer
2) No one knew an issue was ever raised asking this question because they don't monitor github issues
3) Looking for someone to translate the question into the correct native language so it can be understood

I think it is interesting that no one can even take 5 seconds to respond to an issue when it is raised.

**Comment by sergaz-msft** [comment]
@jflynn129 sorry the delay on this one. Currently you will need a PC running Windows 10 Anniversary Update or later. See the Prerequisites [here](https://docs.microsoft.com/en-us/azure-sphere/install/install).

Please vote for the feature request [here](https://feedback.azure.com/forums/915433-azure-sphere/suggestions/35968183-support-linux-distros) so we can prioritize it :).

Thanks! Let us know if you have further questions?

**Comment by TomaszWaszczyk** [comment]
"Its so weird for the platform to be based on Linux, but not work on Linux" so true.

**Comment by richardtaylorrt** [comment]
@jflynn129 , @TomaszWaszczyk - please see point #3 of this [blog post ](https://techcommunity.microsoft.com/t5/Internet-of-Things/Plan-for-changes-coming-to-the-Azure-Sphere-SDK-in-next-release/ba-p/916078) about upcoming changes in the new SDK.

**Comment by TomaszWaszczyk** [comment]
Cool, thanks!!!!!
