### ISSUE TITLE
Problems connecting to MT3620 Development Kit

### ISSUE THREAD

**Issue by jflynn129** [MicrosoftDocs/azure-sphere-issues#86]
I received two different MT3620 development kits and have not been able to connect any of them to my PC running 'Windows 10 Enterprise', Version 1803, Build 17134.590.

When attaching the MT3620 to the computer, it does not find/install the serial driver.  I went to https://www.ftdichip.com/FTDrivers.htm and downloaded the driver for 'Windows 10' and it appears to have resolved that issue.  When then following the instructions,, I opened the 'Azure Sphere Developer Command Prompt Preview' and attempted to show attached devices, it said:

**error: An unexpected problem occurred. Please try again; if the issue persists, please refer to aka.ms/azurespheresupport for troubleshooting suggestions and support.
error: Command failed in 00:00:21.3147525.**

I then performed the azuresphere OS update thinking that may resolve the problem:
**```
C:\Users\043674\Documents>azsphere device recover
Starting device recovery. Please note that this may take up to 10 minutes.
Downloading recovery images...
Download complete.
Board found. Sending recovery bootloader.
Erasing flash.
Sending images.
Sending image 1 of 16.
Sending image 2 of 16.
Sending image 3 of 16.
Sending image 4 of 16.
Sending image 5 of 16.
Sending image 6 of 16.
Sending image 7 of 16.
Sending image 8 of 16.
Sending image 9 of 16.
Sending image 10 of 16.
Sending image 11 of 16.
Sending image 12 of 16.
Sending image 13 of 16.
Sending image 14 of 16.
Sending image 15 of 16.
Sending image 16 of 16.
Finished writing images; rebooting board.
error: Failed to establish communication with device after recovery. Try unplugging the device and plugging it back in, and verifying communication using 'azsphere device show-attached'. If that fails, try recovering the device again.
error: Failed to establish communication with device after recovery.
error: Command failed in 00:04:29.2063041.
```**
It appears that while the flash update works, subsequent communications with the board doesn't.  I verified that I have three COM ports active in Device Manager but I do not know what the port settings are.  It looks like they default to 9600N81 and I'm not sure if that is the correct settings as it isn't mentioned in any documentation.

At this point, I don't know how to proceed working with the hardware since it isn't communicating with the PC. Do you have any suggestions?
BTW, I also verified that J1 is open, J2 has a jumper installed, J3 P2-P3 are connected.

**Comment by jflynn129** [comment]
chirp, chirp, chirp... goes the crickets.  After waiting for a response and receiving none (as is typical for MSFT) I dug into this further.  the problem is the TAP Driver configuration.  When the SDK was installed, it was installed on a machine that was running on a virtual network (VPN).  The TAP driver incorrectly configured the TAP driver.  specifically, I had the "Cisco AnyConnect VPN client" installed.  The TAP driver had enabled the Cisco anyConnect Network Access Manager Filter Driver.  Once this was disabled, the SDK started working correctly.  Hopefully, this will help others.  It seems like the TAP driver can be the source of considerable interference.  

An even bigger problem is that MSFT will not own any issues like this and rarely responds to github issues that are raised (certainly not in a timely manner).  I'll leave this issue open and we will see how long it takes for them to simply close it.

**Comment by sergaz-msft** [comment]
@jflynn129 sorry for the delay on our answer. We are troubleshooting the issue with you on MSDN. Let's continue there and close it here, as we will have MVPs providing insights if they have seen a similar issue. Adding for reference: https://social.msdn.microsoft.com/Forums/en-US/6e384532-5d4a-412f-b176-996fb74b8e38/failed-to-upgrade-sphere-to-1811?forum=azuresphere

Thanks!
