### ISSUE TITLE
Power-loss resilience

### ISSUE THREAD

**Issue by daniel-larsen** [MicrosoftDocs/azure-sphere-issues#87]
Does azure sphere offer power-loss protection for writes to mutable storage?

I understand that azure sphere uses the littlefs file system which does feature power-loss protection. Does this benefit apply to the mutable storage API? If not, what is the recommended approach to ensure the mutable storage file does not get corrupted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6e5e32a-18fa-2084-519c-66b31cefcbba
* Version Independent ID: 594664c5-a625-119d-4e7e-22c1df8eac3f
* Content: [Azure Sphere storage](https://docs.microsoft.com/en-us/azure-sphere/app-development/storage#feedback)
* Content Source: [AzureSphere/articles/app-development/storage.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/storage.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@daniel-larsen Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by pennyo** [comment]
@daniel-larsen Great question. We plan to address this in an update of the documentation.

**Comment by Alberto-Vega-MSFT** [comment]
@daniel-larsen Thanks for your valuable feedback. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by sm1th** [comment]
@Alberto-Vega-MSFT @pennyo we are having issues restoring correct values from the mutable file after power loss, and would like to have an update on this.

Cheers!
