### ISSUE TITLE
Missing Features for MT3620, Crypto accelerators, Pluton

### ISSUE THREAD

**Issue by Buttje** [MicrosoftDocs/azure-sphere-issues#88]
The product brief advertises the Pluton Security Subsystem to provide security for the entire chip, including cryptographic engines and TRNG. I'd like to know which other features are offered, e.g. secure key store, and how I can make use of these features from an A7 normal world application.
Is there any more detailed documentation available about this features and how to use it (e.g. header files, rights to set in the manifest)?

Thanks,
Lutz

**Comment by sergaz-msft** [comment]
Thanks for your feedback @Buttje .

@pennyo can you help validate if we have documentation available related with the questions above?

Thank you!

**Comment by sergaz-msft** [comment]
Thanks @pennyo for syncing with me internally.

@Buttje, we currently don't have documentation related with your request above. We want to onboard your feedback though and for that please let me ask that you open a new feature request [here](https://feedback.azure.com/forums/915433-azure-sphere). Be as much specific as possible on the features needed for your scenario.

Share the link here so others can vote as well :).

Thank you!

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
