### ISSUE TITLE
Improper Header notation in SPI Documentation

### ISSUE THREAD

**Issue by toolboc** [MicrosoftDocs/azure-sphere-issues#89]
The current [Azure Sphere SPI documentation](https://docs.microsoft.com/en-us/azure-sphere/app-development/spi) contains an error in the [Header files section](https://docs.microsoft.com/en-us/azure-sphere/app-development/spi#header-files).

```
#include <applibs_versions.h>
#include <applibs/spi.h>
```

should be:

```
#include "applibs_versions.h"
#include <applibs/spi.h>
```

as the former notation does not properly resolve in Visual Studio.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff26fc0d-9baf-d571-da12-01d8fefeb209
* Version Independent ID: 535d773b-af8c-23ca-cae9-20e7124db74d
* Content: [Using SPI with Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/spi#feedback)
* Content Source: [AzureSphere/articles/app-development/spi.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/spi.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment]
@toolboc Thanks for the feedback and reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by pennyo** [comment]
We will correct this in an upcoming release of the documentation.

**Comment by pennyo** [comment]
This has been corrected in today's documentation release. Closing the issue.
