### ISSUE TITLE
Alter the steps

### ISSUE THREAD

**Issue by sandervandevelde** [MicrosoftDocs/azure-sphere-issues#9]
in [the azure-iot-sample documentation](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample), the description on how to get the IoTHub connection string is wrong.

The current description points to the device connection string (which is not there due to the usage of certificates in a DPS). But even if it was there, this is also not the connectionstring we want.

What we need is a connection string of the IoTHub itself, as found in the shared access policies, with sufficient rights. 

**Alter** the steps in to section *To get your IoT Hub Connection String* to:

* Go to the [Azure Portal](https://portal.azure.com/).
* Click on your IoT Hub.
* Under Settings, click *Shared access policies*.
* Click on the *iothubowner* policy. The permissions and keys are shown.
* In Shared access keys, Copy the text under *Connection string-primary key*.

This will give the readers the correct connectionstring.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by esalc** [comment]
Thank you for your feedback. We updated the topic with the recommended changes. Please let us know if we need to make additional changes.
