### ISSUE TITLE
can't use Device Explorer

### ISSUE THREAD

**Issue by al9419** [MicrosoftDocs/azure-sphere-issues#90]
I tried to reopen Device Explorer a few times, it stills shows it. After I close the error window, there is no sensor ID I can choose, it totally empty. 

<img width="498" alt="Capture" src="https://user-images.githubusercontent.com/48025247/56156634-08dcd700-5f94-11e9-84ad-898eaa75e755.PNG">

Here's the output I got from Visual Studio
<img width="393" alt="Capture1" src="https://user-images.githubusercontent.com/48025247/56156945-b05a0980-5f94-11e9-9309-0c6c850cd8f4.PNG">
<img width="538" alt="Capture2" src="https://user-images.githubusercontent.com/48025247/56158349-29a72b80-5f98-11e9-86ac-4d90611051d0.PNG">
(concerned about this output, but don't know how it might effect Device Explorer)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample#feedback)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by Alberto-Vega-MSFT** [comment]
@al9419 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
@al9419 Sorry for the delay were you able to overcome this issue?

**Comment by al9419** [comment]
No, the issue is still there.

**Comment by Alberto-Vega-MSFT** [comment]
@al9419  Can you please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can help get the support ticket opened for this issue.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @al9419  If you haven't created the support ticket please follow the instructions on the previous email. If you already did. Would you please share the support case number in an email to the address I shared with you?

**Comment by Alberto-Vega-MSFT** [comment]
I will be closing this issue for now since  we wil continue the conversation via email.
