### ISSUE TITLE
Incorrect enum identifier in example

### ISSUE THREAD

**Issue by ninosarmiento** [MicrosoftDocs/azure-sphere-issues#91]
the typedef enum identifier should be WifiConfig_Secuirity instead of GPIO_OutputMode;

typedef enum {
    WifiConfig_Security_Unknown = 0,
    WifiConfig_Security_Open = 1,
    WifiConfig_Security_Wpa2_Psk = 2
} **_GPIO_OutputMode;_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13d196b-4cd8-12b9-a8a0-08e020307fe2
* Version Independent ID: ac4fe98d-804e-9b52-8fa6-55915610256a
* Content: [WifiConfig_Security enumeration - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/enum-wificonfig-security#feedback)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/enum-wificonfig-security.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-wificonfig/enum-wificonfig-security.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by Karishma-Tiwari-MSFT** [comment]
@ninosarmiento 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Alberto-Vega-MSFT** [comment]
@ninosarmiento Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sergaz-msft** [comment]
@pennyo can you have a look at this? Thank you!

**Comment by pennyo** [comment]
Good catch! We'll fix this in the next update of the documentation.

**Comment by pennyo** [comment]
Fixed in today's 19.05 documentation release. Closing this issue.
