### ISSUE TITLE
IoT Hub Sample. Failed to connect to Iot Hub.

### ISSUE THREAD

**Issue by simon-jun** [MicrosoftDocs/azure-sphere-issues#92]
I tried to get the IoT Hub Sample Application to work. So i followed all the steps. I set up a IoT hub and DPS and linked them successfully. After that i created an enrollment group. Then I added my device to the IoT Hub via Visual Studio as described. I selected the correct DPS. 
Running the sample application now gives out the following error, you can also see in the picture:
[Azure IoT] IoTHubDeviceClient_CreateWithAzureSphereDeviceAuthProvisioning returned 'AZURE_SPHERE_PROV_RESULT_NETWORK_NOT_READY'.
ERROR: Failed to connect to IoT Hub; will retry in 60 seconds

![iot sample](https://user-images.githubusercontent.com/48299178/57224223-0b69a400-7009-11e9-8c6a-f0d5260ddad8.PNG)
My wifi is connected and working. 

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ad25d-ef35-4653-4bb4-d01795828e4d
* Version Independent ID: 25b26299-d3ca-45fa-54a1-923c0aca80d0
* Content: [Azure Sphere with Azure IoT Hub - sample application](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample)
* Content Source: [AzureSphere/articles/app-development/azure-iot-sample.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/azure-iot-sample.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Thanks for reporting this @simon-jun . I need to map this issue with a specific doc. Can you confirm [this is the one](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample) you are following? And in what step did it fail?

Also I need to ask if you followed the Prerequisites?

- Connect your Azure Sphere device to your PC and to a Wi-Fi network.
- Run azsphere device prep-debug to add the appdevelopment capability to your device.

++

- After you set up the subscription, you can create a hub. Log into the [Azure Portal](https://portal.azure.com/) and follow [these instructions](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub) to set up your hub and DPS and to link them together. If you already have a hub that is linked to DPS, you can skip step 1 in those instructions but you must still perform steps [2 through 5](https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub#step-2-download-the-tenant-authentication-ca-certificate) to enable authentication and automatic enrollment.

Thank you!

**Comment by simon-jun** [comment]
Yes that's the one I am following. I did the prerequisites. As I said I created a DPS and linked it to my existing IoT hub via steps 1-5. The status in my certificate exporer says it's verified.

The failure occurs at the step:"To prepare the sample code"...F5 to build and run.

In my output window you can see, that everything works except the connection to the iot hub.

**Comment by sergaz-msft** [comment]
Thanks for confirming it @simon-jun . Can you also please confirm that your network meets these requirements?: https://docs.microsoft.com/en-us/azure-sphere/network/ports-protocols-domains

Thank you!

**Comment by simon-jun** [comment]
No ports are blocked in the network. 
Do I need to setup port forwarding?

**Comment by sergaz-msft** [comment]
Can you try it on a different network? Thanks

**Comment by Olee25** [comment]
Had the same issue, my application was working fine one day then the next day it just stopped beeing able to connect to both iot central and iot hub (both where tested and worked fine before). Got the following message returned:

**Comment by simon-jun** [comment]
Using a different network actually worked, but i still don't know what's the issue on my first network. I'll look into it and report back when i have some news.

**Comment by sergaz-msft** [comment]
@Olee25 is it working now? @simon-jun my suggestion is that next time this happens please open a support ticket on azure portal so that we can look at Server Side Logs for both DPS, IoTHub and Azure Sphere.

Thanks!

**Comment by Olee25** [comment]
Ye, seems to be working fine now.

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
