### ISSUE TITLE
Continuity error

### ISSUE THREAD

**Issue by sm1th** [MicrosoftDocs/azure-sphere-issues#93]
Hi there, the following paragraph does not make sense as it is:

> Each feed assigned to a device group must supply a unique SKU set. In this example, both CM300 coffeemakers have the CM300 product SKU, so both devices **must version of the** CM300SW that the CM300 Test feed supplies.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13b5723-67c1-ebd8-5ae1-3c76f94cd5d3
* Version Independent ID: 14bd3533-ecd2-c30c-9132-d78bd8ca7ea1
* Content: [Deployment basics - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/deployment/deployment-concepts)
* Content Source: [AzureSphere/articles/deployment/deployment-concepts.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/deployment/deployment-concepts.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for your feedback.
You're right; looks like some words got lost along the way. We'll fix it in the next doc release.

**Comment by niheinba** [comment]
Do we know when that will be released?

**Comment by pennyo** [comment]
We've just published the documentation for our 19.05 release. This has been fixed. Closing the issue.
