### ISSUE TITLE
Unclear what "is not associated" means

### ISSUE THREAD

**Issue by kyleswinney** [MicrosoftDocs/azure-sphere-issues#95]
Section - Check the TAP-Windows adapter configuration
Step 2 - In Device Manager, open Network Adapters and select TAP-Windows adapter:
Text - "If you see more than one TAP adapter, or if you see only one TAP adapter but it is not associated with the Azure Sphere device,"

The phrase "associated with" is unclear.

After review of my system, I'm guessing it means the TAP - Windows Adapter is titled "Azure Sphere".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Troubleshooting for Azure Sphere installation and setup](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by BryanTrach-MSFT** [comment]
@kyleswinney Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by sergaz-msft** [comment]
Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sergaz-msft** [comment]
Hi @kyleswinney we will change the document text to the following on our next release happening soon:

"If you see more than one TAP adapter, or if you see only one TAP adapter but its name is not Azure Sphere, follow these steps to uninstall all TAP adapters and reinstall the SDK. If you see no TAP adapters, reinstall the SDK."

Thank you so much for your feedback!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
