### ISSUE TITLE
RSS is uncommon, consider alternate technologies

### ISSUE THREAD

**Issue by kyleswinney** [MicrosoftDocs/azure-sphere-issues#96]
I can't remember the last time I subscribed to an RSS feed. I'm betting I'm in the majority. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3204f0e0-78f1-405b-9509-9a3adf282925
* Version Independent ID: b63ae29e-d7ec-42d7-bb91-20f7cc33a1d5
* Content: [Azure Sphere notifications](https://docs.microsoft.com/en-us/azure-sphere/install/get-notifications)
* Content Source: [AzureSphere/articles/install/get-notifications.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/get-notifications.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by sergaz-msft** [comment]
Thank you for your feedback @kyleswinney . As of today, all Azure Updates are posted [here](https://azure.microsoft.com/en-us/updates/) and exposed on an RSS feed. Please kindly add a new feature request [on uservoice](https://feedback.azure.com/forums/34192--general-feedback) with your suggestion for alternative methods :). Let us know the link when you do it, so others can vote as well.

Thanks!

**Comment by sergaz-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
