### ISSUE TITLE
Error " A component with the same name ('Mt3620Blink1') already exists." after Quickstart: Blink tutorial

### ISSUE THREAD

**Issue by kyleswinney** [MicrosoftDocs/azure-sphere-issues#97]
Executing the command...
azsphere device link-feed --dependentfeedid 3369f0e1-dedf-49ec-a602-2aa98669fd61 --imagepath "C:\Users\kswinney\source\repos\Mt3620Blink1\Mt3620Blink1\bin\ARM\Debug\Mt3620Blink1.imagepackage" --newfeedname kswinneyFeedBlink
Getting the details for device with ID '25E9B57D70E4B2E1D5622AEEB3E8A4A5CF13C2EDFC327861A6AE04751282E49793BC9E68506F2FC4603C7834529F0D9F6DB7818DEA2AFE1E0E3D78232273B2BA'.

Outputs...
Uploading image from file 'C:\Users\kswinney\source\repos\Mt3620Blink1\Mt3620Blink1\bin\ARM\Debug\Mt3620Blink1.imagepackage':
 --&gt; Image ID:       fe3124d0-7106-4f87-9df3-a4e2939884fd
 --&gt; Component ID:   23a5a739-b6f4-47d7-bac5-fc5f9996ecf0
 --&gt; Component name: 'Mt3620Blink1'
Removing temporary state for uploaded image.

Erroring with...
error: A component with the same name ('Mt3620Blink1') already exists. Change the name in the application manifest and create a new image package.
Trace ID: 38749b6a-c64e-4adb-80f4-4dcac8c5be77
error: Command failed in 00:00:05.1624969.

Problem...
Because my project name is the same as in the tutorial, 'Mt3620Blink1', it is a duplicate to what's already been OTA'd by someone else.

Workaround...
Rebuild the project with a different name and repeat the OTA steps on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e04f52b-e1a2-44ae-1102-efb2e2096731
* Version Independent ID: 004091d7-2e9e-9074-98b9-b1c364f8603a
* Content: [Deploy your first application quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-first-deployment)
* Content Source: [AzureSphere/articles/quickstarts/qs-first-deployment.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-first-deployment.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by BryanTrach-MSFT** [comment]
@kyleswinney Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by sergaz-msft** [comment]
Thanks for the feedback @kyleswinney , I believe another alternative is that you change the Name and the ComponentId on "app_manifest.json" . @pennyo can we add a note on the doc for that?

Thanks!

**Comment by kyleswinney** [comment]
CC my Microsoft email

Yep…I solved the problem before I wrote the feedback just to make sure I had it right. My next step was to try a rename and modify the manifest. I appreciate you confirming.

BTW…that you guys are responding to feedback is awesome. Also, my only intention is to improve the Azure Sphere docs. This product is awesome!

…Kyle

PS…I’m open to Technical PM opportunities where I’d be building software

________________________________

**Comment by sergaz-msft** [comment]
Thank you so much @kyleswinney :). We have taken your feedback and will add a note on the doc on the next release happening soon.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
