### ISSUE TITLE
Request MT3620 M4 data sheet incorrect

### ISSUE THREAD

**Issue by PaulDFoster** [MicrosoftDocs/azure-sphere-issues#98]
The aka.ms/mt3620-m4-datasheet URL isn't live or implemented.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd75646-48be-ac9d-9c7b-72e7b37cc2af
* Version Independent ID: e82f57e8-7c97-4e66-23bc-2993ffa9e3e8
* Content: [Use peripherals in a real-time capable  application - Azure Sphere](https://docs.microsoft.com/en-gb/azure-sphere/app-development/use-peripherals-rt#feedback)
* Content Source: [AzureSphere/articles/app-development/use-peripherals-rt.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/app-development/use-peripherals-rt.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for the feedback. We will fix the link as soon as we can. 

You can request the datasheetfrom Avnet by emailing Azure-Sphere@avnet.com.

**Comment by PaulDFoster** [comment]
Hi Penny,

My email to Avent just got bounced too ☹

Cheers
Paul

PAUL FOSTER
Commercial Software Engineering
Senior Software Engineer | Microsoft UK
t: +44 (0)118 909 3838| m: +44 (0)7802 881926  e:paulfo@microsoft.com
____________________________________________________________________________________
Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading. RG6 1WG
[MSLogo]<http://www.microsoft.com/en-gb/default.aspx>

Pause for thought: If you’re not failing every now and again, it’s a sign you’re not doing anything very innovative.

**Comment by pennyo** [comment]
We've updated the documentation with the correct email address and confirmed that it is live. We will proceed to close this issue now.
