### ISSUE TITLE
Azure Sphere IOT Hub Sample Doc returns 404

### ISSUE THREAD

**Issue by jonasbark** [MicrosoftDocs/azure-sphere-issues#99]
https://docs.microsoft.com/de-de/azure-sphere/app-development/azure-iot-sample
returns a 404. It's linked in e.g. https://docs.microsoft.com/de-de/azure-sphere/app-development/azure-iot#using-iot-hub

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ed0e4594-2b67-cf34-2f18-fa0a58145bb1
* Version Independent ID: 5dc5e39a-7447-aa36-9c0a-ed45bdb9b3f4
* Content: [Azure Sphere mit Azure IoT Hub](https://docs.microsoft.com/de-de/azure-sphere/app-development/azure-iot#using-iot-hub)
* Content Source: [AzureSphere/articles/app-development/azure-iot.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.de-DE/blob/live-sxs/AzureSphere/articles/app-development/azure-iot.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by pennyo** [comment]
Thank you for the feedback. We will fix the link in a doc update as soon as we can. 

The Azure IoT sample is now available in the [Azure Sphere Samples repo on GitHub](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/AzureIoT).

**Comment by AshokPeddakotla-MSFT** [comment]
@pennyo Just checking in to see if there is any update on this issue so that it can be closed.

**Comment by pennyo** [comment]
Hi Ashok-
This is a localization issue; it appears in the German docs but not in the source docs. I’m following up off-line with you and our loc contact.
-Peny

**Comment by AshokPeddakotla-MSFT** [comment]
@jonasbark The documentation has been updated with the correct link. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
